import { useState, type FormEvent } from "react";
import { Link } from "@tanstack/react-router";
import { Button, ConfirmDialog, CopyField, Field, Modal, PageHeading, Panel, Pill, StateBlock, Table, Tabs, Warning } from "../../shared/ui";
import { useApplyClaudePreview, useApplyClinePreview, useApplyCodexPreview, useApplyCopilotPreview, useApplyDroidPreview, useApplyGrokBuildPreview, useApplyHermesPreview, useApplyJcodePreview, useApplyKiloPreview, useApplyManagedJsonPreview, useApplyManagedTomlPreview, useApplyOmpPreview, useApplyOpenClawPreview, useApplyOpenCodePreview, useClaudePreview, useClaudeStatus, useClinePreview, useClineStatus, useCliTools, useCodexPreview, useCodexStatus, useCopilotPreview, useCopilotStatus, useCreateMcpServer, useDeleteMcpServer, useDroidPreview, useDroidStatus, useGrokBuildPreview, useGrokBuildStatus, useHermesPreview, useHermesStatus, useJcodePreview, useJcodeStatus, useKiloPreview, useKiloStatus, useManagedJsonPreview, useManagedJsonStatus, useManagedTomlPreview, useManagedTomlStatus, useMcpMarketplace, useMcpServers, useOmpPreview, useOmpStatus, useOpenClawPreview, useOpenClawStatus, useOpenCodePreview, useOpenCodeStatus, useUpdateMcpServer, type ClaudePreview, type ClinePreview, type CodexPreview, type CopilotPreview, type DroidPreview, type GrokBuildPreview, type HermesPreview, type JcodePreview, type KiloPreview, type ManagedJsonPreview, type ManagedJsonTool, type ManagedTomlPreview, type ManagedTomlTool, type McpServer, type OmpPreview, type OpenClawPreview, type OpenCodePreview } from "./api";
import { toProblem } from "../../shared/errors";
import { useToast } from "../../shared/toast";

const statusLabel = { configured: "Config found", available: "Installed", not_detected: "Not detected" } as const;
const statusTone = { configured: "healthy", available: "info", not_detected: "muted" } as const;
const configurationRoutes: Record<string, "/integrations/cli-tools/claude" | "/integrations/cli-tools/codex" | "/integrations/cli-tools/opencode" | "/integrations/cli-tools/cline" | "/integrations/cli-tools/droid" | "/integrations/cli-tools/copilot" | "/integrations/cli-tools/crush" | "/integrations/cli-tools/pi" | "/integrations/cli-tools/smelt" | "/integrations/cli-tools/codewhale" | "/integrations/cli-tools/forge" | "/integrations/cli-tools/kilo" | "/integrations/cli-tools/openclaw" | "/integrations/cli-tools/deepseek-tui" | "/integrations/cli-tools/hermes" | "/integrations/cli-tools/jcode" | "/integrations/cli-tools/omp" | "/integrations/cli-tools/grok-build"> = {
  claude: "/integrations/cli-tools/claude", codex: "/integrations/cli-tools/codex", opencode: "/integrations/cli-tools/opencode", cline: "/integrations/cli-tools/cline", droid: "/integrations/cli-tools/droid", copilot: "/integrations/cli-tools/copilot", crush: "/integrations/cli-tools/crush", pi: "/integrations/cli-tools/pi", smelt: "/integrations/cli-tools/smelt", codewhale: "/integrations/cli-tools/codewhale", forge: "/integrations/cli-tools/forge", kilo: "/integrations/cli-tools/kilo", openclaw: "/integrations/cli-tools/openclaw", "deepseek-tui": "/integrations/cli-tools/deepseek-tui", hermes: "/integrations/cli-tools/hermes", jcode: "/integrations/cli-tools/jcode", omp: "/integrations/cli-tools/omp", "grok-build": "/integrations/cli-tools/grok-build",
};

export function CliTools() {
  const query = useCliTools();
  return <><PageHeading eyebrow="Integrations / CLI Tools" title="CLI tools" description="Connect local coding tools to the AIGate endpoint without exposing stored secrets." />
    <Warning>Detection checks this server's PATH and standard configuration locations. Select a supported tool card to review and apply its configuration.</Warning>
    {query.isError ? <div className="state-block error"><strong>Could not detect CLI tools</strong><p>{query.error instanceof Error ? query.error.message : "Request failed"}</p><Button onClick={() => void query.refetch()}>Retry</Button></div>
      : query.isPending ? <StateBlock state="loading" />
      : <div className="grid grid-3 section-gap">{query.data.map((tool) => { const route = configurationRoutes[tool.id]; const card = <article className="tool-card"><div className="row between"><span className="tool-glyph">⌘</span><Pill tone={statusTone[tool.status]}>{statusLabel[tool.status]}</Pill></div><strong>{tool.name}</strong><small>{tool.installed ? "Command found on server PATH" : "Command not found on server PATH"}</small>{tool.configPath && <small className="mono">{tool.configPath}</small>}{route && <small className="tool-link">Review configuration →</small>}</article>; return route ? <Link className="tool-card-link" key={tool.id} to={route}>{card}</Link> : <div key={tool.id}>{card}</div>; })}</div>}
  </>;
}

export function ClaudeToolDetail() {
  const [baseUrl, setBaseUrl] = useState(`${window.location.origin}/v1`);
  const [apiKey, setApiKey] = useState("");
  const [preview, setPreview] = useState<ClaudePreview | null>(null);
  const status = useClaudeStatus();
  const createPreview = useClaudePreview();
  const applyPreview = useApplyClaudePreview();
  const toast = useToast();
  const fail = (error: unknown) => toast({ tone: "error", ...toProblem(error) });
  const apply = () => preview && applyPreview.mutate(preview.previewId, { onSuccess: (result) => { setPreview(null); setApiKey(""); toast({ tone: "success", message: result.action === "reset" ? "Claude Code settings reset." : "Claude Code settings applied." }); }, onError: fail });
  const problem = status.error ? toProblem(status.error) : null;
  return <><PageHeading eyebrow="Integrations / CLI Tools / Claude Code" title="Claude Code" description="Preview a local Claude Code settings change, then apply that exact diff." action={status.data && <Pill tone={status.data.configured ? "healthy" : status.data.installed ? "info" : "muted"}>{status.data.configured ? "AIGate configured" : status.data.installed ? "Available" : "Not detected"}</Pill>} />
    {status.isPending ? <StateBlock state="loading" /> : problem ? <StateBlock state="error" code={problem.code} action={<Button onClick={() => void status.refetch()}>Retry</Button>} /> : <><div className="split section-gap"><Panel title="AIGate connection"><form className="stack" onSubmit={(event) => { event.preventDefault(); createPreview.mutate({ action: "configure", baseUrl, apiKey }, { onSuccess: setPreview, onError: fail }); }}><Field label="Base URL"><input className="input" value={baseUrl} onChange={(event) => setBaseUrl(event.target.value)} required /></Field><Field label="AIGate API key" hint="Saved as ANTHROPIC_AUTH_TOKEN in Claude Code settings. The dashboard never reads it back."><input className="input" type="password" autoComplete="new-password" value={apiKey} onChange={(event) => setApiKey(event.target.value)} minLength={8} maxLength={4096} required /></Field><Button type="submit" variant="primary" disabled={createPreview.isPending || applyPreview.isPending}>{createPreview.isPending ? "Preparing diffâ€¦" : "Preview configuration"}</Button></form></Panel><Panel title="Local file"><div className="stack"><CopyField label="Path" value={status.data!.configPath} /><Warning>Applying stores the key in this local file. The server takes an `.aigate.bak` backup before its atomic replacement.</Warning><Pill tone={status.data!.configured ? "healthy" : "muted"}>{status.data!.baseUrl ?? "No AIGate endpoint is configured"}</Pill></div></Panel></div>
      {status.data!.configured && <div className="section-gap"><Button variant="danger" disabled={createPreview.isPending || applyPreview.isPending} onClick={() => createPreview.mutate({ action: "reset" }, { onSuccess: setPreview, onError: fail })}>Preview reset</Button></div>}
      {preview && <Panel title={preview.action === "reset" ? "Review reset diff" : "Review configuration diff"} detail={`Target ${preview.configPath}`} className="section-gap"><div className="stack"><pre className="code-block">{preview.diff.map((line) => <div className={line.startsWith("+") ? "text-healthy" : line.startsWith("-") ? "text-danger" : "muted"} key={line}>{line}</div>)}{preview.diff.length === 0 && "No file changes."}</pre><p className="muted">Existing secrets are redacted. This preview expires at {new Date(preview.expiresAt).toLocaleTimeString()}.</p><div className="row"><Button onClick={() => setPreview(null)}>Cancel</Button><Button variant="primary" disabled={applyPreview.isPending || preview.diff.length === 0} onClick={apply}>{applyPreview.isPending ? "Applyingâ€¦" : "Apply reviewed diff"}</Button></div></div></Panel>}
    </>}
  </>;
}

export function OpenCodeToolDetail() {
  const [baseUrl, setBaseUrl] = useState(`${window.location.origin}/v1`);
  const [apiKey, setApiKey] = useState("");
  const [model, setModel] = useState("gpt-5-codex");
  const [preview, setPreview] = useState<OpenCodePreview | null>(null);
  const status = useOpenCodeStatus(); const createPreview = useOpenCodePreview(); const applyPreview = useApplyOpenCodePreview(); const toast = useToast();
  const fail = (error: unknown) => toast({ tone: "error", ...toProblem(error) });
  const apply = () => preview && applyPreview.mutate(preview.previewId, { onSuccess: (result) => { setPreview(null); setApiKey(""); toast({ tone: "success", message: result.action === "reset" ? "OpenCode settings reset." : "OpenCode settings applied." }); }, onError: fail });
  const problem = status.error ? toProblem(status.error) : null;
  return <><PageHeading eyebrow="Integrations / CLI Tools / OpenCode" title="OpenCode" description="Preview a local OpenCode provider change, then apply that exact diff." action={status.data && <Pill tone={status.data.configured ? "healthy" : status.data.installed ? "info" : "muted"}>{status.data.configured ? "AIGate configured" : status.data.installed ? "Available" : "Not detected"}</Pill>} />
    {status.isPending ? <StateBlock state="loading" /> : problem ? <StateBlock state="error" code={problem.code} action={<Button onClick={() => void status.refetch()}>Retry</Button>} /> : <><div className="split section-gap"><Panel title="AIGate connection"><form className="stack" onSubmit={(event) => { event.preventDefault(); createPreview.mutate({ action: "configure", baseUrl, apiKey, model }, { onSuccess: setPreview, onError: fail }); }}><Field label="Base URL"><input className="input" value={baseUrl} onChange={(event) => setBaseUrl(event.target.value)} required /></Field><Field label="AIGate API key" hint="Saved in OpenCode's 9router provider options. The dashboard never reads it back."><input className="input" type="password" autoComplete="new-password" value={apiKey} onChange={(event) => setApiKey(event.target.value)} minLength={8} maxLength={4096} required /></Field><Field label="Model"><input className="input" value={model} onChange={(event) => setModel(event.target.value)} maxLength={256} required /></Field><Button type="submit" variant="primary" disabled={createPreview.isPending || applyPreview.isPending}>{createPreview.isPending ? "Preparing diffâ€¦" : "Preview configuration"}</Button></form></Panel><Panel title="Local file"><div className="stack"><CopyField label="Path" value={status.data!.configPath} /><Warning>Applying stores the key in this local file. The server takes an `.aigate.bak` backup before its atomic replacement.</Warning><Pill tone={status.data!.configured ? "healthy" : "muted"}>{status.data!.model ? `Current model: ${status.data!.model}` : "No AIGate model is configured"}</Pill></div></Panel></div>
      {status.data!.configured && <div className="section-gap"><Button variant="danger" disabled={createPreview.isPending || applyPreview.isPending} onClick={() => createPreview.mutate({ action: "reset" }, { onSuccess: setPreview, onError: fail })}>Preview reset</Button></div>}
      {preview && <Panel title={preview.action === "reset" ? "Review reset diff" : "Review configuration diff"} detail={`Target ${preview.configPath}`} className="section-gap"><div className="stack"><pre className="code-block">{preview.diff.map((line) => <div className={line.startsWith("+") ? "text-healthy" : line.startsWith("-") ? "text-danger" : "muted"} key={line}>{line}</div>)}{preview.diff.length === 0 && "No file changes."}</pre><p className="muted">Existing secrets are redacted. This preview expires at {new Date(preview.expiresAt).toLocaleTimeString()}.</p><div className="row"><Button onClick={() => setPreview(null)}>Cancel</Button><Button variant="primary" disabled={applyPreview.isPending || preview.diff.length === 0} onClick={apply}>{applyPreview.isPending ? "Applyingâ€¦" : "Apply reviewed diff"}</Button></div></div></Panel>}
    </>}
  </>;
}

export function ClineToolDetail() {
  const [baseUrl, setBaseUrl] = useState(`${window.location.origin}/v1`); const [apiKey, setApiKey] = useState(""); const [model, setModel] = useState("gpt-5-codex"); const [preview, setPreview] = useState<ClinePreview | null>(null);
  const status = useClineStatus(); const createPreview = useClinePreview(); const applyPreview = useApplyClinePreview(); const toast = useToast(); const fail = (error: unknown) => toast({ tone: "error", ...toProblem(error) });
  const apply = () => preview && applyPreview.mutate(preview.previewId, { onSuccess: (result) => { setPreview(null); setApiKey(""); toast({ tone: "success", message: result.action === "reset" ? "Cline settings reset." : "Cline settings applied." }); }, onError: fail }); const problem = status.error ? toProblem(status.error) : null;
  return <><PageHeading eyebrow="Integrations / CLI Tools / Cline" title="Cline" description="Preview both Cline settings files, then apply that exact diff." action={status.data && <Pill tone={status.data.configured ? "healthy" : status.data.installed ? "info" : "muted"}>{status.data.configured ? "AIGate configured" : status.data.installed ? "Available" : "Not detected"}</Pill>} />
    {status.isPending ? <StateBlock state="loading" /> : problem ? <StateBlock state="error" code={problem.code} action={<Button onClick={() => void status.refetch()}>Retry</Button>} /> : <><div className="split section-gap"><Panel title="AIGate connection"><form className="stack" onSubmit={(event) => { event.preventDefault(); createPreview.mutate({ action: "configure", baseUrl, apiKey, model }, { onSuccess: setPreview, onError: fail }); }}><Field label="Base URL"><input className="input" value={baseUrl} onChange={(event) => setBaseUrl(event.target.value)} required /></Field><Field label="AIGate API key" hint="Saved in Cline's separate secrets file. The dashboard never reads it back."><input className="input" type="password" autoComplete="new-password" value={apiKey} onChange={(event) => setApiKey(event.target.value)} minLength={8} maxLength={4096} required /></Field><Field label="Model"><input className="input" value={model} onChange={(event) => setModel(event.target.value)} maxLength={256} required /></Field><Button type="submit" variant="primary" disabled={createPreview.isPending || applyPreview.isPending}>{createPreview.isPending ? "Preparing diffâ€¦" : "Preview configuration"}</Button></form></Panel><Panel title="Local files"><div className="stack"><CopyField label="State" value={status.data!.statePath} /><CopyField label="Secret" value={status.data!.secretsPath} /><Warning>Both files are previewed and backed up before apply. If the secret write fails, AIGate restores the state file.</Warning></div></Panel></div>
      {status.data!.configured && <div className="section-gap"><Button variant="danger" disabled={createPreview.isPending || applyPreview.isPending} onClick={() => createPreview.mutate({ action: "reset" }, { onSuccess: setPreview, onError: fail })}>Preview reset</Button></div>}
      {preview && <Panel title={preview.action === "reset" ? "Review reset diff" : "Review configuration diff"} detail={`${preview.statePath} and ${preview.secretsPath}`} className="section-gap"><div className="stack"><pre className="code-block">{preview.diff.map((line) => <div className={line.startsWith("+") ? "text-healthy" : line.startsWith("-") ? "text-danger" : "muted"} key={line}>{line}</div>)}</pre><p className="muted">Existing secrets are redacted. This preview expires at {new Date(preview.expiresAt).toLocaleTimeString()}.</p><div className="row"><Button onClick={() => setPreview(null)}>Cancel</Button><Button variant="primary" disabled={applyPreview.isPending || preview.diff.length === 0} onClick={apply}>{applyPreview.isPending ? "Applyingâ€¦" : "Apply reviewed diff"}</Button></div></div></Panel>}
    </>}
  </>;
}

export function DroidToolDetail() {
  const [baseUrl, setBaseUrl] = useState(`${window.location.origin}/v1`), [apiKey, setApiKey] = useState(""), [model, setModel] = useState("gpt-5-codex"), [preview, setPreview] = useState<DroidPreview | null>(null); const status = useDroidStatus(), make = useDroidPreview(), apply = useApplyDroidPreview(), toast = useToast(), fail = (e: unknown) => toast({ tone: "error", ...toProblem(e) });
  return <><PageHeading eyebrow="Integrations / CLI Tools / Droid" title="Droid" description="Preview a local Droid model change, then apply that exact diff." />{status.isPending ? <StateBlock state="loading" /> : status.isError ? <StateBlock state="error" code={toProblem(status.error).code} /> : <><form className="stack section-gap" onSubmit={(e) => { e.preventDefault(); make.mutate({ action: "configure", baseUrl, apiKey, model }, { onSuccess: setPreview, onError: fail }); }}><Field label="Base URL"><input className="input" value={baseUrl} onChange={(e) => setBaseUrl(e.target.value)} required /></Field><Field label="API key"><input className="input" type="password" value={apiKey} onChange={(e) => setApiKey(e.target.value)} minLength={8} required /></Field><Field label="Model"><input className="input" value={model} onChange={(e) => setModel(e.target.value)} required /></Field><Button type="submit" variant="primary">Preview configuration</Button></form>{preview && <Panel title="Review configuration diff"><pre className="code-block">{preview.diff.map((line) => <div key={line}>{line}</div>)}</pre><Button variant="primary" onClick={() => apply.mutate(preview.previewId, { onSuccess: () => { setPreview(null); setApiKey(""); toast({ tone: "success", message: "Droid settings applied." }); }, onError: fail })}>Apply reviewed diff</Button></Panel>}{status.data!.configured && <Button variant="danger" onClick={() => make.mutate({ action: "reset" }, { onSuccess: setPreview, onError: fail })}>Preview reset</Button>}</>}</>;
}

export function CopilotToolDetail() {
  const [baseUrl, setBaseUrl] = useState(`${window.location.origin}/v1`), [apiKey, setApiKey] = useState(""), [model, setModel] = useState("gpt-5-codex"), [preview, setPreview] = useState<CopilotPreview | null>(null); const status = useCopilotStatus(), make = useCopilotPreview(), apply = useApplyCopilotPreview(), toast = useToast(), fail = (e: unknown) => toast({ tone: "error", ...toProblem(e) });
  return <><PageHeading eyebrow="Integrations / CLI Tools / Copilot" title="GitHub Copilot" description="Preview a local VS Code language-model change, then apply that exact diff." />{status.isPending ? <StateBlock state="loading" /> : status.isError ? <StateBlock state="error" code={toProblem(status.error).code} /> : <><form className="stack section-gap" onSubmit={(e) => { e.preventDefault(); make.mutate({ action: "configure", baseUrl, apiKey, model }, { onSuccess: setPreview, onError: fail }); }}><Field label="Base URL"><input className="input" value={baseUrl} onChange={(e) => setBaseUrl(e.target.value)} required /></Field><Field label="AIGate API key"><input className="input" type="password" autoComplete="new-password" value={apiKey} onChange={(e) => setApiKey(e.target.value)} minLength={8} maxLength={4096} required /></Field><Field label="Model"><input className="input" value={model} onChange={(e) => setModel(e.target.value)} maxLength={256} required /></Field><Button type="submit" variant="primary" disabled={make.isPending || apply.isPending}>{make.isPending ? "Preparing diff…" : "Preview configuration"}</Button></form>{preview && <Panel title="Review configuration diff" detail={preview.configPath} className="section-gap"><pre className="code-block">{preview.diff.map((line) => <div className={line.startsWith("+") ? "text-healthy" : line.startsWith("-") ? "text-danger" : "muted"} key={line}>{line}</div>)}</pre><p className="muted">Existing secrets are redacted. This preview expires at {new Date(preview.expiresAt).toLocaleTimeString()}.</p><div className="row"><Button onClick={() => setPreview(null)}>Cancel</Button><Button variant="primary" disabled={apply.isPending || preview.diff.length === 0} onClick={() => apply.mutate(preview.previewId, { onSuccess: () => { setPreview(null); setApiKey(""); toast({ tone: "success", message: "Copilot settings applied. Reload VS Code to use it." }); }, onError: fail })}>{apply.isPending ? "Applying…" : "Apply reviewed diff"}</Button></div></Panel>}{status.data!.configured && <div className="section-gap"><Button variant="danger" disabled={make.isPending || apply.isPending} onClick={() => make.mutate({ action: "reset" }, { onSuccess: setPreview, onError: fail })}>Preview reset</Button></div>}</>}</>;
}

export function ManagedJsonToolDetail({ tool, title }: { tool: ManagedJsonTool; title: string }) {
  const [baseUrl, setBaseUrl] = useState(`${window.location.origin}/v1`), [apiKey, setApiKey] = useState(""), [model, setModel] = useState("gpt-5-codex"), [preview, setPreview] = useState<ManagedJsonPreview | null>(null); const status = useManagedJsonStatus(tool), make = useManagedJsonPreview(tool), apply = useApplyManagedJsonPreview(tool), toast = useToast(), fail = (e: unknown) => toast({ tone: "error", ...toProblem(e) });
  return <><PageHeading eyebrow={`Integrations / CLI Tools / ${title}`} title={title} description={`Preview a local ${title} configuration change, then apply that exact diff.`} />{status.isPending ? <StateBlock state="loading" /> : status.isError ? <StateBlock state="error" code={toProblem(status.error).code} /> : <><form className="stack section-gap" onSubmit={(e) => { e.preventDefault(); make.mutate({ action: "configure", baseUrl, apiKey, model }, { onSuccess: setPreview, onError: fail }); }}><Field label="Base URL"><input className="input" value={baseUrl} onChange={(e) => setBaseUrl(e.target.value)} required /></Field><Field label="AIGate API key"><input className="input" type="password" autoComplete="new-password" value={apiKey} onChange={(e) => setApiKey(e.target.value)} minLength={8} maxLength={4096} required /></Field><Field label="Model"><input className="input" value={model} onChange={(e) => setModel(e.target.value)} maxLength={256} required /></Field><Button type="submit" variant="primary" disabled={make.isPending || apply.isPending}>{make.isPending ? "Preparing diff…" : "Preview configuration"}</Button></form>{preview && <Panel title="Review configuration diff" detail={preview.configPath} className="section-gap"><pre className="code-block">{preview.diff.map((line) => <div className={line.startsWith("+") ? "text-healthy" : line.startsWith("-") ? "text-danger" : "muted"} key={line}>{line}</div>)}</pre><p className="muted">Existing secrets are redacted. This preview expires at {new Date(preview.expiresAt).toLocaleTimeString()}.</p><div className="row"><Button onClick={() => setPreview(null)}>Cancel</Button><Button variant="primary" disabled={apply.isPending || preview.diff.length === 0} onClick={() => apply.mutate(preview.previewId, { onSuccess: () => { setPreview(null); setApiKey(""); toast({ tone: "success", message: `${title} settings applied.` }); }, onError: fail })}>{apply.isPending ? "Applying…" : "Apply reviewed diff"}</Button></div></Panel>}{status.data!.configured && <div className="section-gap"><Button variant="danger" disabled={make.isPending || apply.isPending} onClick={() => make.mutate({ action: "reset" }, { onSuccess: setPreview, onError: fail })}>Preview reset</Button></div>}</>}</>;
}

export function ManagedTomlToolDetail({ tool, title }: { tool: ManagedTomlTool; title: string }) {
  const [baseUrl, setBaseUrl] = useState(`${window.location.origin}/v1`), [apiKey, setApiKey] = useState(""), [model, setModel] = useState("gpt-5-codex"), [preview, setPreview] = useState<ManagedTomlPreview | null>(null); const status = useManagedTomlStatus(tool), make = useManagedTomlPreview(tool), apply = useApplyManagedTomlPreview(tool), toast = useToast(), fail = (e: unknown) => toast({ tone: "error", ...toProblem(e) });
  return <><PageHeading eyebrow={`Integrations / CLI Tools / ${title}`} title={title} description={`Preview a local ${title} configuration change, then apply that exact diff.`} />{status.isPending ? <StateBlock state="loading" /> : status.isError ? <StateBlock state="error" code={toProblem(status.error).code} /> : <><form className="stack section-gap" onSubmit={(e) => { e.preventDefault(); make.mutate({ action: "configure", baseUrl, apiKey, model }, { onSuccess: setPreview, onError: fail }); }}><Field label="Base URL"><input className="input" value={baseUrl} onChange={(e) => setBaseUrl(e.target.value)} required /></Field><Field label="AIGate API key"><input className="input" type="password" autoComplete="new-password" value={apiKey} onChange={(e) => setApiKey(e.target.value)} minLength={8} maxLength={4096} required /></Field><Field label="Model"><input className="input" value={model} onChange={(e) => setModel(e.target.value)} maxLength={256} required /></Field><Button type="submit" variant="primary" disabled={make.isPending || apply.isPending}>{make.isPending ? "Preparing diff…" : "Preview configuration"}</Button></form>{preview && <Panel title="Review configuration diff" detail={preview.configPath} className="section-gap"><pre className="code-block">{preview.diff.map((line) => <div className={line.startsWith("+") ? "text-healthy" : line.startsWith("-") ? "text-danger" : "muted"} key={line}>{line}</div>)}</pre><p className="muted">Existing secrets are redacted. This preview expires at {new Date(preview.expiresAt).toLocaleTimeString()}.</p><div className="row"><Button onClick={() => setPreview(null)}>Cancel</Button><Button variant="primary" disabled={apply.isPending || preview.diff.length === 0} onClick={() => apply.mutate(preview.previewId, { onSuccess: () => { setPreview(null); setApiKey(""); toast({ tone: "success", message: `${title} settings applied.` }); }, onError: fail })}>{apply.isPending ? "Applying…" : "Apply reviewed diff"}</Button></div></Panel>}{status.data!.configured && <div className="section-gap"><Button variant="danger" disabled={make.isPending || apply.isPending} onClick={() => make.mutate({ action: "reset" }, { onSuccess: setPreview, onError: fail })}>Preview reset</Button></div>}</>}</>;
}

export function KiloToolDetail() {
  const [baseUrl, setBaseUrl] = useState(`${window.location.origin}/v1`), [apiKey, setApiKey] = useState(""), [model, setModel] = useState("gpt-5-codex"), [preview, setPreview] = useState<KiloPreview | null>(null); const status = useKiloStatus(), make = useKiloPreview(), apply = useApplyKiloPreview(), toast = useToast(), fail = (e: unknown) => toast({ tone: "error", ...toProblem(e) });
  return <><PageHeading eyebrow="Integrations / CLI Tools / Kilo" title="Kilo Code" description="Preview Kilo and VS Code settings, then apply that exact diff." />{status.isPending ? <StateBlock state="loading" /> : status.isError ? <StateBlock state="error" code={toProblem(status.error).code} /> : <><form className="stack section-gap" onSubmit={(e) => { e.preventDefault(); make.mutate({ action: "configure", baseUrl, apiKey, model }, { onSuccess: setPreview, onError: fail }); }}><Field label="Base URL"><input className="input" value={baseUrl} onChange={(e) => setBaseUrl(e.target.value)} required /></Field><Field label="AIGate API key"><input className="input" type="password" autoComplete="new-password" value={apiKey} onChange={(e) => setApiKey(e.target.value)} minLength={8} maxLength={4096} required /></Field><Field label="Model"><input className="input" value={model} onChange={(e) => setModel(e.target.value)} maxLength={256} required /></Field><Button type="submit" variant="primary" disabled={make.isPending || apply.isPending}>{make.isPending ? "Preparing diff…" : "Preview configuration"}</Button></form>{preview && <Panel title="Review configuration diff" detail={`${preview.authPath} and ${preview.vscodePath}`} className="section-gap"><pre className="code-block">{preview.diff.map((line) => <div className={line.startsWith("+") ? "text-healthy" : line.startsWith("-") ? "text-danger" : "muted"} key={line}>{line}</div>)}</pre><p className="muted">Existing secrets are redacted. This preview expires at {new Date(preview.expiresAt).toLocaleTimeString()}.</p><div className="row"><Button onClick={() => setPreview(null)}>Cancel</Button><Button variant="primary" disabled={apply.isPending || preview.diff.length === 0} onClick={() => apply.mutate(preview.previewId, { onSuccess: () => { setPreview(null); setApiKey(""); toast({ tone: "success", message: "Kilo settings applied." }); }, onError: fail })}>{apply.isPending ? "Applying…" : "Apply reviewed diff"}</Button></div></Panel>}{status.data!.configured && <div className="section-gap"><Button variant="danger" disabled={make.isPending || apply.isPending} onClick={() => make.mutate({ action: "reset" }, { onSuccess: setPreview, onError: fail })}>Preview reset</Button></div>}</>}</>;
}

export function HermesToolDetail() {
  const [baseUrl, setBaseUrl] = useState(`${window.location.origin}/v1`), [apiKey, setApiKey] = useState(""), [model, setModel] = useState("gpt-5-codex"), [preview, setPreview] = useState<HermesPreview | null>(null); const status = useHermesStatus(), make = useHermesPreview(), apply = useApplyHermesPreview(), toast = useToast(), fail = (e: unknown) => toast({ tone: "error", ...toProblem(e) });
  return <><PageHeading eyebrow="Integrations / CLI Tools / Hermes" title="Hermes Agent" description="Preview config.yaml and .env together, then apply that exact diff." />{status.isPending ? <StateBlock state="loading" /> : status.isError ? <StateBlock state="error" code={toProblem(status.error).code} /> : <><form className="stack section-gap" onSubmit={(e) => { e.preventDefault(); make.mutate({ action: "configure", baseUrl, apiKey, model }, { onSuccess: setPreview, onError: fail }); }}><Field label="Base URL"><input className="input" value={baseUrl} onChange={(e) => setBaseUrl(e.target.value)} required /></Field><Field label="AIGate API key"><input className="input" type="password" autoComplete="new-password" value={apiKey} onChange={(e) => setApiKey(e.target.value)} minLength={8} maxLength={4096} required /></Field><Field label="Model"><input className="input" value={model} onChange={(e) => setModel(e.target.value)} maxLength={256} required /></Field><Button type="submit" variant="primary" disabled={make.isPending || apply.isPending}>{make.isPending ? "Preparing diff…" : "Preview configuration"}</Button></form>{preview && <Panel title="Review configuration diff" detail={`${preview.configPath} and ${preview.envPath}`} className="section-gap"><pre className="code-block">{preview.diff.map((line) => <div className={line.startsWith("+") ? "text-healthy" : line.startsWith("-") ? "text-danger" : "muted"} key={line}>{line}</div>)}</pre><p className="muted">Existing secrets are redacted. This preview expires at {new Date(preview.expiresAt).toLocaleTimeString()}.</p><div className="row"><Button onClick={() => setPreview(null)}>Cancel</Button><Button variant="primary" disabled={apply.isPending || preview.diff.length === 0} onClick={() => apply.mutate(preview.previewId, { onSuccess: () => { setPreview(null); setApiKey(""); toast({ tone: "success", message: "Hermes settings applied." }); }, onError: fail })}>{apply.isPending ? "Applying…" : "Apply reviewed diff"}</Button></div></Panel>}{status.data!.configured && <div className="section-gap"><Button variant="danger" disabled={make.isPending || apply.isPending} onClick={() => make.mutate({ action: "reset" }, { onSuccess: setPreview, onError: fail })}>Preview reset</Button></div>}</>}</>;
}

export function JcodeToolDetail() {
  const [baseUrl, setBaseUrl] = useState(`${window.location.origin}/v1`), [apiKey, setApiKey] = useState(""), [model, setModel] = useState("gpt-5-codex"), [preview, setPreview] = useState<JcodePreview | null>(null); const status = useJcodeStatus(), make = useJcodePreview(), apply = useApplyJcodePreview(), toast = useToast(), fail = (e: unknown) => toast({ tone: "error", ...toProblem(e) });
  return <><PageHeading eyebrow="Integrations / CLI Tools / JCode" title="JCode" description="Preview the provider TOML and secret env file together, then apply that exact diff." />{status.isPending ? <StateBlock state="loading" /> : status.isError ? <StateBlock state="error" code={toProblem(status.error).code} /> : <><form className="stack section-gap" onSubmit={(e) => { e.preventDefault(); make.mutate({ action: "configure", baseUrl, apiKey, model }, { onSuccess: setPreview, onError: fail }); }}><Field label="Base URL"><input className="input" value={baseUrl} onChange={(e) => setBaseUrl(e.target.value)} required /></Field><Field label="AIGate API key"><input className="input" type="password" autoComplete="new-password" value={apiKey} onChange={(e) => setApiKey(e.target.value)} minLength={8} maxLength={4096} required /></Field><Field label="Default model"><input className="input" value={model} onChange={(e) => setModel(e.target.value)} maxLength={256} required /></Field><Button type="submit" variant="primary" disabled={make.isPending || apply.isPending}>{make.isPending ? "Preparing diff…" : "Preview configuration"}</Button></form>{preview && <Panel title="Review configuration diff" detail={`${preview.configPath} and ${preview.envPath}`} className="section-gap"><pre className="code-block">{preview.diff.map((line) => <div className={line.startsWith("+") ? "text-healthy" : line.startsWith("-") ? "text-danger" : "muted"} key={line}>{line}</div>)}</pre><p className="muted">Existing secrets are redacted. This preview expires at {new Date(preview.expiresAt).toLocaleTimeString()}.</p><div className="row"><Button onClick={() => setPreview(null)}>Cancel</Button><Button variant="primary" disabled={apply.isPending || preview.diff.length === 0} onClick={() => apply.mutate(preview.previewId, { onSuccess: () => { setPreview(null); setApiKey(""); toast({ tone: "success", message: "JCode settings applied." }); }, onError: fail })}>{apply.isPending ? "Applying…" : "Apply reviewed diff"}</Button></div></Panel>}{status.data!.configured && <div className="section-gap"><Button variant="danger" disabled={make.isPending || apply.isPending} onClick={() => make.mutate({ action: "reset" }, { onSuccess: setPreview, onError: fail })}>Preview reset</Button></div>}</>}</>;
}

export function OmpToolDetail() {
  const [baseUrl, setBaseUrl] = useState(`${window.location.origin}/v1`), [apiKey, setApiKey] = useState(""), [preview, setPreview] = useState<OmpPreview | null>(null); const status = useOmpStatus(), make = useOmpPreview(), apply = useApplyOmpPreview(), toast = useToast(), fail = (e: unknown) => toast({ tone: "error", ...toProblem(e) });
  return <><PageHeading eyebrow="Integrations / CLI Tools / Oh My Pi" title="Oh My Pi" description="Preview the 9router provider entry in models.yml, then apply that exact diff." />{status.isPending ? <StateBlock state="loading" /> : status.isError ? <StateBlock state="error" code={toProblem(status.error).code} /> : <><form className="stack section-gap" onSubmit={(e) => { e.preventDefault(); make.mutate({ action: "configure", baseUrl, apiKey }, { onSuccess: setPreview, onError: fail }); }}><Field label="Base URL"><input className="input" value={baseUrl} onChange={(e) => setBaseUrl(e.target.value)} required /></Field><Field label="AIGate API key"><input className="input" type="password" autoComplete="new-password" value={apiKey} onChange={(e) => setApiKey(e.target.value)} minLength={8} maxLength={4096} required /></Field><Button type="submit" variant="primary" disabled={make.isPending || apply.isPending}>{make.isPending ? "Preparing diff…" : "Preview configuration"}</Button></form>{preview && <Panel title="Review configuration diff" detail={preview.configPath} className="section-gap"><pre className="code-block">{preview.diff.map((line) => <div className={line.startsWith("+") ? "text-healthy" : line.startsWith("-") ? "text-danger" : "muted"} key={line}>{line}</div>)}</pre><p className="muted">Existing secrets are redacted. This preview expires at {new Date(preview.expiresAt).toLocaleTimeString()}.</p><div className="row"><Button onClick={() => setPreview(null)}>Cancel</Button><Button variant="primary" disabled={apply.isPending || preview.diff.length === 0} onClick={() => apply.mutate(preview.previewId, { onSuccess: () => { setPreview(null); setApiKey(""); toast({ tone: "success", message: "Oh My Pi settings applied." }); }, onError: fail })}>{apply.isPending ? "Applying…" : "Apply reviewed diff"}</Button></div></Panel>}{status.data!.configured && <div className="section-gap"><Button variant="danger" disabled={make.isPending || apply.isPending} onClick={() => make.mutate({ action: "reset" }, { onSuccess: setPreview, onError: fail })}>Preview reset</Button></div>}</>}</>;
}

export function GrokBuildToolDetail() {
  const [baseUrl, setBaseUrl] = useState(`${window.location.origin}/v1`), [apiKey, setApiKey] = useState(""), [model, setModel] = useState("gpt-5-codex"), [contextWindow, setContextWindow] = useState("128000"), [preview, setPreview] = useState<GrokBuildPreview | null>(null); const status = useGrokBuildStatus(), make = useGrokBuildPreview(), apply = useApplyGrokBuildPreview(), toast = useToast(), fail = (e: unknown) => toast({ tone: "error", ...toProblem(e) });
  return <><PageHeading eyebrow="Integrations / CLI Tools / Grok Build" title="Grok Build" description="Preview the AIGate model slot and default mapping before applying it." />{status.isPending ? <StateBlock state="loading" /> : status.isError ? <StateBlock state="error" code={toProblem(status.error).code} /> : <><form className="stack section-gap" onSubmit={(e) => { e.preventDefault(); make.mutate({ action: "configure", baseUrl, apiKey, model, contextWindow: Number(contextWindow) }, { onSuccess: setPreview, onError: fail }); }}><Field label="Base URL"><input className="input" value={baseUrl} onChange={(e) => setBaseUrl(e.target.value)} required /></Field><Field label="AIGate API key"><input className="input" type="password" autoComplete="new-password" value={apiKey} onChange={(e) => setApiKey(e.target.value)} minLength={8} maxLength={4096} required /></Field><Field label="Model"><input className="input" value={model} onChange={(e) => setModel(e.target.value)} maxLength={256} required /></Field><Field label="Context window"><input className="input" type="number" min="1" max="10000000" value={contextWindow} onChange={(e) => setContextWindow(e.target.value)} required /></Field><Button type="submit" variant="primary" disabled={make.isPending || apply.isPending}>{make.isPending ? "Preparing diff…" : "Preview configuration"}</Button></form>{preview && <Panel title="Review configuration diff" detail={preview.configPath} className="section-gap"><pre className="code-block">{preview.diff.map((line) => <div className={line.startsWith("+") ? "text-healthy" : line.startsWith("-") ? "text-danger" : "muted"} key={line}>{line}</div>)}</pre><p className="muted">Existing secrets are redacted. This preview expires at {new Date(preview.expiresAt).toLocaleTimeString()}.</p><div className="row"><Button onClick={() => setPreview(null)}>Cancel</Button><Button variant="primary" disabled={apply.isPending || preview.diff.length === 0} onClick={() => apply.mutate(preview.previewId, { onSuccess: () => { setPreview(null); setApiKey(""); toast({ tone: "success", message: "Grok Build settings applied." }); }, onError: fail })}>{apply.isPending ? "Applying…" : "Apply reviewed diff"}</Button></div></Panel>}{status.data!.configured && <div className="section-gap"><Button variant="danger" disabled={make.isPending || apply.isPending} onClick={() => make.mutate({ action: "reset" }, { onSuccess: setPreview, onError: fail })}>Preview reset</Button></div>}</>}</>;
}

export function OpenClawToolDetail() {
  const [baseUrl, setBaseUrl] = useState(`${window.location.origin}/v1`), [apiKey, setApiKey] = useState(""), [model, setModel] = useState("gpt-5-codex"), [agentModels, setAgentModels] = useState<Record<string, string>>({}), [preview, setPreview] = useState<OpenClawPreview | null>(null); const status = useOpenClawStatus(), make = useOpenClawPreview(), apply = useApplyOpenClawPreview(), toast = useToast(), fail = (e: unknown) => toast({ tone: "error", ...toProblem(e) });
  return <><PageHeading eyebrow="Integrations / CLI Tools / OpenClaw" title="OpenClaw" description="Preview the main and agent model files, then apply one reviewed change." />{status.isPending ? <StateBlock state="loading" /> : status.isError ? <StateBlock state="error" code={toProblem(status.error).code} /> : <><form className="stack section-gap" onSubmit={(e) => { e.preventDefault(); make.mutate({ action: "configure", baseUrl, apiKey, model, agentModels }, { onSuccess: setPreview, onError: fail }); }}><Field label="Base URL"><input className="input" value={baseUrl} onChange={(e) => setBaseUrl(e.target.value)} required /></Field><Field label="AIGate API key"><input className="input" type="password" autoComplete="new-password" value={apiKey} onChange={(e) => setApiKey(e.target.value)} minLength={8} maxLength={4096} required /></Field><Field label="Default model"><input className="input" value={model} onChange={(e) => setModel(e.target.value)} maxLength={256} required /></Field>{status.data!.agents.map((agent) => <Field key={agent.id} label={`Agent ${agent.id}`} hint={agent.model ? `Current: ${agent.model}. Leave blank to use the default model.` : "Leave blank to use the default model."}><input className="input" value={agentModels[agent.id] ?? ""} onChange={(e) => setAgentModels({ ...agentModels, [agent.id]: e.target.value })} maxLength={256} /></Field>)}<Button type="submit" variant="primary" disabled={make.isPending || apply.isPending}>{make.isPending ? "Preparing diff…" : "Preview configuration"}</Button></form>{preview && <Panel title="Review configuration diff" detail={`${preview.files.length} ${preview.files.length === 1 ? "file" : "files"}`} className="section-gap"><pre className="code-block">{preview.diff.map((line) => <div className={line.startsWith("+") ? "text-healthy" : line.startsWith("-") ? "text-danger" : "muted"} key={line}>{line}</div>)}</pre><p className="muted">Existing secrets are redacted. This preview expires at {new Date(preview.expiresAt).toLocaleTimeString()}.</p><div className="row"><Button onClick={() => setPreview(null)}>Cancel</Button><Button variant="primary" disabled={apply.isPending || preview.diff.length === 0} onClick={() => apply.mutate(preview.previewId, { onSuccess: () => { setPreview(null); setApiKey(""); toast({ tone: "success", message: "OpenClaw settings applied." }); }, onError: fail })}>{apply.isPending ? "Applying…" : "Apply reviewed diff"}</Button></div></Panel>}{status.data!.configured && <div className="section-gap"><Button variant="danger" disabled={make.isPending || apply.isPending} onClick={() => make.mutate({ action: "reset" }, { onSuccess: setPreview, onError: fail })}>Preview reset</Button></div>}</>}</>;
}

export function CliToolDetail() {
  const [baseUrl, setBaseUrl] = useState(`${window.location.origin}/v1`);
  const [apiKey, setApiKey] = useState("");
  const [model, setModel] = useState("gpt-5-codex");
  const [subagentModel, setSubagentModel] = useState("");
  const [preview, setPreview] = useState<CodexPreview | null>(null);
  const status = useCodexStatus();
  const createPreview = useCodexPreview();
  const applyPreview = useApplyCodexPreview();
  const toast = useToast();
  const fail = (error: unknown) => toast({ tone: "error", ...toProblem(error) });
  const previewConfig = () => createPreview.mutate({ action: "configure", baseUrl, apiKey, model, subagentModel }, { onSuccess: setPreview, onError: fail });
  const previewReset = () => createPreview.mutate({ action: "reset" }, { onSuccess: setPreview, onError: fail });
  const apply = () => preview && applyPreview.mutate(preview.previewId, { onSuccess: (result) => { setPreview(null); setApiKey(""); toast({ tone: "success", message: result.action === "reset" ? "Codex settings reset." : "Codex settings applied." }); }, onError: fail });
  const problem = status.error ? toProblem(status.error) : null;
  return <><PageHeading eyebrow="Integrations / CLI Tools / Codex" title="Codex" description="Preview a local Codex config change, then apply that exact diff." action={status.data && <Pill tone={status.data.configured ? "healthy" : status.data.installed ? "info" : "muted"}>{status.data.configured ? "AIGate configured" : status.data.installed ? "Available" : "Not detected"}</Pill>} />
    {status.isPending ? <StateBlock state="loading" /> : problem ? <StateBlock state="error" code={problem.code} action={<Button onClick={() => void status.refetch()}>Retry</Button>} /> : <>
      <div className="split section-gap"><Panel title="AIGate connection"><form className="stack" onSubmit={(event) => { event.preventDefault(); previewConfig(); }}>
        <Field label="Base URL"><input className="input" value={baseUrl} onChange={(event) => setBaseUrl(event.target.value)} required /></Field>
        <Field label="AIGate API key" hint="Stored in Codex config.toml as a bearer header. The dashboard never reads it back."><input className="input" type="password" autoComplete="new-password" value={apiKey} onChange={(event) => setApiKey(event.target.value)} minLength={8} maxLength={4096} required /></Field>
        <Field label="Default model"><input className="input" value={model} onChange={(event) => setModel(event.target.value)} maxLength={256} required /></Field>
        <Field label="Subagent model (optional)"><input className="input" value={subagentModel} onChange={(event) => setSubagentModel(event.target.value)} maxLength={256} /></Field>
        <Button type="submit" variant="primary" disabled={createPreview.isPending || applyPreview.isPending}>{createPreview.isPending ? "Preparing diff…" : "Preview configuration"}</Button>
      </form></Panel><Panel title="Local file"><div className="stack"><CopyField label="Path" value={status.data!.configPath} /><Warning>Applying stores the key in this local file. The server takes an `.aigate.bak` backup and restricts POSIX permissions to owner read/write.</Warning><Pill tone={status.data!.configured ? "healthy" : "muted"}>{status.data!.model ? `Current model: ${status.data!.model}` : "No AIGate model is configured"}</Pill></div></Panel></div>
      {status.data!.configured && <div className="section-gap"><Button variant="danger" disabled={createPreview.isPending || applyPreview.isPending} onClick={previewReset}>Preview reset</Button></div>}
      {preview && <Panel title={preview.action === "reset" ? "Review reset diff" : "Review configuration diff"} detail={`Target ${preview.configPath}`} className="section-gap"><div className="stack"><pre className="code-block">{preview.diff.map((line) => <div className={line.startsWith("+") ? "text-healthy" : line.startsWith("-") ? "text-danger" : "muted"} key={line}>{line}</div>)}{preview.diff.length === 0 && "No file changes."}</pre><p className="muted">Existing secrets are redacted. This preview expires at {new Date(preview.expiresAt).toLocaleTimeString()}.</p><div className="row"><Button onClick={() => setPreview(null)}>Cancel</Button><Button variant="primary" disabled={applyPreview.isPending || preview.diff.length === 0} onClick={apply}>{applyPreview.isPending ? "Applying…" : "Apply reviewed diff"}</Button></div></div></Panel>}
    </>}
  </>;
}

export function Skills() {
  const skills = [
    ["9router", "9Router (Entry)", "Setup and index of all capabilities.", null],
    ["9router-chat", "Chat", "Chat and code generation with streaming.", "/v1/chat/completions"],
    ["9router-image", "Image Generation", "Generate images through supported providers.", "/v1/images/generations"],
    ["9router-tts", "Text-to-Speech", "Generate speech through supported providers.", "/v1/audio/speech"],
    ["9router-stt", "Speech-to-Text", "Transcribe audio through supported providers.", "/v1/audio/transcriptions"],
    ["9router-embeddings", "Embeddings", "Create vectors for RAG and semantic search.", "/v1/embeddings"],
    ["9router-web-search", "Web Search", "Search the web through configured providers.", "/v1/search"],
    ["9router-web-fetch", "Web Fetch", "Fetch a URL as markdown, text, or HTML.", "/v1/web/fetch"],
  ] as const;
  const rawUrl = (id: string) => `https://raw.githubusercontent.com/decolua/9router/refs/heads/master/skills/${id}/SKILL.md`;
  return <><PageHeading eyebrow="Integrations / Skills" title="Agent skills" description="Copy a skill entry URL into your coding agent. The agent fetches the instructions from GitHub." />
    <Warning>These links point to the 9router repository's master branch.</Warning>
    <Panel title="Available skills" detail="Start with the entry skill, then add only the capabilities your agent needs." className="panel-flush"><Table columns={["Skill", "Purpose", "Endpoint", "Entry URL"]} rows={skills.map(([id, name, description, endpoint]) => [<strong>{name}</strong>, description, endpoint ? <code>{endpoint}</code> : <Pill tone="info">Start here</Pill>, <CopyField value={rawUrl(id)} />])} /></Panel>
  </>;
}

export function Mcp() {
  const [tab, setTab] = useState("Servers");
  const [exportClient, setExportClient] = useState<"claude" | "cursor">("claude");
  const [editing, setEditing] = useState<McpServer | "new" | null>(null);
  const [remove, setRemove] = useState<McpServer | null>(null);
  const servers = useMcpServers();
  const marketplace = useMcpMarketplace();
  const create = useCreateMcpServer();
  const update = useUpdateMcpServer();
  const deletion = useDeleteMcpServer();
  const toast = useToast();
  const fail = (error: unknown) => toast({ tone: "error", ...toProblem(error) });
  const exportServers = (servers.data ?? []).filter((server) => server.enabled);
  const exportConfig = JSON.stringify({ mcpServers: Object.fromEntries(exportServers.map((server) => [server.name, exportClient === "claude" ? { type: "http", url: server.url } : { url: server.url }])) }, null, 2);
  const submit = (event: FormEvent<HTMLFormElement>) => {
    event.preventDefault();
    const form = new FormData(event.currentTarget);
    const scope: McpServer["scope"] = form.get("scope") === "project" ? "project" : "user";
    const input = { name: String(form.get("name") ?? ""), url: String(form.get("url") ?? ""), scope };
    const done = () => { setEditing(null); toast({ tone: "success", message: editing === "new" ? "MCP server saved." : "MCP server updated." }); };
    if (editing === "new") create.mutate(input, { onSuccess: done, onError: fail });
    else if (editing) update.mutate({ id: editing.id, ...input }, { onSuccess: done, onError: fail });
  };
  return <><PageHeading eyebrow="Integrations / MCP" title="MCP server registry" description="Save remote MCP server endpoints for later client setup." action={<Button variant="primary" onClick={() => setEditing("new")}>+ Add server</Button>} />
    <Warning>MCP endpoints are stored on the AIGate host; AIGate does not connect to, probe, or expose these servers yet. HTTPS is required except for localhost.</Warning>
    <Tabs items={["Servers", "Marketplace", "Storage"]} active={tab} onChange={setTab} />
    {tab === "Servers" && <Panel title="Saved servers" detail="Enabled controls the saved entry only; it does not start a connection." className="section-gap panel-flush">
      {servers.isPending ? <StateBlock state="loading" /> : servers.isError ? <StateBlock state="error" code={toProblem(servers.error).code} action={<Button onClick={() => void servers.refetch()}>Retry</Button>} />
        : <Table empty="No MCP servers saved. Add an HTTPS server URL to begin." columns={["Server", "Endpoint", "Scope", "State", ""]} rows={(servers.data ?? []).map((server) => [<strong>{server.name}</strong>, <code>{server.url}</code>, server.scope, <Pill tone={server.enabled ? "info" : "muted"}>{server.enabled ? "Saved" : "Paused"}</Pill>, <><Button variant="ghost" onClick={() => update.mutate({ id: server.id, enabled: !server.enabled }, { onError: fail })}>{server.enabled ? "Pause" : "Enable"}</Button><Button variant="ghost" onClick={() => setEditing(server)}>Edit</Button><Button variant="ghost" onClick={() => setRemove(server)}>Delete</Button></>])} />}
    </Panel>}
    {tab === "Marketplace" && <Panel title="MCP marketplace" detail="Direct HTTPS servers from the Anthropic MCP registry. OAuth servers must be authorized in the client." className="section-gap panel-flush">{marketplace.isPending ? <StateBlock state="loading" /> : marketplace.isError ? <StateBlock state="error" code={toProblem(marketplace.error).code} action={<Button onClick={() => void marketplace.refetch()}>Retry</Button>} /> : <Table empty="No direct-connect MCP servers are currently available." columns={["Server", "Description", "Transport", ""]} rows={(marketplace.data?.servers ?? []).map((server) => [<strong>{server.title}</strong>, <span>{server.description || server.url}</span>, <Pill tone={server.requiresAuth ? "info" : "healthy"}>{server.requiresAuth ? "OAuth" : server.transport}</Pill>, <Button variant="ghost" disabled={create.isPending || (servers.data ?? []).some((saved) => saved.name.toLowerCase() === server.name.toLowerCase())} onClick={() => create.mutate({ name: server.name, url: server.url, scope: "user" }, { onSuccess: () => toast({ tone: "success", message: `${server.title} saved.` }), onError: fail })}>Add</Button>])} />}</Panel>}
    {tab === "Storage" && <div className="stack section-gap"><Panel title="AIGate storage"><p>Server definitions are stored in <code>mcp-servers.json</code> under AIGATE_DATA_DIR with owner-only file permissions and an atomic backup.</p></Panel>
      <Panel title="Copy client configuration" detail="Only enabled servers are included. Copy and merge this snippet into the selected client on your workstation."><div className="stack"><Field label="Client"><select className="input" value={exportClient} onChange={(event) => setExportClient(event.target.value === "cursor" ? "cursor" : "claude")}><option value="claude">Claude Code</option><option value="cursor">Cursor</option></select></Field>
        {servers.isError ? <StateBlock state="error" code={toProblem(servers.error).code} /> : servers.isPending ? <StateBlock state="loading" /> : exportServers.length ? <><pre className="code-block">{exportConfig}</pre><Button onClick={() => void navigator.clipboard.writeText(exportConfig).then(() => toast({ tone: "success", message: "MCP config copied." }), () => toast({ tone: "error", message: "Clipboard access was denied." }))}>Copy JSON</Button></> : <p className="muted">Enable at least one saved server to create a config snippet.</p>}
        <Warning>AIGate does not write to the client config. The browser may run on a different machine from the AIGate server.</Warning>
      </div></Panel></div>}
    {editing && <Modal title={editing === "new" ? "Add MCP server" : `Edit ${editing.name}`} onClose={() => setEditing(null)}><form onSubmit={submit} className="stack"><Field label="Name"><input className="input" name="name" defaultValue={editing === "new" ? "" : editing.name} maxLength={64} required /></Field><Field label="Server URL" hint="HTTPS only; HTTP is allowed for localhost. URL credentials and query parameters are not accepted."><input className="input" name="url" type="url" defaultValue={editing === "new" ? "" : editing.url} maxLength={2048} required /></Field><Field label="Scope"><select className="input" name="scope" defaultValue={editing === "new" ? "user" : editing.scope}><option value="user">User</option><option value="project">Project</option></select></Field><div className="modal-actions"><Button onClick={() => setEditing(null)}>Cancel</Button><Button type="submit" variant="primary" disabled={create.isPending || update.isPending}>{create.isPending || update.isPending ? "Saving…" : "Save server"}</Button></div></form></Modal>}
    {remove && <ConfirmDialog name={remove.name} detail="Remove this saved server entry from AIGate?" onClose={() => setRemove(null)} onConfirm={() => deletion.mutate(remove.id, { onSuccess: () => { setRemove(null); toast({ tone: "success", message: `Removed ${remove.name}.` }); }, onError: fail })} />}
  </>;
}
