import { useState } from "react";
import { Button, Field, PageHeading, Panel, StateBlock } from "../../shared/ui";
import { useApplyCopilotPreview, useApplyDroidPreview, useApplyGrokBuildPreview, useApplyHermesPreview, useApplyJcodePreview, useApplyKiloPreview, useApplyManagedJsonPreview, useApplyManagedTomlPreview, useApplyOmpPreview, useApplyOpenClawPreview, useCopilotPreview, useCopilotStatus, useDroidPreview, useDroidStatus, useGrokBuildPreview, useGrokBuildStatus, useHermesPreview, useHermesStatus, useJcodePreview, useJcodeStatus, useKiloPreview, useKiloStatus, useManagedJsonPreview, useManagedJsonStatus, useManagedTomlPreview, useManagedTomlStatus, useOmpPreview, useOmpStatus, useOpenClawPreview, useOpenClawStatus, type CopilotPreview, type DroidPreview, type GrokBuildPreview, type HermesPreview, type JcodePreview, type KiloPreview, type ManagedJsonPreview, type ManagedJsonTool, type ManagedTomlPreview, type ManagedTomlTool, type OmpPreview, type OpenClawPreview } from "./api";
import { toProblem } from "../../shared/errors";
import { useToast } from "../../shared/toast";

export function DroidToolDetail() {
  const [baseUrl, setBaseUrl] = useState(`${window.location.origin}/v1`), [apiKey, setApiKey] = useState(""), [model, setModel] = useState("gpt-5-codex"), [preview, setPreview] = useState<DroidPreview | null>(null); const status = useDroidStatus(), make = useDroidPreview(), apply = useApplyDroidPreview(), toast = useToast(), fail = (e: unknown) => toast({ tone: "error", ...toProblem(e) });
  return <><PageHeading eyebrow="Integrations / CLI Tools / Droid" title="Droid" description="Preview a local Droid model change, then apply that exact diff." />{status.isPending ? <StateBlock state="loading" /> : status.isError ? <StateBlock state="error" code={toProblem(status.error).code} /> : <><form className="stack section-gap" onSubmit={(e) => { e.preventDefault(); make.mutate({ action: "configure", baseUrl, apiKey, model }, { onSuccess: setPreview, onError: fail }); }}><Field label="Base URL"><input className="input" value={baseUrl} onChange={(e) => setBaseUrl(e.target.value)} required /></Field><Field label="API key"><input className="input" type="password" value={apiKey} onChange={(e) => setApiKey(e.target.value)} minLength={8} required /></Field><Field label="Model"><input className="input" value={model} onChange={(e) => setModel(e.target.value)} required /></Field><Button type="submit" variant="primary">Preview configuration</Button></form>{preview && <Panel title="Review configuration diff"><pre className="code-block">{preview.diff.map((line) => <div key={line}>{line}</div>)}</pre><Button variant="primary" onClick={() => apply.mutate(preview.previewId, { onSuccess: () => { setPreview(null); setApiKey(""); toast({ tone: "success", message: "Droid settings applied." }); }, onError: fail })}>Apply reviewed diff</Button></Panel>}{status.data!.configured && <Button variant="danger" onClick={() => make.mutate({ action: "reset" }, { onSuccess: setPreview, onError: fail })}>Preview reset</Button>}</>}</>;
}

export function CopilotToolDetail() {
  const [baseUrl, setBaseUrl] = useState(`${window.location.origin}/v1`), [apiKey, setApiKey] = useState(""), [model, setModel] = useState("gpt-5-codex"), [preview, setPreview] = useState<CopilotPreview | null>(null); const status = useCopilotStatus(), make = useCopilotPreview(), apply = useApplyCopilotPreview(), toast = useToast(), fail = (e: unknown) => toast({ tone: "error", ...toProblem(e) });
  return <><PageHeading eyebrow="Integrations / CLI Tools / Copilot" title="GitHub Copilot" description="Preview a local VS Code language-model change, then apply that exact diff." />{status.isPending ? <StateBlock state="loading" /> : status.isError ? <StateBlock state="error" code={toProblem(status.error).code} /> : <><form className="stack section-gap" onSubmit={(e) => { e.preventDefault(); make.mutate({ action: "configure", baseUrl, apiKey, model }, { onSuccess: setPreview, onError: fail }); }}><Field label="Base URL"><input className="input" value={baseUrl} onChange={(e) => setBaseUrl(e.target.value)} required /></Field><Field label="AIGate API key"><input className="input" type="password" autoComplete="new-password" value={apiKey} onChange={(e) => setApiKey(e.target.value)} minLength={8} maxLength={4096} required /></Field><Field label="Model"><input className="input" value={model} onChange={(e) => setModel(e.target.value)} maxLength={256} required /></Field><Button type="submit" variant="primary" disabled={make.isPending || apply.isPending}>{make.isPending ? "Preparing diff…" : "Preview configuration"}</Button></form>{preview && <Panel title="Review configuration diff" detail={preview.configPath} className="section-gap"><pre className="code-block">{preview.diff.map((line) => <div className={line.startsWith("+") ? "text-healthy" : line.startsWith("-") ? "text-danger" : "muted"} key={line}>{line}</div>)}</pre><p className="muted">Existing secrets are redacted. This preview expires at {new Date(preview.expiresAt).toLocaleTimeString()}.</p><div className="row"><Button onClick={() => setPreview(null)}>Cancel</Button><Button variant="primary" disabled={apply.isPending || preview.diff.length === 0} onClick={() => apply.mutate(preview.previewId, { onSuccess: () => { setPreview(null); setApiKey(""); toast({ tone: "success", message: "Copilot settings applied. Reload VS Code to use it." }); }, onError: fail })}>{apply.isPending ? "Applying…" : "Apply reviewed diff"}</Button></div></Panel>}{status.data!.configured && <div className="section-gap"><Button variant="danger" disabled={make.isPending || apply.isPending} onClick={() => make.mutate({ action: "reset" }, { onSuccess: setPreview, onError: fail })}>Preview reset</Button></div>}</>}</>;
}

export function ManagedJsonToolDetail({ tool, title }: { tool: ManagedJsonTool; title: string }) {
  const [baseUrl, setBaseUrl] = useState(`${window.location.origin}/v1`), [apiKey, setApiKey] = useState(""), [model, setModel] = useState("gpt-5-codex"), [preview, setPreview] = useState<ManagedJsonPreview | null>(null); const status = useManagedJsonStatus(tool), make = useManagedJsonPreview(tool), apply = useApplyManagedJsonPreview(tool), toast = useToast(), fail = (e: unknown) => toast({ tone: "error", ...toProblem(e) });
  return <><PageHeading eyebrow={`Integrations / CLI Tools / ${title}`} title={title} description={`Preview a local ${title} configuration change, then apply that exact diff.`} />{status.isPending ? <StateBlock state="loading" /> : status.isError ? <StateBlock state="error" code={toProblem(status.error).code} /> : <><form className="stack section-gap" onSubmit={(e) => { e.preventDefault(); make.mutate({ action: "configure", baseUrl, apiKey, model }, { onSuccess: setPreview, onError: fail }); }}><Field label="Base URL"><input className="input" value={baseUrl} onChange={(e) => setBaseUrl(e.target.value)} required /></Field><Field label="AIGate API key"><input className="input" type="password" autoComplete="new-password" value={apiKey} onChange={(e) => setApiKey(e.target.value)} minLength={8} maxLength={4096} required /></Field><Field label="Model"><input className="input" value={model} onChange={(e) => setModel(e.target.value)} maxLength={256} required /></Field><Button type="submit" variant="primary" disabled={make.isPending || apply.isPending}>{make.isPending ? "Preparing diff…" : "Preview configuration"}</Button></form>{preview && <Panel title="Review configuration diff" detail={preview.configPath} className="section-gap"><pre className="code-block">{preview.diff.map((line) => <div className={line.startsWith("+") ? "text-healthy" : line.startsWith("-") ? "text-danger" : "muted"} key={line}>{line}</div>)}</pre><p className="muted">Existing secrets are redacted. This preview expires at {new Date(preview.expiresAt).toLocaleTimeString()}.</p><div className="row"><Button onClick={() => setPreview(null)}>Cancel</Button><Button variant="primary" disabled={apply.isPending || preview.diff.length === 0} onClick={() => apply.mutate(preview.previewId, { onSuccess: () => { setPreview(null); setApiKey(""); toast({ tone: "success", message: `${title} settings applied.` }); }, onError: fail })}>{apply.isPending ? "Applying…" : "Apply reviewed diff"}</Button></div></Panel>}{status.data!.configured && <div className="section-gap"><Button variant="danger" disabled={make.isPending || apply.isPending} onClick={() => make.mutate({ action: "reset" }, { onSuccess: setPreview, onError: fail })}>Preview reset</Button></div>}</>}</>;
}

export function ManagedTomlToolDetail({ tool, title }: { tool: ManagedTomlTool; title: string }) {
  const [baseUrl, setBaseUrl] = useState(`${window.location.origin}/v1`), [apiKey, setApiKey] = useState(""), [model, setModel] = useState("gpt-5-codex"), [preview, setPreview] = useState<ManagedTomlPreview | null>(null); const status = useManagedTomlStatus(tool), make = useManagedTomlPreview(tool), apply = useApplyManagedTomlPreview(tool), toast = useToast(), fail = (e: unknown) => toast({ tone: "error", ...toProblem(e) });
  return <><PageHeading eyebrow={`Integrations / CLI Tools / ${title}`} title={title} description={`Preview a local ${title} configuration change, then apply that exact diff.`} />{status.isPending ? <StateBlock state="loading" /> : status.isError ? <StateBlock state="error" code={toProblem(status.error).code} /> : <><form className="stack section-gap" onSubmit={(e) => { e.preventDefault(); make.mutate({ action: "configure", baseUrl, apiKey, model }, { onSuccess: setPreview, onError: fail }); }}><Field label="Base URL"><input className="input" value={baseUrl} onChange={(e) => setBaseUrl(e.target.value)} required /></Field><Field label="AIGate API key"><input className="input" type="password" autoComplete="new-password" value={apiKey} onChange={(e) => setApiKey(e.target.value)} minLength={8} maxLength={4096} required /></Field><Field label="Model"><input className="input" value={model} onChange={(e) => setModel(e.target.value)} maxLength={256} required /></Field><Button type="submit" variant="primary" disabled={make.isPending || apply.isPending}>{make.isPending ? "Preparing diff…" : "Preview configuration"}</Button></form>{preview && <Panel title="Review configuration diff" detail={preview.configPath} className="section-gap"><pre className="code-block">{preview.diff.map((line) => <div className={line.startsWith("+") ? "text-healthy" : line.startsWith("-") ? "text-danger" : "muted"} key={line}>{line}</div>)}</pre><p className="muted">Existing secrets are redacted. This preview expires at {new Date(preview.expiresAt).toLocaleTimeString()}.</p><div className="row"><Button onClick={() => setPreview(null)}>Cancel</Button><Button variant="primary" disabled={apply.isPending || preview.diff.length === 0} onClick={() => apply.mutate(preview.previewId, { onSuccess: () => { setPreview(null); setApiKey(""); toast({ tone: "success", message: `${title} settings applied.` }); }, onError: fail })}>{apply.isPending ? "Applying…" : "Apply reviewed diff"}</Button></div></Panel>}{status.data!.configured && <div className="section-gap"><Button variant="danger" disabled={make.isPending || apply.isPending} onClick={() => make.mutate({ action: "reset" }, { onSuccess: setPreview, onError: fail })}>Preview reset</Button></div>}</>}</>;
}

export function KiloToolDetail() {
  const [baseUrl, setBaseUrl] = useState(`${window.location.origin}/v1`), [apiKey, setApiKey] = useState(""), [model, setModel] = useState("gpt-5-codex"), [preview, setPreview] = useState<KiloPreview | null>(null); const status = useKiloStatus(), make = useKiloPreview(), apply = useApplyKiloPreview(), toast = useToast(), fail = (e: unknown) => toast({ tone: "error", ...toProblem(e) });
  return <><PageHeading eyebrow="Integrations / CLI Tools / Kilo" title="Kilo Code" description="Preview Kilo and VS Code settings, then apply that exact diff." />{status.isPending ? <StateBlock state="loading" /> : status.isError ? <StateBlock state="error" code={toProblem(status.error).code} /> : <><form className="stack section-gap" onSubmit={(e) => { e.preventDefault(); make.mutate({ action: "configure", baseUrl, apiKey, model }, { onSuccess: setPreview, onError: fail }); }}><Field label="Base URL"><input className="input" value={baseUrl} onChange={(e) => setBaseUrl(e.target.value)} required /></Field><Field label="AIGate API key"><input className="input" type="password" autoComplete="new-password" value={apiKey} onChange={(e) => setApiKey(e.target.value)} minLength={8} maxLength={4096} required /></Field><Field label="Model"><input className="input" value={model} onChange={(e) => setModel(e.target.value)} maxLength={256} required /></Field><Button type="submit" variant="primary" disabled={make.isPending || apply.isPending}>{make.isPending ? "Preparing diff…" : "Preview configuration"}</Button></form>{preview && <Panel title="Review configuration diff" detail={`${preview.authPath} and ${preview.vscodePath}`} className="section-gap"><pre className="code-block">{preview.diff.map((line) => <div className={line.startsWith("+") ? "text-healthy" : line.startsWith("-") ? "text-danger" : "muted"} key={line}>{line}</div>)}</pre><p className="muted">Existing secrets are redacted. This preview expires at {new Date(preview.expiresAt).toLocaleTimeString()}.</p><div className="row"><Button onClick={() => setPreview(null)}>Cancel</Button><Button variant="primary" disabled={apply.isPending || preview.diff.length === 0} onClick={() => apply.mutate(preview.previewId, { onSuccess: () => { setPreview(null); setApiKey(""); toast({ tone: "success", message: "Kilo settings applied." }); }, onError: fail })}>{apply.isPending ? "Applying…" : "Apply reviewed diff"}</Button></div></Panel>}{status.data!.configured && <div className="section-gap"><Button variant="danger" disabled={make.isPending || apply.isPending} onClick={() => make.mutate({ action: "reset" }, { onSuccess: setPreview, onError: fail })}>Preview reset</Button></div>}</>}</>;
}

export function HermesToolDetail() {
  const [baseUrl, setBaseUrl] = useState(`${window.location.origin}/v1`), [apiKey, setApiKey] = useState(""), [model, setModel] = useState("gpt-5-codex"), [preview, setPreview] = useState<HermesPreview | null>(null); const status = useHermesStatus(), make = useHermesPreview(), apply = useApplyHermesPreview(), toast = useToast(), fail = (e: unknown) => toast({ tone: "error", ...toProblem(e) });
  return <><PageHeading eyebrow="Integrations / CLI Tools / Hermes" title="Hermes Agent" description="Preview config.yaml and .env together, then apply that exact diff." />{status.isPending ? <StateBlock state="loading" /> : status.isError ? <StateBlock state="error" code={toProblem(status.error).code} /> : <><form className="stack section-gap" onSubmit={(e) => { e.preventDefault(); make.mutate({ action: "configure", baseUrl, apiKey, model }, { onSuccess: setPreview, onError: fail }); }}><Field label="Base URL"><input className="input" value={baseUrl} onChange={(e) => setBaseUrl(e.target.value)} required /></Field><Field label="AIGate API key"><input className="input" type="password" autoComplete="new-password" value={apiKey} onChange={(e) => setApiKey(e.target.value)} minLength={8} maxLength={4096} required /></Field><Field label="Model"><input className="input" value={model} onChange={(e) => setModel(e.target.value)} maxLength={256} required /></Field><Button type="submit" variant="primary" disabled={make.isPending || apply.isPending}>{make.isPending ? "Preparing diff…" : "Preview configuration"}</Button></form>{preview && <Panel title="Review configuration diff" detail={`${preview.configPath} and ${preview.envPath}`} className="section-gap"><pre className="code-block">{preview.diff.map((line) => <div className={line.startsWith("+") ? "text-healthy" : line.startsWith("-") ? "text-danger" : "muted"} key={line}>{line}</div>)}</pre><p className="muted">Existing secrets are redacted. This preview expires at {new Date(preview.expiresAt).toLocaleTimeString()}.</p><div className="row"><Button onClick={() => setPreview(null)}>Cancel</Button><Button variant="primary" disabled={apply.isPending || preview.diff.length === 0} onClick={() => apply.mutate(preview.previewId, { onSuccess: () => { setPreview(null); setApiKey(""); toast({ tone: "success", message: "Hermes settings applied." }); }, onError: fail })}>{apply.isPending ? "Applying…" : "Apply reviewed diff"}</Button></div></Panel>}{status.data!.configured && <div className="section-gap"><Button variant="danger" disabled={make.isPending || apply.isPending} onClick={() => make.mutate({ action: "reset" }, { onSuccess: setPreview, onError: fail })}>Preview reset</Button></div>}</>}</>;
}

export function JcodeToolDetail() {
  const [baseUrl, setBaseUrl] = useState(`${window.location.origin}/v1`), [apiKey, setApiKey] = useState(""), [model, setModel] = useState("gpt-5-codex"), [preview, setPreview] = useState<JcodePreview | null>(null); const status = useJcodeStatus(), make = useJcodePreview(), apply = useApplyJcodePreview(), toast = useToast(), fail = (e: unknown) => toast({ tone: "error", ...toProblem(e) });
  return <><PageHeading eyebrow="Integrations / CLI Tools / JCode" title="JCode" description="Preview the provider TOML and secret env file together, then apply that exact diff." />{status.isPending ? <StateBlock state="loading" /> : status.isError ? <StateBlock state="error" code={toProblem(status.error).code} /> : <><form className="stack section-gap" onSubmit={(e) => { e.preventDefault(); make.mutate({ action: "configure", baseUrl, apiKey, model }, { onSuccess: setPreview, onError: fail }); }}><Field label="Base URL"><input className="input" value={baseUrl} onChange={(e) => setBaseUrl(e.target.value)} required /></Field><Field label="AIGate API key"><input className="input" type="password" autoComplete="new-password" value={apiKey} onChange={(e) => setApiKey(e.target.value)} minLength={8} maxLength={4096} required /></Field><Field label="Default model"><input className="input" value={model} onChange={(e) => setModel(e.target.value)} maxLength={256} required /></Field><Button type="submit" variant="primary" disabled={make.isPending || apply.isPending}>{make.isPending ? "Preparing diff…" : "Preview configuration"}</Button></form>{preview && <Panel title="Review configuration diff" detail={`${preview.configPath} and ${preview.envPath}`} className="section-gap"><pre className="code-block">{preview.diff.map((line) => <div className={line.startsWith("+") ? "text-healthy" : line.startsWith("-") ? "text-danger" : "muted"} key={line}>{line}</div>)}</pre><p className="muted">Existing secrets are redacted. This preview expires at {new Date(preview.expiresAt).toLocaleTimeString()}.</p><div className="row"><Button onClick={() => setPreview(null)}>Cancel</Button><Button variant="primary" disabled={apply.isPending || preview.diff.length === 0} onClick={() => apply.mutate(preview.previewId, { onSuccess: () => { setPreview(null); setApiKey(""); toast({ tone: "success", message: "JCode settings applied." }); }, onError: fail })}>{apply.isPending ? "Applying…" : "Apply reviewed diff"}</Button></div></Panel>}{status.data!.configured && <div className="section-gap"><Button variant="danger" disabled={make.isPending || apply.isPending} onClick={() => make.mutate({ action: "reset" }, { onSuccess: setPreview, onError: fail })}>Preview reset</Button></div>}</>}</>;
}

export function OmpToolDetail() {
  const [baseUrl, setBaseUrl] = useState(`${window.location.origin}/v1`), [apiKey, setApiKey] = useState(""), [preview, setPreview] = useState<OmpPreview | null>(null); const status = useOmpStatus(), make = useOmpPreview(), apply = useApplyOmpPreview(), toast = useToast(), fail = (e: unknown) => toast({ tone: "error", ...toProblem(e) });
  return <><PageHeading eyebrow="Integrations / CLI Tools / Oh My Pi" title="Oh My Pi" description="Preview the 9router provider entry in models.yml, then apply that exact diff." />{status.isPending ? <StateBlock state="loading" /> : status.isError ? <StateBlock state="error" code={toProblem(status.error).code} /> : <><form className="stack section-gap" onSubmit={(e) => { e.preventDefault(); make.mutate({ action: "configure", baseUrl, apiKey }, { onSuccess: setPreview, onError: fail }); }}><Field label="Base URL"><input className="input" value={baseUrl} onChange={(e) => setBaseUrl(e.target.value)} required /></Field><Field label="AIGate API key"><input className="input" type="password" autoComplete="new-password" value={apiKey} onChange={(e) => setApiKey(e.target.value)} minLength={8} maxLength={4096} required /></Field><Button type="submit" variant="primary" disabled={make.isPending || apply.isPending}>{make.isPending ? "Preparing diff…" : "Preview configuration"}</Button></form>{preview && <Panel title="Review configuration diff" detail={preview.configPath} className="section-gap"><pre className="code-block">{preview.diff.map((line) => <div className={line.startsWith("+") ? "text-healthy" : line.startsWith("-") ? "text-danger" : "muted"} key={line}>{line}</div>)}</pre><p className="muted">Existing secrets are redacted. This preview expires at {new Date(preview.expiresAt).toLocaleTimeString()}.</p><div className="row"><Button onClick={() => setPreview(null)}>Cancel</Button><Button variant="primary" disabled={apply.isPending || preview.diff.length === 0} onClick={() => apply.mutate(preview.previewId, { onSuccess: () => { setPreview(null); setApiKey(""); toast({ tone: "success", message: "Oh My Pi settings applied." }); }, onError: fail })}>{apply.isPending ? "Applying…" : "Apply reviewed diff"}</Button></div></Panel>}{status.data!.configured && <div className="section-gap"><Button variant="danger" disabled={make.isPending || apply.isPending} onClick={() => make.mutate({ action: "reset" }, { onSuccess: setPreview, onError: fail })}>Preview reset</Button></div>}</>}</>;
}

export function GrokBuildToolDetail() {
  const [baseUrl, setBaseUrl] = useState(`${window.location.origin}/v1`), [apiKey, setApiKey] = useState(""), [model, setModel] = useState("gpt-5-codex"), [contextWindow, setContextWindow] = useState("128000"), [preview, setPreview] = useState<GrokBuildPreview | null>(null); const status = useGrokBuildStatus(), make = useGrokBuildPreview(), apply = useApplyGrokBuildPreview(), toast = useToast(), fail = (e: unknown) => toast({ tone: "error", ...toProblem(e) });
  return <><PageHeading eyebrow="Integrations / CLI Tools / Grok Build" title="Grok Build" description="Preview the AIGate model slot and default mapping before applying it." />{status.isPending ? <StateBlock state="loading" /> : status.isError ? <StateBlock state="error" code={toProblem(status.error).code} /> : <><form className="stack section-gap" onSubmit={(e) => { e.preventDefault(); make.mutate({ action: "configure", baseUrl, apiKey, model, contextWindow: Number(contextWindow) }, { onSuccess: setPreview, onError: fail }); }}><Field label="Base URL"><input className="input" value={baseUrl} onChange={(e) => setBaseUrl(e.target.value)} required /></Field><Field label="AIGate API key"><input className="input" type="password" autoComplete="new-password" value={apiKey} onChange={(e) => setApiKey(e.target.value)} minLength={8} maxLength={4096} required /></Field><Field label="Model"><input className="input" value={model} onChange={(e) => setModel(e.target.value)} maxLength={256} required /></Field><Field label="Context window"><input className="input" type="number" min="1" max="10000000" value={contextWindow} onChange={(e) => setContextWindow(e.target.value)} required /></Field><Button type="submit" variant="primary" disabled={make.isPending || apply.isPending}>{make.isPending ? "Preparing diff…" : "Preview configuration"}</Button></form>{preview && <Panel title="Review configuration diff" detail={preview.configPath} className="section-gap"><pre className="code-block">{preview.diff.map((line) => <div className={line.startsWith("+") ? "text-healthy" : line.startsWith("-") ? "text-danger" : "muted"} key={line}>{line}</div>)}</pre><p className="muted">Existing secrets are redacted. This preview expires at {new Date(preview.expiresAt).toLocaleTimeString()}.</p><div className="row"><Button onClick={() => setPreview(null)}>Cancel</Button><Button variant="primary" disabled={apply.isPending || preview.diff.length === 0} onClick={() => apply.mutate(preview.previewId, { onSuccess: () => { setPreview(null); setApiKey(""); toast({ tone: "success", message: "Grok Build settings applied." }); }, onError: fail })}>{apply.isPending ? "Applying…" : "Apply reviewed diff"}</Button></div></Panel>}{status.data!.configured && <div className="section-gap"><Button variant="danger" disabled={make.isPending || apply.isPending} onClick={() => make.mutate({ action: "reset" }, { onSuccess: setPreview, onError: fail })}>Preview reset</Button></div>}</>}</>;
}

export function OpenClawToolDetail() {
  const [baseUrl, setBaseUrl] = useState(`${window.location.origin}/v1`), [apiKey, setApiKey] = useState(""), [model, setModel] = useState("gpt-5-codex"), [agentModels, setAgentModels] = useState<Record<string, string>>({}), [preview, setPreview] = useState<OpenClawPreview | null>(null); const status = useOpenClawStatus(), make = useOpenClawPreview(), apply = useApplyOpenClawPreview(), toast = useToast(), fail = (e: unknown) => toast({ tone: "error", ...toProblem(e) });
  return <><PageHeading eyebrow="Integrations / CLI Tools / OpenClaw" title="OpenClaw" description="Preview the main and agent model files, then apply one reviewed change." />{status.isPending ? <StateBlock state="loading" /> : status.isError ? <StateBlock state="error" code={toProblem(status.error).code} /> : <><form className="stack section-gap" onSubmit={(e) => { e.preventDefault(); make.mutate({ action: "configure", baseUrl, apiKey, model, agentModels }, { onSuccess: setPreview, onError: fail }); }}><Field label="Base URL"><input className="input" value={baseUrl} onChange={(e) => setBaseUrl(e.target.value)} required /></Field><Field label="AIGate API key"><input className="input" type="password" autoComplete="new-password" value={apiKey} onChange={(e) => setApiKey(e.target.value)} minLength={8} maxLength={4096} required /></Field><Field label="Default model"><input className="input" value={model} onChange={(e) => setModel(e.target.value)} maxLength={256} required /></Field>{status.data!.agents.map((agent) => <Field key={agent.id} label={`Agent ${agent.id}`} hint={agent.model ? `Current: ${agent.model}. Leave blank to use the default model.` : "Leave blank to use the default model."}><input className="input" value={agentModels[agent.id] ?? ""} onChange={(e) => setAgentModels({ ...agentModels, [agent.id]: e.target.value })} maxLength={256} /></Field>)}<Button type="submit" variant="primary" disabled={make.isPending || apply.isPending}>{make.isPending ? "Preparing diff…" : "Preview configuration"}</Button></form>{preview && <Panel title="Review configuration diff" detail={`${preview.files.length} ${preview.files.length === 1 ? "file" : "files"}`} className="section-gap"><pre className="code-block">{preview.diff.map((line) => <div className={line.startsWith("+") ? "text-healthy" : line.startsWith("-") ? "text-danger" : "muted"} key={line}>{line}</div>)}</pre><p className="muted">Existing secrets are redacted. This preview expires at {new Date(preview.expiresAt).toLocaleTimeString()}.</p><div className="row"><Button onClick={() => setPreview(null)}>Cancel</Button><Button variant="primary" disabled={apply.isPending || preview.diff.length === 0} onClick={() => apply.mutate(preview.previewId, { onSuccess: () => { setPreview(null); setApiKey(""); toast({ tone: "success", message: "OpenClaw settings applied." }); }, onError: fail })}>{apply.isPending ? "Applying…" : "Apply reviewed diff"}</Button></div></Panel>}{status.data!.configured && <div className="section-gap"><Button variant="danger" disabled={make.isPending || apply.isPending} onClick={() => make.mutate({ action: "reset" }, { onSuccess: setPreview, onError: fail })}>Preview reset</Button></div>}</>}</>;
}

export { Skills, Mcp } from "./skills-mcp";
export { CliTools, ClaudeToolDetail, OpenCodeToolDetail, ClineToolDetail, CliToolDetail } from "./cli-core";
