import { useState } from "react";
import { Link } from "@tanstack/react-router";
import { Button, CopyField, Field, PageHeading, Panel, Pill, StateBlock, Warning } from "../../shared/ui";
import { useApplyClaudePreview, useApplyClinePreview, useApplyCodexPreview, useApplyCopilotPreview, useApplyDroidPreview, useApplyGrokBuildPreview, useApplyHermesPreview, useApplyJcodePreview, useApplyKiloPreview, useApplyManagedJsonPreview, useApplyManagedTomlPreview, useApplyOmpPreview, useApplyOpenClawPreview, useApplyOpenCodePreview, useClaudePreview, useClaudeStatus, useClinePreview, useClineStatus, useCliTools, useCodexPreview, useCodexStatus, useCopilotPreview, useCopilotStatus, useDroidPreview, useDroidStatus, useGrokBuildPreview, useGrokBuildStatus, useHermesPreview, useHermesStatus, useJcodePreview, useJcodeStatus, useKiloPreview, useKiloStatus, useManagedJsonPreview, useManagedJsonStatus, useManagedTomlPreview, useManagedTomlStatus, useOmpPreview, useOmpStatus, useOpenClawPreview, useOpenClawStatus, useOpenCodePreview, useOpenCodeStatus, type ClaudePreview, type ClinePreview, type CodexPreview, type CopilotPreview, type DroidPreview, type GrokBuildPreview, type HermesPreview, type JcodePreview, type KiloPreview, type ManagedJsonPreview, type ManagedJsonTool, type ManagedTomlPreview, type ManagedTomlTool, type OmpPreview, type OpenClawPreview, type OpenCodePreview } from "./api";
import { toProblem } from "../../shared/errors";
import { useToast } from "../../shared/toast";

const statusLabel = { configured: "Config found", available: "Installed", not_detected: "Not detected" } as const;
const statusTone = { configured: "healthy", available: "info", not_detected: "muted" } as const;
const configurationRoutes: Record<string, "/integrations/cli-tools/claude" | "/integrations/cli-tools/codex" | "/integrations/cli-tools/opencode" | "/integrations/cli-tools/cline" | "/integrations/cli-tools/droid" | "/integrations/cli-tools/copilot" | "/integrations/cli-tools/crush" | "/integrations/cli-tools/pi" | "/integrations/cli-tools/smelt" | "/integrations/cli-tools/codewhale" | "/integrations/cli-tools/forge" | "/integrations/cli-tools/kilo" | "/integrations/cli-tools/openclaw" | "/integrations/cli-tools/deepseek-tui" | "/integrations/cli-tools/hermes" | "/integrations/cli-tools/jcode" | "/integrations/cli-tools/omp" | "/integrations/cli-tools/grok-build"> = {
  claude: "/integrations/cli-tools/claude", codex: "/integrations/cli-tools/codex", opencode: "/integrations/cli-tools/opencode", cline: "/integrations/cli-tools/cline", droid: "/integrations/cli-tools/droid", copilot: "/integrations/cli-tools/copilot", crush: "/integrations/cli-tools/crush", pi: "/integrations/cli-tools/pi", smelt: "/integrations/cli-tools/smelt", codewhale: "/integrations/cli-tools/codewhale", forge: "/integrations/cli-tools/forge", kilo: "/integrations/cli-tools/kilo", openclaw: "/integrations/cli-tools/openclaw", "deepseek-tui": "/integrations/cli-tools/deepseek-tui", hermes: "/integrations/cli-tools/hermes", jcode: "/integrations/cli-tools/jcode", omp: "/integrations/cli-tools/omp", "grok-build": "/integrations/cli-tools/grok-build",
};

export function CliTools() {
  const query = useCliTools();
  return <><PageHeading eyebrow="Integrations / CLI Tools" title="CLI tools" description="Connect local coding tools to the AIGate endpoint without exposing stored secrets." />
    <Warning>Detection checks this server's PATH and standard configuration locations. Select a supported tool card to review and apply its configuration.</Warning>
    {query.isError ? <div className="state-block error"><strong>Could not detect CLI tools</strong><p>{query.error instanceof Error ? query.error.message : "Request failed"}</p><Button onClick={() => void query.refetch()}>Retry</Button></div>
      : query.isPending ? <StateBlock state="loading" />
      : <div className="grid grid-3 section-gap">{query.data.map((tool) => { const route = configurationRoutes[tool.id]; const card = <article className="tool-card"><div className="row between"><span className="tool-glyph">⌘</span><Pill tone={statusTone[tool.status]}>{statusLabel[tool.status]}</Pill></div><strong>{tool.name}</strong><small>{tool.installed ? "Command found on server PATH" : "Command not found on server PATH"}</small>{tool.configPath && <small className="mono">{tool.configPath}</small>}{route && <small className="tool-link">Review configuration →</small>}</article>; return route ? <Link className="tool-card-link" key={tool.id} to={route}>{card}</Link> : <div key={tool.id}>{card}</div>; })}</div>}
  </>;
}

export function ClaudeToolDetail() {
  const [baseUrl, setBaseUrl] = useState(`${window.location.origin}/v1`);
  const [apiKey, setApiKey] = useState("");
  const [preview, setPreview] = useState<ClaudePreview | null>(null);
  const status = useClaudeStatus();
  const createPreview = useClaudePreview();
  const applyPreview = useApplyClaudePreview();
  const toast = useToast();
  const fail = (error: unknown) => toast({ tone: "error", ...toProblem(error) });
  const apply = () => preview && applyPreview.mutate(preview.previewId, { onSuccess: (result) => { setPreview(null); setApiKey(""); toast({ tone: "success", message: result.action === "reset" ? "Claude Code settings reset." : "Claude Code settings applied." }); }, onError: fail });
  const problem = status.error ? toProblem(status.error) : null;
  return <><PageHeading eyebrow="Integrations / CLI Tools / Claude Code" title="Claude Code" description="Preview a local Claude Code settings change, then apply that exact diff." action={status.data && <Pill tone={status.data.configured ? "healthy" : status.data.installed ? "info" : "muted"}>{status.data.configured ? "AIGate configured" : status.data.installed ? "Available" : "Not detected"}</Pill>} />
    {status.isPending ? <StateBlock state="loading" /> : problem ? <StateBlock state="error" code={problem.code} action={<Button onClick={() => void status.refetch()}>Retry</Button>} /> : <><div className="split section-gap"><Panel title="AIGate connection"><form className="stack" onSubmit={(event) => { event.preventDefault(); createPreview.mutate({ action: "configure", baseUrl, apiKey }, { onSuccess: setPreview, onError: fail }); }}><Field label="Base URL"><input className="input" value={baseUrl} onChange={(event) => setBaseUrl(event.target.value)} required /></Field><Field label="AIGate API key" hint="Saved as ANTHROPIC_AUTH_TOKEN in Claude Code settings. The dashboard never reads it back."><input className="input" type="password" autoComplete="new-password" value={apiKey} onChange={(event) => setApiKey(event.target.value)} minLength={8} maxLength={4096} required /></Field><Button type="submit" variant="primary" disabled={createPreview.isPending || applyPreview.isPending}>{createPreview.isPending ? "Preparing diffâ€¦" : "Preview configuration"}</Button></form></Panel><Panel title="Local file"><div className="stack"><CopyField label="Path" value={status.data!.configPath} /><Warning>Applying stores the key in this local file. The server takes an `.aigate.bak` backup before its atomic replacement.</Warning><Pill tone={status.data!.configured ? "healthy" : "muted"}>{status.data!.baseUrl ?? "No AIGate endpoint is configured"}</Pill></div></Panel></div>
      {status.data!.configured && <div className="section-gap"><Button variant="danger" disabled={createPreview.isPending || applyPreview.isPending} onClick={() => createPreview.mutate({ action: "reset" }, { onSuccess: setPreview, onError: fail })}>Preview reset</Button></div>}
      {preview && <Panel title={preview.action === "reset" ? "Review reset diff" : "Review configuration diff"} detail={`Target ${preview.configPath}`} className="section-gap"><div className="stack"><pre className="code-block">{preview.diff.map((line) => <div className={line.startsWith("+") ? "text-healthy" : line.startsWith("-") ? "text-danger" : "muted"} key={line}>{line}</div>)}{preview.diff.length === 0 && "No file changes."}</pre><p className="muted">Existing secrets are redacted. This preview expires at {new Date(preview.expiresAt).toLocaleTimeString()}.</p><div className="row"><Button onClick={() => setPreview(null)}>Cancel</Button><Button variant="primary" disabled={applyPreview.isPending || preview.diff.length === 0} onClick={apply}>{applyPreview.isPending ? "Applyingâ€¦" : "Apply reviewed diff"}</Button></div></div></Panel>}
    </>}
  </>;
}

export function OpenCodeToolDetail() {
  const [baseUrl, setBaseUrl] = useState(`${window.location.origin}/v1`);
  const [apiKey, setApiKey] = useState("");
  const [model, setModel] = useState("gpt-5-codex");
  const [preview, setPreview] = useState<OpenCodePreview | null>(null);
  const status = useOpenCodeStatus(); const createPreview = useOpenCodePreview(); const applyPreview = useApplyOpenCodePreview(); const toast = useToast();
  const fail = (error: unknown) => toast({ tone: "error", ...toProblem(error) });
  const apply = () => preview && applyPreview.mutate(preview.previewId, { onSuccess: (result) => { setPreview(null); setApiKey(""); toast({ tone: "success", message: result.action === "reset" ? "OpenCode settings reset." : "OpenCode settings applied." }); }, onError: fail });
  const problem = status.error ? toProblem(status.error) : null;
  return <><PageHeading eyebrow="Integrations / CLI Tools / OpenCode" title="OpenCode" description="Preview a local OpenCode provider change, then apply that exact diff." action={status.data && <Pill tone={status.data.configured ? "healthy" : status.data.installed ? "info" : "muted"}>{status.data.configured ? "AIGate configured" : status.data.installed ? "Available" : "Not detected"}</Pill>} />
    {status.isPending ? <StateBlock state="loading" /> : problem ? <StateBlock state="error" code={problem.code} action={<Button onClick={() => void status.refetch()}>Retry</Button>} /> : <><div className="split section-gap"><Panel title="AIGate connection"><form className="stack" onSubmit={(event) => { event.preventDefault(); createPreview.mutate({ action: "configure", baseUrl, apiKey, model }, { onSuccess: setPreview, onError: fail }); }}><Field label="Base URL"><input className="input" value={baseUrl} onChange={(event) => setBaseUrl(event.target.value)} required /></Field><Field label="AIGate API key" hint="Saved in OpenCode's 9router provider options. The dashboard never reads it back."><input className="input" type="password" autoComplete="new-password" value={apiKey} onChange={(event) => setApiKey(event.target.value)} minLength={8} maxLength={4096} required /></Field><Field label="Model"><input className="input" value={model} onChange={(event) => setModel(event.target.value)} maxLength={256} required /></Field><Button type="submit" variant="primary" disabled={createPreview.isPending || applyPreview.isPending}>{createPreview.isPending ? "Preparing diffâ€¦" : "Preview configuration"}</Button></form></Panel><Panel title="Local file"><div className="stack"><CopyField label="Path" value={status.data!.configPath} /><Warning>Applying stores the key in this local file. The server takes an `.aigate.bak` backup before its atomic replacement.</Warning><Pill tone={status.data!.configured ? "healthy" : "muted"}>{status.data!.model ? `Current model: ${status.data!.model}` : "No AIGate model is configured"}</Pill></div></Panel></div>
      {status.data!.configured && <div className="section-gap"><Button variant="danger" disabled={createPreview.isPending || applyPreview.isPending} onClick={() => createPreview.mutate({ action: "reset" }, { onSuccess: setPreview, onError: fail })}>Preview reset</Button></div>}
      {preview && <Panel title={preview.action === "reset" ? "Review reset diff" : "Review configuration diff"} detail={`Target ${preview.configPath}`} className="section-gap"><div className="stack"><pre className="code-block">{preview.diff.map((line) => <div className={line.startsWith("+") ? "text-healthy" : line.startsWith("-") ? "text-danger" : "muted"} key={line}>{line}</div>)}{preview.diff.length === 0 && "No file changes."}</pre><p className="muted">Existing secrets are redacted. This preview expires at {new Date(preview.expiresAt).toLocaleTimeString()}.</p><div className="row"><Button onClick={() => setPreview(null)}>Cancel</Button><Button variant="primary" disabled={applyPreview.isPending || preview.diff.length === 0} onClick={apply}>{applyPreview.isPending ? "Applyingâ€¦" : "Apply reviewed diff"}</Button></div></div></Panel>}
    </>}
  </>;
}

export function ClineToolDetail() {
  const [baseUrl, setBaseUrl] = useState(`${window.location.origin}/v1`); const [apiKey, setApiKey] = useState(""); const [model, setModel] = useState("gpt-5-codex"); const [preview, setPreview] = useState<ClinePreview | null>(null);
  const status = useClineStatus(); const createPreview = useClinePreview(); const applyPreview = useApplyClinePreview(); const toast = useToast(); const fail = (error: unknown) => toast({ tone: "error", ...toProblem(error) });
  const apply = () => preview && applyPreview.mutate(preview.previewId, { onSuccess: (result) => { setPreview(null); setApiKey(""); toast({ tone: "success", message: result.action === "reset" ? "Cline settings reset." : "Cline settings applied." }); }, onError: fail }); const problem = status.error ? toProblem(status.error) : null;
  return <><PageHeading eyebrow="Integrations / CLI Tools / Cline" title="Cline" description="Preview both Cline settings files, then apply that exact diff." action={status.data && <Pill tone={status.data.configured ? "healthy" : status.data.installed ? "info" : "muted"}>{status.data.configured ? "AIGate configured" : status.data.installed ? "Available" : "Not detected"}</Pill>} />
    {status.isPending ? <StateBlock state="loading" /> : problem ? <StateBlock state="error" code={problem.code} action={<Button onClick={() => void status.refetch()}>Retry</Button>} /> : <><div className="split section-gap"><Panel title="AIGate connection"><form className="stack" onSubmit={(event) => { event.preventDefault(); createPreview.mutate({ action: "configure", baseUrl, apiKey, model }, { onSuccess: setPreview, onError: fail }); }}><Field label="Base URL"><input className="input" value={baseUrl} onChange={(event) => setBaseUrl(event.target.value)} required /></Field><Field label="AIGate API key" hint="Saved in Cline's separate secrets file. The dashboard never reads it back."><input className="input" type="password" autoComplete="new-password" value={apiKey} onChange={(event) => setApiKey(event.target.value)} minLength={8} maxLength={4096} required /></Field><Field label="Model"><input className="input" value={model} onChange={(event) => setModel(event.target.value)} maxLength={256} required /></Field><Button type="submit" variant="primary" disabled={createPreview.isPending || applyPreview.isPending}>{createPreview.isPending ? "Preparing diffâ€¦" : "Preview configuration"}</Button></form></Panel><Panel title="Local files"><div className="stack"><CopyField label="State" value={status.data!.statePath} /><CopyField label="Secret" value={status.data!.secretsPath} /><Warning>Both files are previewed and backed up before apply. If the secret write fails, AIGate restores the state file.</Warning></div></Panel></div>
      {status.data!.configured && <div className="section-gap"><Button variant="danger" disabled={createPreview.isPending || applyPreview.isPending} onClick={() => createPreview.mutate({ action: "reset" }, { onSuccess: setPreview, onError: fail })}>Preview reset</Button></div>}
      {preview && <Panel title={preview.action === "reset" ? "Review reset diff" : "Review configuration diff"} detail={`${preview.statePath} and ${preview.secretsPath}`} className="section-gap"><div className="stack"><pre className="code-block">{preview.diff.map((line) => <div className={line.startsWith("+") ? "text-healthy" : line.startsWith("-") ? "text-danger" : "muted"} key={line}>{line}</div>)}</pre><p className="muted">Existing secrets are redacted. This preview expires at {new Date(preview.expiresAt).toLocaleTimeString()}.</p><div className="row"><Button onClick={() => setPreview(null)}>Cancel</Button><Button variant="primary" disabled={applyPreview.isPending || preview.diff.length === 0} onClick={apply}>{applyPreview.isPending ? "Applyingâ€¦" : "Apply reviewed diff"}</Button></div></div></Panel>}
    </>}
  </>;
}

export function DroidToolDetail() {
  const [baseUrl, setBaseUrl] = useState(`${window.location.origin}/v1`), [apiKey, setApiKey] = useState(""), [model, setModel] = useState("gpt-5-codex"), [preview, setPreview] = useState<DroidPreview | null>(null); const status = useDroidStatus(), make = useDroidPreview(), apply = useApplyDroidPreview(), toast = useToast(), fail = (e: unknown) => toast({ tone: "error", ...toProblem(e) });
  return <><PageHeading eyebrow="Integrations / CLI Tools / Droid" title="Droid" description="Preview a local Droid model change, then apply that exact diff." />{status.isPending ? <StateBlock state="loading" /> : status.isError ? <StateBlock state="error" code={toProblem(status.error).code} /> : <><form className="stack section-gap" onSubmit={(e) => { e.preventDefault(); make.mutate({ action: "configure", baseUrl, apiKey, model }, { onSuccess: setPreview, onError: fail }); }}><Field label="Base URL"><input className="input" value={baseUrl} onChange={(e) => setBaseUrl(e.target.value)} required /></Field><Field label="API key"><input className="input" type="password" value={apiKey} onChange={(e) => setApiKey(e.target.value)} minLength={8} required /></Field><Field label="Model"><input className="input" value={model} onChange={(e) => setModel(e.target.value)} required /></Field><Button type="submit" variant="primary">Preview configuration</Button></form>{preview && <Panel title="Review configuration diff"><pre className="code-block">{preview.diff.map((line) => <div key={line}>{line}</div>)}</pre><Button variant="primary" onClick={() => apply.mutate(preview.previewId, { onSuccess: () => { setPreview(null); setApiKey(""); toast({ tone: "success", message: "Droid settings applied." }); }, onError: fail })}>Apply reviewed diff</Button></Panel>}{status.data!.configured && <Button variant="danger" onClick={() => make.mutate({ action: "reset" }, { onSuccess: setPreview, onError: fail })}>Preview reset</Button>}</>}</>;
}

export function CopilotToolDetail() {
  const [baseUrl, setBaseUrl] = useState(`${window.location.origin}/v1`), [apiKey, setApiKey] = useState(""), [model, setModel] = useState("gpt-5-codex"), [preview, setPreview] = useState<CopilotPreview | null>(null); const status = useCopilotStatus(), make = useCopilotPreview(), apply = useApplyCopilotPreview(), toast = useToast(), fail = (e: unknown) => toast({ tone: "error", ...toProblem(e) });
  return <><PageHeading eyebrow="Integrations / CLI Tools / Copilot" title="GitHub Copilot" description="Preview a local VS Code language-model change, then apply that exact diff." />{status.isPending ? <StateBlock state="loading" /> : status.isError ? <StateBlock state="error" code={toProblem(status.error).code} /> : <><form className="stack section-gap" onSubmit={(e) => { e.preventDefault(); make.mutate({ action: "configure", baseUrl, apiKey, model }, { onSuccess: setPreview, onError: fail }); }}><Field label="Base URL"><input className="input" value={baseUrl} onChange={(e) => setBaseUrl(e.target.value)} required /></Field><Field label="AIGate API key"><input className="input" type="password" autoComplete="new-password" value={apiKey} onChange={(e) => setApiKey(e.target.value)} minLength={8} maxLength={4096} required /></Field><Field label="Model"><input className="input" value={model} onChange={(e) => setModel(e.target.value)} maxLength={256} required /></Field><Button type="submit" variant="primary" disabled={make.isPending || apply.isPending}>{make.isPending ? "Preparing diff…" : "Preview configuration"}</Button></form>{preview && <Panel title="Review configuration diff" detail={preview.configPath} className="section-gap"><pre className="code-block">{preview.diff.map((line) => <div className={line.startsWith("+") ? "text-healthy" : line.startsWith("-") ? "text-danger" : "muted"} key={line}>{line}</div>)}</pre><p className="muted">Existing secrets are redacted. This preview expires at {new Date(preview.expiresAt).toLocaleTimeString()}.</p><div className="row"><Button onClick={() => setPreview(null)}>Cancel</Button><Button variant="primary" disabled={apply.isPending || preview.diff.length === 0} onClick={() => apply.mutate(preview.previewId, { onSuccess: () => { setPreview(null); setApiKey(""); toast({ tone: "success", message: "Copilot settings applied. Reload VS Code to use it." }); }, onError: fail })}>{apply.isPending ? "Applying…" : "Apply reviewed diff"}</Button></div></Panel>}{status.data!.configured && <div className="section-gap"><Button variant="danger" disabled={make.isPending || apply.isPending} onClick={() => make.mutate({ action: "reset" }, { onSuccess: setPreview, onError: fail })}>Preview reset</Button></div>}</>}</>;
}

export function ManagedJsonToolDetail({ tool, title }: { tool: ManagedJsonTool; title: string }) {
  const [baseUrl, setBaseUrl] = useState(`${window.location.origin}/v1`), [apiKey, setApiKey] = useState(""), [model, setModel] = useState("gpt-5-codex"), [preview, setPreview] = useState<ManagedJsonPreview | null>(null); const status = useManagedJsonStatus(tool), make = useManagedJsonPreview(tool), apply = useApplyManagedJsonPreview(tool), toast = useToast(), fail = (e: unknown) => toast({ tone: "error", ...toProblem(e) });
  return <><PageHeading eyebrow={`Integrations / CLI Tools / ${title}`} title={title} description={`Preview a local ${title} configuration change, then apply that exact diff.`} />{status.isPending ? <StateBlock state="loading" /> : status.isError ? <StateBlock state="error" code={toProblem(status.error).code} /> : <><form className="stack section-gap" onSubmit={(e) => { e.preventDefault(); make.mutate({ action: "configure", baseUrl, apiKey, model }, { onSuccess: setPreview, onError: fail }); }}><Field label="Base URL"><input className="input" value={baseUrl} onChange={(e) => setBaseUrl(e.target.value)} required /></Field><Field label="AIGate API key"><input className="input" type="password" autoComplete="new-password" value={apiKey} onChange={(e) => setApiKey(e.target.value)} minLength={8} maxLength={4096} required /></Field><Field label="Model"><input className="input" value={model} onChange={(e) => setModel(e.target.value)} maxLength={256} required /></Field><Button type="submit" variant="primary" disabled={make.isPending || apply.isPending}>{make.isPending ? "Preparing diff…" : "Preview configuration"}</Button></form>{preview && <Panel title="Review configuration diff" detail={preview.configPath} className="section-gap"><pre className="code-block">{preview.diff.map((line) => <div className={line.startsWith("+") ? "text-healthy" : line.startsWith("-") ? "text-danger" : "muted"} key={line}>{line}</div>)}</pre><p className="muted">Existing secrets are redacted. This preview expires at {new Date(preview.expiresAt).toLocaleTimeString()}.</p><div className="row"><Button onClick={() => setPreview(null)}>Cancel</Button><Button variant="primary" disabled={apply.isPending || preview.diff.length === 0} onClick={() => apply.mutate(preview.previewId, { onSuccess: () => { setPreview(null); setApiKey(""); toast({ tone: "success", message: `${title} settings applied.` }); }, onError: fail })}>{apply.isPending ? "Applying…" : "Apply reviewed diff"}</Button></div></Panel>}{status.data!.configured && <div className="section-gap"><Button variant="danger" disabled={make.isPending || apply.isPending} onClick={() => make.mutate({ action: "reset" }, { onSuccess: setPreview, onError: fail })}>Preview reset</Button></div>}</>}</>;
}

export function ManagedTomlToolDetail({ tool, title }: { tool: ManagedTomlTool; title: string }) {
  const [baseUrl, setBaseUrl] = useState(`${window.location.origin}/v1`), [apiKey, setApiKey] = useState(""), [model, setModel] = useState("gpt-5-codex"), [preview, setPreview] = useState<ManagedTomlPreview | null>(null); const status = useManagedTomlStatus(tool), make = useManagedTomlPreview(tool), apply = useApplyManagedTomlPreview(tool), toast = useToast(), fail = (e: unknown) => toast({ tone: "error", ...toProblem(e) });
  return <><PageHeading eyebrow={`Integrations / CLI Tools / ${title}`} title={title} description={`Preview a local ${title} configuration change, then apply that exact diff.`} />{status.isPending ? <StateBlock state="loading" /> : status.isError ? <StateBlock state="error" code={toProblem(status.error).code} /> : <><form className="stack section-gap" onSubmit={(e) => { e.preventDefault(); make.mutate({ action: "configure", baseUrl, apiKey, model }, { onSuccess: setPreview, onError: fail }); }}><Field label="Base URL"><input className="input" value={baseUrl} onChange={(e) => setBaseUrl(e.target.value)} required /></Field><Field label="AIGate API key"><input className="input" type="password" autoComplete="new-password" value={apiKey} onChange={(e) => setApiKey(e.target.value)} minLength={8} maxLength={4096} required /></Field><Field label="Model"><input className="input" value={model} onChange={(e) => setModel(e.target.value)} maxLength={256} required /></Field><Button type="submit" variant="primary" disabled={make.isPending || apply.isPending}>{make.isPending ? "Preparing diff…" : "Preview configuration"}</Button></form>{preview && <Panel title="Review configuration diff" detail={preview.configPath} className="section-gap"><pre className="code-block">{preview.diff.map((line) => <div className={line.startsWith("+") ? "text-healthy" : line.startsWith("-") ? "text-danger" : "muted"} key={line}>{line}</div>)}</pre><p className="muted">Existing secrets are redacted. This preview expires at {new Date(preview.expiresAt).toLocaleTimeString()}.</p><div className="row"><Button onClick={() => setPreview(null)}>Cancel</Button><Button variant="primary" disabled={apply.isPending || preview.diff.length === 0} onClick={() => apply.mutate(preview.previewId, { onSuccess: () => { setPreview(null); setApiKey(""); toast({ tone: "success", message: `${title} settings applied.` }); }, onError: fail })}>{apply.isPending ? "Applying…" : "Apply reviewed diff"}</Button></div></Panel>}{status.data!.configured && <div className="section-gap"><Button variant="danger" disabled={make.isPending || apply.isPending} onClick={() => make.mutate({ action: "reset" }, { onSuccess: setPreview, onError: fail })}>Preview reset</Button></div>}</>}</>;
}

export function KiloToolDetail() {
  const [baseUrl, setBaseUrl] = useState(`${window.location.origin}/v1`), [apiKey, setApiKey] = useState(""), [model, setModel] = useState("gpt-5-codex"), [preview, setPreview] = useState<KiloPreview | null>(null); const status = useKiloStatus(), make = useKiloPreview(), apply = useApplyKiloPreview(), toast = useToast(), fail = (e: unknown) => toast({ tone: "error", ...toProblem(e) });
  return <><PageHeading eyebrow="Integrations / CLI Tools / Kilo" title="Kilo Code" description="Preview Kilo and VS Code settings, then apply that exact diff." />{status.isPending ? <StateBlock state="loading" /> : status.isError ? <StateBlock state="error" code={toProblem(status.error).code} /> : <><form className="stack section-gap" onSubmit={(e) => { e.preventDefault(); make.mutate({ action: "configure", baseUrl, apiKey, model }, { onSuccess: setPreview, onError: fail }); }}><Field label="Base URL"><input className="input" value={baseUrl} onChange={(e) => setBaseUrl(e.target.value)} required /></Field><Field label="AIGate API key"><input className="input" type="password" autoComplete="new-password" value={apiKey} onChange={(e) => setApiKey(e.target.value)} minLength={8} maxLength={4096} required /></Field><Field label="Model"><input className="input" value={model} onChange={(e) => setModel(e.target.value)} maxLength={256} required /></Field><Button type="submit" variant="primary" disabled={make.isPending || apply.isPending}>{make.isPending ? "Preparing diff…" : "Preview configuration"}</Button></form>{preview && <Panel title="Review configuration diff" detail={`${preview.authPath} and ${preview.vscodePath}`} className="section-gap"><pre className="code-block">{preview.diff.map((line) => <div className={line.startsWith("+") ? "text-healthy" : line.startsWith("-") ? "text-danger" : "muted"} key={line}>{line}</div>)}</pre><p className="muted">Existing secrets are redacted. This preview expires at {new Date(preview.expiresAt).toLocaleTimeString()}.</p><div className="row"><Button onClick={() => setPreview(null)}>Cancel</Button><Button variant="primary" disabled={apply.isPending || preview.diff.length === 0} onClick={() => apply.mutate(preview.previewId, { onSuccess: () => { setPreview(null); setApiKey(""); toast({ tone: "success", message: "Kilo settings applied." }); }, onError: fail })}>{apply.isPending ? "Applying…" : "Apply reviewed diff"}</Button></div></Panel>}{status.data!.configured && <div className="section-gap"><Button variant="danger" disabled={make.isPending || apply.isPending} onClick={() => make.mutate({ action: "reset" }, { onSuccess: setPreview, onError: fail })}>Preview reset</Button></div>}</>}</>;
}

export function HermesToolDetail() {
  const [baseUrl, setBaseUrl] = useState(`${window.location.origin}/v1`), [apiKey, setApiKey] = useState(""), [model, setModel] = useState("gpt-5-codex"), [preview, setPreview] = useState<HermesPreview | null>(null); const status = useHermesStatus(), make = useHermesPreview(), apply = useApplyHermesPreview(), toast = useToast(), fail = (e: unknown) => toast({ tone: "error", ...toProblem(e) });
  return <><PageHeading eyebrow="Integrations / CLI Tools / Hermes" title="Hermes Agent" description="Preview config.yaml and .env together, then apply that exact diff." />{status.isPending ? <StateBlock state="loading" /> : status.isError ? <StateBlock state="error" code={toProblem(status.error).code} /> : <><form className="stack section-gap" onSubmit={(e) => { e.preventDefault(); make.mutate({ action: "configure", baseUrl, apiKey, model }, { onSuccess: setPreview, onError: fail }); }}><Field label="Base URL"><input className="input" value={baseUrl} onChange={(e) => setBaseUrl(e.target.value)} required /></Field><Field label="AIGate API key"><input className="input" type="password" autoComplete="new-password" value={apiKey} onChange={(e) => setApiKey(e.target.value)} minLength={8} maxLength={4096} required /></Field><Field label="Model"><input className="input" value={model} onChange={(e) => setModel(e.target.value)} maxLength={256} required /></Field><Button type="submit" variant="primary" disabled={make.isPending || apply.isPending}>{make.isPending ? "Preparing diff…" : "Preview configuration"}</Button></form>{preview && <Panel title="Review configuration diff" detail={`${preview.configPath} and ${preview.envPath}`} className="section-gap"><pre className="code-block">{preview.diff.map((line) => <div className={line.startsWith("+") ? "text-healthy" : line.startsWith("-") ? "text-danger" : "muted"} key={line}>{line}</div>)}</pre><p className="muted">Existing secrets are redacted. This preview expires at {new Date(preview.expiresAt).toLocaleTimeString()}.</p><div className="row"><Button onClick={() => setPreview(null)}>Cancel</Button><Button variant="primary" disabled={apply.isPending || preview.diff.length === 0} onClick={() => apply.mutate(preview.previewId, { onSuccess: () => { setPreview(null); setApiKey(""); toast({ tone: "success", message: "Hermes settings applied." }); }, onError: fail })}>{apply.isPending ? "Applying…" : "Apply reviewed diff"}</Button></div></Panel>}{status.data!.configured && <div className="section-gap"><Button variant="danger" disabled={make.isPending || apply.isPending} onClick={() => make.mutate({ action: "reset" }, { onSuccess: setPreview, onError: fail })}>Preview reset</Button></div>}</>}</>;
}

export function JcodeToolDetail() {
  const [baseUrl, setBaseUrl] = useState(`${window.location.origin}/v1`), [apiKey, setApiKey] = useState(""), [model, setModel] = useState("gpt-5-codex"), [preview, setPreview] = useState<JcodePreview | null>(null); const status = useJcodeStatus(), make = useJcodePreview(), apply = useApplyJcodePreview(), toast = useToast(), fail = (e: unknown) => toast({ tone: "error", ...toProblem(e) });
  return <><PageHeading eyebrow="Integrations / CLI Tools / JCode" title="JCode" description="Preview the provider TOML and secret env file together, then apply that exact diff." />{status.isPending ? <StateBlock state="loading" /> : status.isError ? <StateBlock state="error" code={toProblem(status.error).code} /> : <><form className="stack section-gap" onSubmit={(e) => { e.preventDefault(); make.mutate({ action: "configure", baseUrl, apiKey, model }, { onSuccess: setPreview, onError: fail }); }}><Field label="Base URL"><input className="input" value={baseUrl} onChange={(e) => setBaseUrl(e.target.value)} required /></Field><Field label="AIGate API key"><input className="input" type="password" autoComplete="new-password" value={apiKey} onChange={(e) => setApiKey(e.target.value)} minLength={8} maxLength={4096} required /></Field><Field label="Default model"><input className="input" value={model} onChange={(e) => setModel(e.target.value)} maxLength={256} required /></Field><Button type="submit" variant="primary" disabled={make.isPending || apply.isPending}>{make.isPending ? "Preparing diff…" : "Preview configuration"}</Button></form>{preview && <Panel title="Review configuration diff" detail={`${preview.configPath} and ${preview.envPath}`} className="section-gap"><pre className="code-block">{preview.diff.map((line) => <div className={line.startsWith("+") ? "text-healthy" : line.startsWith("-") ? "text-danger" : "muted"} key={line}>{line}</div>)}</pre><p className="muted">Existing secrets are redacted. This preview expires at {new Date(preview.expiresAt).toLocaleTimeString()}.</p><div className="row"><Button onClick={() => setPreview(null)}>Cancel</Button><Button variant="primary" disabled={apply.isPending || preview.diff.length === 0} onClick={() => apply.mutate(preview.previewId, { onSuccess: () => { setPreview(null); setApiKey(""); toast({ tone: "success", message: "JCode settings applied." }); }, onError: fail })}>{apply.isPending ? "Applying…" : "Apply reviewed diff"}</Button></div></Panel>}{status.data!.configured && <div className="section-gap"><Button variant="danger" disabled={make.isPending || apply.isPending} onClick={() => make.mutate({ action: "reset" }, { onSuccess: setPreview, onError: fail })}>Preview reset</Button></div>}</>}</>;
}

export function OmpToolDetail() {
  const [baseUrl, setBaseUrl] = useState(`${window.location.origin}/v1`), [apiKey, setApiKey] = useState(""), [preview, setPreview] = useState<OmpPreview | null>(null); const status = useOmpStatus(), make = useOmpPreview(), apply = useApplyOmpPreview(), toast = useToast(), fail = (e: unknown) => toast({ tone: "error", ...toProblem(e) });
  return <><PageHeading eyebrow="Integrations / CLI Tools / Oh My Pi" title="Oh My Pi" description="Preview the 9router provider entry in models.yml, then apply that exact diff." />{status.isPending ? <StateBlock state="loading" /> : status.isError ? <StateBlock state="error" code={toProblem(status.error).code} /> : <><form className="stack section-gap" onSubmit={(e) => { e.preventDefault(); make.mutate({ action: "configure", baseUrl, apiKey }, { onSuccess: setPreview, onError: fail }); }}><Field label="Base URL"><input className="input" value={baseUrl} onChange={(e) => setBaseUrl(e.target.value)} required /></Field><Field label="AIGate API key"><input className="input" type="password" autoComplete="new-password" value={apiKey} onChange={(e) => setApiKey(e.target.value)} minLength={8} maxLength={4096} required /></Field><Button type="submit" variant="primary" disabled={make.isPending || apply.isPending}>{make.isPending ? "Preparing diff…" : "Preview configuration"}</Button></form>{preview && <Panel title="Review configuration diff" detail={preview.configPath} className="section-gap"><pre className="code-block">{preview.diff.map((line) => <div className={line.startsWith("+") ? "text-healthy" : line.startsWith("-") ? "text-danger" : "muted"} key={line}>{line}</div>)}</pre><p className="muted">Existing secrets are redacted. This preview expires at {new Date(preview.expiresAt).toLocaleTimeString()}.</p><div className="row"><Button onClick={() => setPreview(null)}>Cancel</Button><Button variant="primary" disabled={apply.isPending || preview.diff.length === 0} onClick={() => apply.mutate(preview.previewId, { onSuccess: () => { setPreview(null); setApiKey(""); toast({ tone: "success", message: "Oh My Pi settings applied." }); }, onError: fail })}>{apply.isPending ? "Applying…" : "Apply reviewed diff"}</Button></div></Panel>}{status.data!.configured && <div className="section-gap"><Button variant="danger" disabled={make.isPending || apply.isPending} onClick={() => make.mutate({ action: "reset" }, { onSuccess: setPreview, onError: fail })}>Preview reset</Button></div>}</>}</>;
}

export function GrokBuildToolDetail() {
  const [baseUrl, setBaseUrl] = useState(`${window.location.origin}/v1`), [apiKey, setApiKey] = useState(""), [model, setModel] = useState("gpt-5-codex"), [contextWindow, setContextWindow] = useState("128000"), [preview, setPreview] = useState<GrokBuildPreview | null>(null); const status = useGrokBuildStatus(), make = useGrokBuildPreview(), apply = useApplyGrokBuildPreview(), toast = useToast(), fail = (e: unknown) => toast({ tone: "error", ...toProblem(e) });
  return <><PageHeading eyebrow="Integrations / CLI Tools / Grok Build" title="Grok Build" description="Preview the AIGate model slot and default mapping before applying it." />{status.isPending ? <StateBlock state="loading" /> : status.isError ? <StateBlock state="error" code={toProblem(status.error).code} /> : <><form className="stack section-gap" onSubmit={(e) => { e.preventDefault(); make.mutate({ action: "configure", baseUrl, apiKey, model, contextWindow: Number(contextWindow) }, { onSuccess: setPreview, onError: fail }); }}><Field label="Base URL"><input className="input" value={baseUrl} onChange={(e) => setBaseUrl(e.target.value)} required /></Field><Field label="AIGate API key"><input className="input" type="password" autoComplete="new-password" value={apiKey} onChange={(e) => setApiKey(e.target.value)} minLength={8} maxLength={4096} required /></Field><Field label="Model"><input className="input" value={model} onChange={(e) => setModel(e.target.value)} maxLength={256} required /></Field><Field label="Context window"><input className="input" type="number" min="1" max="10000000" value={contextWindow} onChange={(e) => setContextWindow(e.target.value)} required /></Field><Button type="submit" variant="primary" disabled={make.isPending || apply.isPending}>{make.isPending ? "Preparing diff…" : "Preview configuration"}</Button></form>{preview && <Panel title="Review configuration diff" detail={preview.configPath} className="section-gap"><pre className="code-block">{preview.diff.map((line) => <div className={line.startsWith("+") ? "text-healthy" : line.startsWith("-") ? "text-danger" : "muted"} key={line}>{line}</div>)}</pre><p className="muted">Existing secrets are redacted. This preview expires at {new Date(preview.expiresAt).toLocaleTimeString()}.</p><div className="row"><Button onClick={() => setPreview(null)}>Cancel</Button><Button variant="primary" disabled={apply.isPending || preview.diff.length === 0} onClick={() => apply.mutate(preview.previewId, { onSuccess: () => { setPreview(null); setApiKey(""); toast({ tone: "success", message: "Grok Build settings applied." }); }, onError: fail })}>{apply.isPending ? "Applying…" : "Apply reviewed diff"}</Button></div></Panel>}{status.data!.configured && <div className="section-gap"><Button variant="danger" disabled={make.isPending || apply.isPending} onClick={() => make.mutate({ action: "reset" }, { onSuccess: setPreview, onError: fail })}>Preview reset</Button></div>}</>}</>;
}

export function OpenClawToolDetail() {
  const [baseUrl, setBaseUrl] = useState(`${window.location.origin}/v1`), [apiKey, setApiKey] = useState(""), [model, setModel] = useState("gpt-5-codex"), [agentModels, setAgentModels] = useState<Record<string, string>>({}), [preview, setPreview] = useState<OpenClawPreview | null>(null); const status = useOpenClawStatus(), make = useOpenClawPreview(), apply = useApplyOpenClawPreview(), toast = useToast(), fail = (e: unknown) => toast({ tone: "error", ...toProblem(e) });
  return <><PageHeading eyebrow="Integrations / CLI Tools / OpenClaw" title="OpenClaw" description="Preview the main and agent model files, then apply one reviewed change." />{status.isPending ? <StateBlock state="loading" /> : status.isError ? <StateBlock state="error" code={toProblem(status.error).code} /> : <><form className="stack section-gap" onSubmit={(e) => { e.preventDefault(); make.mutate({ action: "configure", baseUrl, apiKey, model, agentModels }, { onSuccess: setPreview, onError: fail }); }}><Field label="Base URL"><input className="input" value={baseUrl} onChange={(e) => setBaseUrl(e.target.value)} required /></Field><Field label="AIGate API key"><input className="input" type="password" autoComplete="new-password" value={apiKey} onChange={(e) => setApiKey(e.target.value)} minLength={8} maxLength={4096} required /></Field><Field label="Default model"><input className="input" value={model} onChange={(e) => setModel(e.target.value)} maxLength={256} required /></Field>{status.data!.agents.map((agent) => <Field key={agent.id} label={`Agent ${agent.id}`} hint={agent.model ? `Current: ${agent.model}. Leave blank to use the default model.` : "Leave blank to use the default model."}><input className="input" value={agentModels[agent.id] ?? ""} onChange={(e) => setAgentModels({ ...agentModels, [agent.id]: e.target.value })} maxLength={256} /></Field>)}<Button type="submit" variant="primary" disabled={make.isPending || apply.isPending}>{make.isPending ? "Preparing diff…" : "Preview configuration"}</Button></form>{preview && <Panel title="Review configuration diff" detail={`${preview.files.length} ${preview.files.length === 1 ? "file" : "files"}`} className="section-gap"><pre className="code-block">{preview.diff.map((line) => <div className={line.startsWith("+") ? "text-healthy" : line.startsWith("-") ? "text-danger" : "muted"} key={line}>{line}</div>)}</pre><p className="muted">Existing secrets are redacted. This preview expires at {new Date(preview.expiresAt).toLocaleTimeString()}.</p><div className="row"><Button onClick={() => setPreview(null)}>Cancel</Button><Button variant="primary" disabled={apply.isPending || preview.diff.length === 0} onClick={() => apply.mutate(preview.previewId, { onSuccess: () => { setPreview(null); setApiKey(""); toast({ tone: "success", message: "OpenClaw settings applied." }); }, onError: fail })}>{apply.isPending ? "Applying…" : "Apply reviewed diff"}</Button></div></Panel>}{status.data!.configured && <div className="section-gap"><Button variant="danger" disabled={make.isPending || apply.isPending} onClick={() => make.mutate({ action: "reset" }, { onSuccess: setPreview, onError: fail })}>Preview reset</Button></div>}</>}</>;
}

export function CliToolDetail() {
  const [baseUrl, setBaseUrl] = useState(`${window.location.origin}/v1`);
  const [apiKey, setApiKey] = useState("");
  const [model, setModel] = useState("gpt-5-codex");
  const [subagentModel, setSubagentModel] = useState("");
  const [preview, setPreview] = useState<CodexPreview | null>(null);
  const status = useCodexStatus();
  const createPreview = useCodexPreview();
  const applyPreview = useApplyCodexPreview();
  const toast = useToast();
  const fail = (error: unknown) => toast({ tone: "error", ...toProblem(error) });
  const previewConfig = () => createPreview.mutate({ action: "configure", baseUrl, apiKey, model, subagentModel }, { onSuccess: setPreview, onError: fail });
  const previewReset = () => createPreview.mutate({ action: "reset" }, { onSuccess: setPreview, onError: fail });
  const apply = () => preview && applyPreview.mutate(preview.previewId, { onSuccess: (result) => { setPreview(null); setApiKey(""); toast({ tone: "success", message: result.action === "reset" ? "Codex settings reset." : "Codex settings applied." }); }, onError: fail });
  const problem = status.error ? toProblem(status.error) : null;
  return <><PageHeading eyebrow="Integrations / CLI Tools / Codex" title="Codex" description="Preview a local Codex config change, then apply that exact diff." action={status.data && <Pill tone={status.data.configured ? "healthy" : status.data.installed ? "info" : "muted"}>{status.data.configured ? "AIGate configured" : status.data.installed ? "Available" : "Not detected"}</Pill>} />
    {status.isPending ? <StateBlock state="loading" /> : problem ? <StateBlock state="error" code={problem.code} action={<Button onClick={() => void status.refetch()}>Retry</Button>} /> : <>
      <div className="split section-gap"><Panel title="AIGate connection"><form className="stack" onSubmit={(event) => { event.preventDefault(); previewConfig(); }}>
        <Field label="Base URL"><input className="input" value={baseUrl} onChange={(event) => setBaseUrl(event.target.value)} required /></Field>
        <Field label="AIGate API key" hint="Stored in Codex config.toml as a bearer header. The dashboard never reads it back."><input className="input" type="password" autoComplete="new-password" value={apiKey} onChange={(event) => setApiKey(event.target.value)} minLength={8} maxLength={4096} required /></Field>
        <Field label="Default model"><input className="input" value={model} onChange={(event) => setModel(event.target.value)} maxLength={256} required /></Field>
        <Field label="Subagent model (optional)"><input className="input" value={subagentModel} onChange={(event) => setSubagentModel(event.target.value)} maxLength={256} /></Field>
        <Button type="submit" variant="primary" disabled={createPreview.isPending || applyPreview.isPending}>{createPreview.isPending ? "Preparing diff…" : "Preview configuration"}</Button>
      </form></Panel><Panel title="Local file"><div className="stack"><CopyField label="Path" value={status.data!.configPath} /><Warning>Applying stores the key in this local file. The server takes an `.aigate.bak` backup and restricts POSIX permissions to owner read/write.</Warning><Pill tone={status.data!.configured ? "healthy" : "muted"}>{status.data!.model ? `Current model: ${status.data!.model}` : "No AIGate model is configured"}</Pill></div></Panel></div>
      {status.data!.configured && <div className="section-gap"><Button variant="danger" disabled={createPreview.isPending || applyPreview.isPending} onClick={previewReset}>Preview reset</Button></div>}
      {preview && <Panel title={preview.action === "reset" ? "Review reset diff" : "Review configuration diff"} detail={`Target ${preview.configPath}`} className="section-gap"><div className="stack"><pre className="code-block">{preview.diff.map((line) => <div className={line.startsWith("+") ? "text-healthy" : line.startsWith("-") ? "text-danger" : "muted"} key={line}>{line}</div>)}{preview.diff.length === 0 && "No file changes."}</pre><p className="muted">Existing secrets are redacted. This preview expires at {new Date(preview.expiresAt).toLocaleTimeString()}.</p><div className="row"><Button onClick={() => setPreview(null)}>Cancel</Button><Button variant="primary" disabled={applyPreview.isPending || preview.diff.length === 0} onClick={apply}>{applyPreview.isPending ? "Applying…" : "Apply reviewed diff"}</Button></div></div></Panel>}
    </>}
  </>;
}

export { Skills, Mcp } from "./skills-mcp";
