import type { FeatureEntry } from "./schema.js";

const HEADER = `<!-- GENERATED by \`pnpm discovery capabilities\`. Do not hand-edit. -->

# AIGate — Capability Specification

Every item below is a capability AIGate must have. Derived from tracing
9router, but stated as a requirement of AIGate, not as a description of
9router. Suspected bugs are listed separately and must NOT be reproduced.
`;

export function renderCapabilities(entries: FeatureEntry[]): string {
  const out: string[] = [HEADER];
  const groups = new Map<string, FeatureEntry[]>();
  for (const e of entries) {
    const list = groups.get(e.group) ?? [];
    list.push(e);
    groups.set(e.group, list);
  }

  for (const [group, list] of [...groups].sort(([a], [b]) => a.localeCompare(b))) {
    const capabilities = [...list].sort((a, b) => a.id.localeCompare(b.id));
    if (capabilities.length === 0) continue;

    out.push(`## ${group}`, "");
    for (const e of capabilities) {
      out.push(`### ${e.subFeature}`, "");
      out.push(`- **id:** \`${e.id}\` · **module:** \`${e.newModule}\``);
      out.push(`- **Trigger:** ${e.trigger}`);
      out.push(`- **Input:** ${e.input}`);
      out.push(`- **Output:** ${e.output}`);
      if (e.businessRules.length) {
        out.push("- **Rules:**");
        for (const r of e.businessRules) out.push(`  - ${r}`);
      }
      if (e.behavior.streaming) out.push("- **Streaming:** yes");
      if (e.errorCases.length) {
        out.push(
          "- **Errors:** " +
            e.errorCases.map((c) => `\`${c.code}\` (${c.when})`).join(", "),
        );
      }
      // Suspected-bug entries are still capabilities AIGate must have — the
      // defect they carry in 9router does not exempt the underlying behavior
      // from being required. State what AIGate must do; never restate
      // 9router's actual (buggy) behavior here — that lives only in the
      // "Suspected bugs" table below.
      if (e.labels.includes("SUSPECTED_BUG") && e.suspicion) {
        out.push(`- **AIGate required behavior:** ${e.suspicion.expected}`);
      }
      if (e.labels.includes("IMPLEMENTATION_ACCIDENT")) {
        out.push(
          "- **Note:** 9router's mechanism here is an accident of its stack. Behavior required, mechanism not.",
        );
      }
      out.push("");
    }
  }

  const bugs = entries.filter((e) => e.labels.includes("SUSPECTED_BUG"));
  out.push("## Suspected bugs — do NOT reproduce", "");
  if (bugs.length === 0) {
    out.push("None recorded.", "");
  } else {
    out.push("| id | Expected | Actual | Impact |", "|---|---|---|---|");
    for (const b of bugs) {
      const s = b.suspicion;
      if (!s) continue;
      out.push(
        `| \`${cell(b.id)}\` | ${cell(s.expected)} | ${cell(s.actual)} | ${cell(s.impact)} |`,
      );
    }
    out.push("");
  }
  return out.join("\n");
}

/** Escape `|` so an interpolated value can't break a markdown table row's column count. */
function cell(s: string): string {
  return s.replace(/\|/g, "\\|");
}
