import { createHash, randomUUID } from "node:crypto";
import { lstat, mkdir, open, readFile, rename, rm } from "node:fs/promises";
import { homedir } from "node:os";
import { join } from "node:path";
import { BadRequestException, ConflictException, Injectable, NotFoundException } from "@nestjs/common";

const DIR = join(homedir(), ".cline", "data"); const STATE = join(DIR, "globalState.json"); const SECRETS = join(DIR, "secrets.json"); const MAX_BYTES = 1_048_576; const TTL = 300_000;
const digest = (value: string | null) => value === null ? null : createHash("sha256").update(value).digest("hex");
const object = (value: unknown): Record<string, unknown> | null => typeof value === "object" && value !== null && !Array.isArray(value) ? Object.fromEntries(Object.entries(value)) : null;
type Draft = { action: "configure" | "reset"; beforeState: string | null; beforeSecrets: string | null; state: string; secrets: string; expires: number };

// ponytail: one process-local apply queue; shared locking is needed only for multiple AIGate server instances.
@Injectable()
export class ClineSettingsService {
  private readonly previews = new Map<string, Draft>(); private applying: Promise<void> = Promise.resolve();
  async status() { const source = await this.read(STATE); const state = source === null ? {} : this.parse(source, "globalState.json"); const configured = state.actModeApiProvider === "openai" && state.planModeApiProvider === "openai" && typeof state.openAiBaseUrl === "string"; return { installed: source !== null || await this.commandExists(), configured, statePath: STATE, secretsPath: SECRETS, model: typeof state.openAiModelId === "string" ? state.openAiModelId : null, baseUrl: typeof state.openAiBaseUrl === "string" ? state.openAiBaseUrl : null }; }
  async preview(input: unknown) { this.prune(); if (this.previews.size >= 20) throw new ConflictException({ code: "PREVIEW_LIMIT", message: "Close or apply an earlier configuration preview, then retry." }); const action = object(input)?.action; if (action !== "configure" && action !== "reset") throw new BadRequestException({ code: "INVALID_REQUEST", message: "action must be configure or reset" }); const beforeState = await this.read(STATE); const beforeSecrets = await this.read(SECRETS); const next = action === "configure" ? this.configure(beforeState, beforeSecrets, input) : this.reset(beforeState, beforeSecrets); const id = randomUUID(); const expires = Date.now() + TTL; this.previews.set(id, { action, beforeState, beforeSecrets, ...next, expires }); return { previewId: id, action, statePath: STATE, secretsPath: SECRETS, diff: this.diff(beforeState ?? "", next.state, beforeSecrets ?? "", next.secrets), expiresAt: new Date(expires).toISOString() }; }
  async apply(id: string) { const draft = this.previews.get(id); if (!draft || draft.expires < Date.now()) { this.previews.delete(id); throw new NotFoundException({ code: "PREVIEW_EXPIRED", message: "This preview expired. Review a new diff before applying." }); } let release!: () => void; const prior = this.applying; this.applying = new Promise<void>((resolve) => { release = resolve; }); await prior; try { if (digest(await this.read(STATE)) !== digest(draft.beforeState) || digest(await this.read(SECRETS)) !== digest(draft.beforeSecrets)) { this.previews.delete(id); throw new ConflictException({ code: "CONFIG_CHANGED", message: "Cline settings changed after the preview. Review a fresh diff before applying." }); } await this.writeBoth(draft); this.previews.delete(id); return { success: true, action: draft.action, statePath: STATE, secretsPath: SECRETS }; } finally { release(); } }
  private configure(stateSource: string | null, secretsSource: string | null, input: unknown) { const body = object(input) ?? {}; const rawUrl = typeof body.baseUrl === "string" ? body.baseUrl.trim() : ""; const key = typeof body.apiKey === "string" ? body.apiKey : ""; const model = typeof body.model === "string" ? body.model.trim() : ""; let url: URL; try { url = new URL(rawUrl); } catch { throw new BadRequestException({ code: "INVALID_REQUEST", message: "baseUrl must be an absolute HTTP or HTTPS URL" }); } if (!(url.protocol === "http:" || url.protocol === "https:") || url.username || url.password || url.search || url.hash || key.length < 8 || key.length > 4096 || /[\r\n]/.test(key) || !model || model.length > 256) throw new BadRequestException({ code: "INVALID_REQUEST", message: "baseUrl, apiKey, or model is invalid" }); const path = url.pathname.replace(/\/+$/, ""); if (path.endsWith("/v1")) url.pathname = path.slice(0, -3) || "/"; const state = stateSource === null ? {} : this.parse(stateSource, "globalState.json"); const secrets = secretsSource === null ? {} : this.parse(secretsSource, "secrets.json"); return { state: JSON.stringify({ ...state, actModeApiProvider: "openai", planModeApiProvider: "openai", openAiBaseUrl: url.toString().replace(/\/$/, ""), openAiModelId: model, planModeOpenAiModelId: model }, null, 2) + "\n", secrets: JSON.stringify({ ...secrets, openAiApiKey: key }, null, 2) + "\n" }; }
  private reset(stateSource: string | null, secretsSource: string | null) { const state = stateSource === null ? {} : this.parse(stateSource, "globalState.json"); const secrets = secretsSource === null ? {} : this.parse(secretsSource, "secrets.json"); if (state.actModeApiProvider === "openai" && state.planModeApiProvider === "openai") { delete state.openAiBaseUrl; delete state.openAiModelId; delete state.planModeOpenAiModelId; state.actModeApiProvider = "cline"; state.planModeApiProvider = "cline"; } delete secrets.openAiApiKey; return { state: JSON.stringify(state, null, 2) + "\n", secrets: JSON.stringify(secrets, null, 2) + "\n" }; }
  private parse(source: string, name: string): Record<string, unknown> { try { const result = object(JSON.parse(source)); if (!result) throw new Error(); return result; } catch { throw new BadRequestException({ code: "INVALID_REQUEST", message: `Cline ${name} must contain a JSON object before AIGate can safely edit it.` }); } }
  private diff(a: string, b: string, c: string, d: string) { const lines = (oldValue: string, newValue: string, name: string) => { const oldLines = oldValue.split(/\r?\n/).filter(Boolean); const newLines = newValue.split(/\r?\n/).filter(Boolean); const redacted = (line: string) => line.replace(/("(?:openAiApiKey|api[_-]?key|access[_-]?token|password|secret)"\s*:\s*)"[^"]*"/gi, '$1"[redacted]"'); const oldSet = new Set(oldLines); const newSet = new Set(newLines); return [`  ${name}`, ...oldLines.filter((line) => !newSet.has(line)).map((line) => `- ${redacted(line)}`), ...newLines.filter((line) => !oldSet.has(line)).map((line) => `+ ${redacted(line)}`)]; }; return [...lines(a, b, "globalState.json"), ...lines(c, d, "secrets.json")].slice(0, 200); }
  private async read(path: string): Promise<string | null> { try { const info = await lstat(path); if (!info.isFile() || info.isSymbolicLink() || info.size > MAX_BYTES) throw new Error("Cline configuration must be a regular file within the 1 MiB limit"); return await readFile(path, "utf8"); } catch (error) { if (typeof error === "object" && error !== null && "code" in error && error.code === "ENOENT") return null; throw error; } }
  private async writeBoth(draft: Draft) { await mkdir(DIR, { recursive: true, mode: 0o700 }); if (draft.beforeState !== null) await this.atomic(`${STATE}.aigate.bak`, draft.beforeState); if (draft.beforeSecrets !== null) await this.atomic(`${SECRETS}.aigate.bak`, draft.beforeSecrets); await this.atomic(STATE, draft.state); try { await this.atomic(SECRETS, draft.secrets); } catch (error) { if (draft.beforeState !== null) await this.atomic(STATE, draft.beforeState).catch(() => undefined); else await rm(STATE, { force: true }).catch(() => undefined); throw error; } }
  private async atomic(path: string, content: string) { const temp = `${path}.${randomUUID()}.tmp`; let file; try { file = await open(temp, "wx", 0o600); await file.writeFile(content, "utf8"); await file.sync(); await file.close(); file = undefined; await rename(temp, path); } finally { await file?.close().catch(() => undefined); await rm(temp, { force: true }).catch(() => undefined); } }
  private async commandExists() { const { accessSync, constants, statSync } = await import("node:fs"); const extensions = process.platform === "win32" ? (process.env.PATHEXT ?? ".EXE;.CMD;.BAT").split(";") : [""]; for (const directory of (process.env.PATH ?? "").split(process.platform === "win32" ? ";" : ":")) for (const extension of extensions) try { const file = join(directory, `cline${extension}`); if (statSync(file).isFile()) { if (process.platform !== "win32") accessSync(file, constants.X_OK); return true; } } catch { /* continue */ } return false; }
  private prune() { for (const [id, draft] of this.previews) if (draft.expires < Date.now()) this.previews.delete(id); }
}
