import { createHash, randomUUID } from "node:crypto";
import { lstat, mkdir, open, readFile, rename, rm } from "node:fs/promises";
import { homedir } from "node:os";
import { dirname, join } from "node:path";
import { BadRequestException, ConflictException, Injectable, NotFoundException } from "@nestjs/common";

const FILE = join(homedir(), ".factory", "settings.json"); const hash = (v: string | null) => v === null ? null : createHash("sha256").update(v).digest("hex"); const obj = (v: unknown): Record<string, unknown> | null => typeof v === "object" && v !== null && !Array.isArray(v) ? Object.fromEntries(Object.entries(v)) : null; const managed = (v: unknown) => { const entry = obj(v); return typeof entry?.id === "string" && entry.id.startsWith("custom:9Router"); };
type Draft = { before: string | null; next: string; action: "configure" | "reset"; expires: number };
@Injectable()
export class DroidSettingsService {
  private drafts = new Map<string, Draft>(); private queue: Promise<void> = Promise.resolve();
  async status() { const raw = await this.read(); const cfg = raw ? this.parse(raw) : {}; const models = Array.isArray(cfg.customModels) ? cfg.customModels.map(obj).filter((m): m is Record<string, unknown> => typeof m?.id === "string" && m.id.startsWith("custom:9Router")).map((m) => typeof m.model === "string" ? m.model : "").filter(Boolean) : []; return { installed: raw !== null || await this.installed(), configured: models.length > 0, configPath: FILE, models }; }
  async preview(input: unknown) { this.prune(); if (this.drafts.size >= 20) throw new ConflictException({ code: "PREVIEW_LIMIT", message: "Close or apply an earlier configuration preview, then retry." }); const action = obj(input)?.action; if (action !== "configure" && action !== "reset") throw new BadRequestException({ code: "INVALID_REQUEST", message: "action must be configure or reset" }); const before = await this.read(); const next = action === "configure" ? this.configure(before, input) : this.reset(before); const id = randomUUID(); const expires = Date.now() + 300_000; this.drafts.set(id, { before, next, action, expires }); return { previewId: id, action, configPath: FILE, backupPath: `${FILE}.aigate.bak`, diff: this.diff(before ?? "", next), expiresAt: new Date(expires).toISOString() }; }
  async apply(id: string) { const draft = this.drafts.get(id); if (!draft || draft.expires < Date.now()) { this.drafts.delete(id); throw new NotFoundException({ code: "PREVIEW_EXPIRED", message: "This preview expired. Review a new diff before applying." }); } let release!: () => void; const old = this.queue; this.queue = new Promise<void>((resolve) => { release = resolve; }); await old; try { if (hash(await this.read()) !== hash(draft.before)) throw new ConflictException({ code: "CONFIG_CHANGED", message: "Droid settings changed after the preview. Review a fresh diff before applying." }); await mkdir(dirname(FILE), { recursive: true, mode: 0o700 }); if (draft.before !== null) await this.write(`${FILE}.aigate.bak`, draft.before); await this.write(FILE, draft.next); this.drafts.delete(id); return { success: true, action: draft.action, configPath: FILE }; } finally { release(); } }
  private configure(raw: string | null, input: unknown) { const body = obj(input) ?? {}; const base = typeof body.baseUrl === "string" ? body.baseUrl.trim() : ""; const key = typeof body.apiKey === "string" ? body.apiKey : ""; const model = typeof body.model === "string" ? body.model.trim() : ""; let url: URL; try { url = new URL(base); } catch { throw new BadRequestException({ code: "INVALID_REQUEST", message: "baseUrl must be an absolute HTTP or HTTPS URL" }); } if (!(url.protocol === "http:" || url.protocol === "https:") || url.username || url.password || url.search || url.hash || key.length < 8 || key.length > 4096 || /[\r\n]/.test(key) || !model || model.length > 256) throw new BadRequestException({ code: "INVALID_REQUEST", message: "baseUrl, apiKey, or model is invalid" }); const path = url.pathname.replace(/\/+$/, ""); if (!path.endsWith("/v1")) url.pathname = `${path}/v1`; const cfg = raw ? this.parse(raw) : {}; const others = Array.isArray(cfg.customModels) ? cfg.customModels.filter((v) => !managed(v)) : []; return JSON.stringify({ ...cfg, customModels: [...others, { model, id: "custom:9Router-0", index: 0, baseUrl: url.toString().replace(/\/$/, ""), apiKey: key, displayName: model, maxOutputTokens: 131072, noImageSupport: false, provider: "openai" }] }, null, 2) + "\n"; }
  private reset(raw: string | null) { if (!raw) return ""; const cfg = this.parse(raw); const customModels = Array.isArray(cfg.customModels) ? cfg.customModels.filter((v) => !managed(v)) : []; const next: Record<string, unknown> = { ...cfg, ...(customModels.length ? { customModels } : {}) }; if (!customModels.length) delete next.customModels; return JSON.stringify(next, null, 2) + "\n"; }
  private parse(raw: string) { try { const out = obj(JSON.parse(raw)); if (!out) throw new Error(); return out; } catch { throw new BadRequestException({ code: "INVALID_REQUEST", message: "Droid settings.json must contain a JSON object before AIGate can safely edit it." }); } }
  private diff(a: string, b: string) { const old = a.split(/\r?\n/).filter(Boolean), next = b.split(/\r?\n/).filter(Boolean), x = new Set(old), y = new Set(next); const redact = (l: string) => l.replace(/("(?:apiKey|api[_-]?key|token|secret)"\s*:\s*)"[^"]*"/i, '$1"[redacted]"'); return [...old.filter((l) => !y.has(l)).map((l) => `- ${redact(l)}`), ...next.filter((l) => !x.has(l)).map((l) => `+ ${redact(l)}`)].slice(0, 200); }
  private async read() { try { const s = await lstat(FILE); if (!s.isFile() || s.isSymbolicLink() || s.size > 1_048_576) throw new Error("Droid config must be a regular file within the 1 MiB limit"); return await readFile(FILE, "utf8"); } catch (e) { if (typeof e === "object" && e !== null && "code" in e && e.code === "ENOENT") return null; throw e; } }
  private async write(path: string, content: string) { const temp = `${path}.${randomUUID()}.tmp`; let f; try { f = await open(temp, "wx", 0o600); await f.writeFile(content); await f.sync(); await f.close(); f = undefined; await rename(temp, path); } finally { await f?.close().catch(() => undefined); await rm(temp, { force: true }).catch(() => undefined); } }
  private async installed() { const { statSync } = await import("node:fs"); const exts = process.platform === "win32" ? (process.env.PATHEXT ?? ".EXE;.CMD;.BAT").split(";") : [""]; for (const d of (process.env.PATH ?? "").split(process.platform === "win32" ? ";" : ":")) for (const e of exts) try { if (statSync(join(d, `droid${e}`)).isFile()) return true; } catch { /* next */ } return false; }
  private prune() { for (const [id, draft] of this.drafts) if (draft.expires < Date.now()) this.drafts.delete(id); }
}
