import { createHash, randomUUID } from "node:crypto";
import { existsSync } from "node:fs";
import { lstat, mkdir, open, readFile, rename, rm } from "node:fs/promises";
import { homedir } from "node:os";
import { dirname, join } from "node:path";
import { BadRequestException, ConflictException, Injectable, NotFoundException } from "@nestjs/common";

const FILE = join(homedir(), ".grok", "config.toml"), TYPES = ["general-purpose", "explore", "plan"] as const, hash = (value: string | null) => value === null ? null : createHash("sha256").update(value).digest("hex");
type Draft = { before: string | null; next: string; action: "configure" | "reset"; expires: number }; type Subagents = Partial<Record<(typeof TYPES)[number], { model: string; contextWindow?: number }>>;
@Injectable() export class GrokBuildSettingsService {
  private previews = new Map<string, Draft>(); private tail: Promise<void> = Promise.resolve();
  async status() { const source = await this.read(FILE); return { installed: source !== null || this.commandExists(), configured: source !== null && this.section(source, "model.9router") !== null, configPath: FILE, subagents: TYPES.filter((type) => this.field(source ?? "", "subagents.models", type) === `9router-${type}`) }; }
  async preview(input: unknown) { this.prune(); if (this.previews.size >= 20) throw new ConflictException({ code: "PREVIEW_LIMIT", message: "Close or apply an earlier configuration preview, then retry." }); const body = this.object(input), action = body?.["action"]; if (action !== "configure" && action !== "reset") throw new BadRequestException({ code: "INVALID_REQUEST", message: "action must be configure or reset" }); const before = await this.read(FILE), next = action === "configure" ? this.configure(before ?? "", body ?? {}) : this.reset(before ?? ""); const previewId = randomUUID(), expires = Date.now() + 300_000; this.previews.set(previewId, { before, next, action, expires }); return { previewId, action, configPath: FILE, diff: this.diff(before ?? "", next), expiresAt: new Date(expires).toISOString() }; }
  async apply(id: string) { const draft = this.previews.get(id); if (!draft || draft.expires < Date.now()) { this.previews.delete(id); throw new NotFoundException({ code: "PREVIEW_EXPIRED", message: "This preview expired. Review a fresh diff before applying." }); } let release!: () => void; const prior = this.tail; this.tail = new Promise<void>((resolve) => { release = resolve; }); await prior; try { if (hash(await this.read(FILE)) !== hash(draft.before)) throw new ConflictException({ code: "CONFIG_CHANGED", message: "Grok Build settings changed after the preview. Review a fresh diff before applying." }); await mkdir(dirname(FILE), { recursive: true, mode: 0o700 }); if (draft.before !== null) await this.write(`${FILE}.aigate.bak`, draft.before); await this.write(FILE, draft.next); this.previews.delete(id); return { success: true, action: draft.action, configPath: FILE }; } finally { release(); } }
  private configure(source: string, body: Record<string, unknown>) { const baseUrl = this.url(body), apiKey = this.key(body), model = this.model(body), contextWindow = this.window(body["contextWindow"], 128_000), subagents = this.subagents(body["subagentModels"]); let next = this.rememberDefault(source); next = this.upsert(next, "model.9router", this.modelSection(model, baseUrl, apiKey, contextWindow, "9Router")); next = this.set(next, "models", "default", "9router"); if (subagents !== undefined) for (const type of TYPES) { const selected = subagents[type], slot = `9router-${type}`; if (selected) { next = this.rememberSubagent(next, type); next = this.upsert(next, `model.${slot}`, this.modelSection(selected.model, baseUrl, apiKey, this.window(selected.contextWindow, contextWindow), `9Router ${type}`)); next = this.set(next, "subagents.models", type, slot); } else { next = this.restoreSubagent(next, type); next = this.remove(next, `model.${slot}`); } } return next; }
  private reset(source: string) { let next = source; for (const type of TYPES) { next = this.restoreSubagent(next, type); next = this.remove(next, `model.9router-${type}`); } next = this.remove(next, "model.9router"); return this.restoreDefault(next).replace(/\n{3,}/g, "\n\n"); }
  private section(source: string, name: string) { const escaped = name.replaceAll(".", "\\."), match = source.match(new RegExp(`^\\[${escaped}\\]\\r?\\n([\\s\\S]*?)(?=^\\[|$)`, "m")); return match ? match[0] : null; }
  private upsert(source: string, name: string, value: string) { const existing = this.section(source, name); return existing ? source.replace(existing, value) : `${source.trimEnd()}${source.trim() ? "\n\n" : ""}${value}`; }
  private remove(source: string, name: string) { const existing = this.section(source, name); return existing ? source.replace(existing, "") : source; }
  private field(source: string, section: string, key: string) { const body = this.section(source, section); return body?.match(new RegExp(`^${key.replaceAll(".", "\\.")}\\s*=\\s*"([^"]*)"`, "m"))?.[1] ?? null; }
  private set(source: string, section: string, key: string, value: string) { const existing = this.section(source, section), line = `${key} = ${JSON.stringify(value)}`; if (!existing) return `${source.trimEnd()}${source.trim() ? "\n\n" : ""}[${section}]\n${line}\n`; const pattern = new RegExp(`^${key.replaceAll(".", "\\.")}\\s*=.*\\r?\\n?`, "m"), body = pattern.test(existing) ? existing.replace(pattern, `${line}\n`) : existing.replace(`\n`, `\n${line}\n`); return source.replace(existing, body); }
  private marker(source: string, key: string) { return source.match(new RegExp(`^# aigate: grok-${key} = "([^"]*)"\\r?\\n?`, "m"))?.[1] ?? null; }
  private rememberDefault(source: string) { if (this.marker(source, "default") !== null) return source; const current = this.field(source, "models", "default"); return current && current !== "9router" ? `# aigate: grok-default = ${JSON.stringify(current)}\n${source}` : source; }
  private restoreDefault(source: string) { const previous = this.marker(source, "default") ?? "grok-build", next = source.replace(/^# aigate: grok-default = "[^"]*"\r?\n?/m, ""); return this.field(next, "models", "default") === "9router" ? this.set(next, "models", "default", previous) : next; }
  private rememberSubagent(source: string, type: (typeof TYPES)[number]) { const key = `subagent-${type}`; if (this.marker(source, key) !== null) return source; return `# aigate: grok-${key} = ${JSON.stringify(this.field(source, "subagents.models", type) ?? "__unset__")}\n${source}`; }
  private restoreSubagent(source: string, type: (typeof TYPES)[number]) { const key = `subagent-${type}`, previous = this.marker(source, key) ?? "__unset__", next = source.replace(new RegExp(`^# aigate: grok-${key} = "[^"]*"\\r?\\n?`, "m"), ""); if (this.field(next, "subagents.models", type) !== `9router-${type}`) return next; return previous === "__unset__" ? this.deleteField(next, "subagents.models", type) : this.set(next, "subagents.models", type, previous); }
  private deleteField(source: string, section: string, key: string) { const existing = this.section(source, section); if (!existing) return source; const body = existing.replace(new RegExp(`^${key.replaceAll(".", "\\.")}\\s*=.*\\r?\\n?`, "m"), ""); return body.trim() === `[${section}]` ? source.replace(existing, "") : source.replace(existing, body); }
  private modelSection(model: string, baseUrl: string, apiKey: string, contextWindow: number, name: string) { return `[model.${name === "9Router" ? "9router" : `9router-${name.slice(8)}`}]\nmodel = ${JSON.stringify(model)}\nbase_url = ${JSON.stringify(baseUrl)}\nname = ${JSON.stringify(name)}\ndescription = "Routed via AIGate gateway"\napi_backend = "chat_completions"\napi_key = ${JSON.stringify(apiKey)}\ncontext_window = ${contextWindow}\n`; }
  private subagents(value: unknown): Subagents | undefined { if (value === undefined) return undefined; const input = this.object(value); if (!input) return {}; const result: Subagents = {}; for (const type of TYPES) { const item = input[type], entry = this.object(item), model = typeof item === "string" ? item.trim() : entry?.["model"], contextWindow = entry?.["contextWindow"]; if (typeof model === "string" && model.trim()) result[type] = { model: model.trim(), ...(typeof contextWindow === "number" ? { contextWindow } : {}) }; } return result; }
  private object(value: unknown): Record<string, unknown> | null { return typeof value === "object" && value !== null && !Array.isArray(value) ? Object.fromEntries(Object.entries(value)) : null; } private model(body: Record<string, unknown>) { const value = typeof body["model"] === "string" ? body.model.trim() : ""; if (!value || value.length > 256) throw new BadRequestException({ code: "INVALID_REQUEST", message: "model is invalid" }); return value; } private key(body: Record<string, unknown>) { const value = typeof body["apiKey"] === "string" ? body.apiKey : ""; if (value.length < 8 || value.length > 4096 || /[\r\n]/.test(value)) throw new BadRequestException({ code: "INVALID_REQUEST", message: "apiKey is invalid" }); return value; } private window(value: unknown, fallback: number) { const parsed = Number(value); return Number.isFinite(parsed) && parsed > 0 && parsed <= 10_000_000 ? Math.floor(parsed) : fallback; } private url(body: Record<string, unknown>) { const raw = typeof body["baseUrl"] === "string" ? body.baseUrl.trim() : ""; let url: URL; try { url = new URL(raw); } catch { throw new BadRequestException({ code: "INVALID_REQUEST", message: "baseUrl must be an absolute HTTP or HTTPS URL" }); } if (!(url.protocol === "http:" || url.protocol === "https:") || url.username || url.password || url.search || url.hash) throw new BadRequestException({ code: "INVALID_REQUEST", message: "baseUrl is invalid" }); const path = url.pathname.replace(/\/+$/, ""); url.pathname = path.endsWith("/v1") ? path : `${path}/v1`; return url.toString().replace(/\/$/, ""); }
  private diff(before: string, after: string) { const old = before.split(/\r?\n/).filter(Boolean), next = after.split(/\r?\n/).filter(Boolean), x = new Set(old), y = new Set(next), redact = (line: string) => line.replace(/(api_key\s*=\s*)"[^"]*"/i, '$1"[redacted]"'); return [...old.filter((line) => !y.has(line)).map((line) => `- ${redact(line)}`), ...next.filter((line) => !x.has(line)).map((line) => `+ ${redact(line)}`)].slice(0, 200); } private async read(path: string): Promise<string | null> { try { const info = await lstat(path); if (!info.isFile() || info.isSymbolicLink() || info.size > 1_048_576) throw new Error("Grok config must be a regular file within the 1 MiB limit"); return await readFile(path, "utf8"); } catch (error) { if (typeof error === "object" && error !== null && "code" in error && error.code === "ENOENT") return null; throw error; } } private async write(path: string, content: string) { const temp = `${path}.${randomUUID()}.tmp`; let file; try { file = await open(temp, "wx", 0o600); await file.writeFile(content); await file.sync(); await file.close(); file = undefined; await rename(temp, path); } finally { await file?.close().catch(() => undefined); await rm(temp, { force: true }).catch(() => undefined); } } private commandExists() { const names = process.platform === "win32" ? ["grok.exe", "grok.cmd", "grok.bat"] : ["grok"]; return (process.env.PATH ?? "").split(process.platform === "win32" ? ";" : ":").some((directory) => names.some((name) => existsSync(join(directory, name)))); } private prune() { for (const [id, draft] of this.previews) if (draft.expires < Date.now()) this.previews.delete(id); }
}
