import { createHash, randomUUID } from "node:crypto";
import { existsSync } from "node:fs";
import { lstat, mkdir, open, readFile, rename, rm } from "node:fs/promises";
import { homedir } from "node:os";
import { dirname, join } from "node:path";
import { BadRequestException, ConflictException, Injectable, NotFoundException } from "@nestjs/common";

const CONFIG = join(homedir(), ".jcode", "config.toml"), ENV = join(process.env["XDG_CONFIG_HOME"] ?? join(homedir(), ".config"), "jcode", "provider-9router.env"), hash = (value: string | null) => value === null ? null : createHash("sha256").update(value).digest("hex");
type Draft = { configBefore: string | null; envBefore: string | null; config: string; env: string; action: "configure" | "reset"; expires: number };
@Injectable() export class JcodeSettingsService {
  private previews = new Map<string, Draft>(); private tail: Promise<void> = Promise.resolve();
  async status() { const config = await this.read(CONFIG); return { installed: config !== null || this.commandExists(), configured: config !== null && /^# aigate: jcode-owned$/m.test(config), configPath: CONFIG, envPath: ENV }; }
  async preview(input: unknown) { this.prune(); if (this.previews.size >= 20) throw new ConflictException({ code: "PREVIEW_LIMIT", message: "Close or apply an earlier configuration preview, then retry." }); const action = this.object(input)?.["action"]; if (action !== "configure" && action !== "reset") throw new BadRequestException({ code: "INVALID_REQUEST", message: "action must be configure or reset" }); const configBefore = await this.read(CONFIG), envBefore = await this.read(ENV), next = action === "configure" ? this.configure(configBefore ?? "", envBefore ?? "", input) : this.reset(configBefore ?? "", envBefore ?? ""); const previewId = randomUUID(), expires = Date.now() + 300_000; this.previews.set(previewId, { configBefore, envBefore, ...next, action, expires }); return { previewId, action, configPath: CONFIG, envPath: ENV, diff: this.diff(configBefore ?? "", next.config, envBefore ?? "", next.env), expiresAt: new Date(expires).toISOString() }; }
  async apply(id: string) { const draft = this.previews.get(id); if (!draft || draft.expires < Date.now()) { this.previews.delete(id); throw new NotFoundException({ code: "PREVIEW_EXPIRED", message: "This preview expired. Review a fresh diff before applying." }); } let release!: () => void; const prior = this.tail; this.tail = new Promise<void>((resolve) => { release = resolve; }); await prior; const written: { path: string; before: string | null }[] = []; try { if (hash(await this.read(CONFIG)) !== hash(draft.configBefore) || hash(await this.read(ENV)) !== hash(draft.envBefore)) throw new ConflictException({ code: "CONFIG_CHANGED", message: "JCode settings changed after the preview. Review a fresh diff before applying." }); for (const target of [{ path: CONFIG, before: draft.configBefore, next: draft.config }, { path: ENV, before: draft.envBefore, next: draft.env }]) { await mkdir(dirname(target.path), { recursive: true, mode: 0o700 }); if (target.before !== null) await this.write(`${target.path}.aigate.bak`, target.before); await this.write(target.path, target.next); written.push(target); } this.previews.delete(id); return { success: true, action: draft.action, configPath: CONFIG, envPath: ENV }; } catch (error) { for (const target of written.reverse()) if (target.before === null) await rm(target.path, { force: true }).catch(() => undefined); else await this.write(target.path, target.before).catch(() => undefined); throw error; } finally { release(); } }
  private configure(config: string, env: string, input: unknown) { const body = this.object(input) ?? {}, baseUrl = this.url(body), apiKey = this.key(body), model = this.model(body), owned = /^# aigate: jcode-owned$/m.test(config), previous = this.table(config, "providers.9router"), key = this.envLine(env), cleanConfig = this.removeTable(config, "providers.9router").trim(), cleanEnv = this.removeEnv(env).trim(); const configHead = owned ? cleanConfig : [`# aigate: jcode-owned`, `# aigate: jcode-provider ${Buffer.from(previous).toString("base64")}`, cleanConfig].filter(Boolean).join("\n"); const envHead = /^# aigate: jcode-owned$/m.test(env) ? cleanEnv : [`# aigate: jcode-owned`, `# aigate: jcode-key ${Buffer.from(key).toString("base64")}`, cleanEnv].filter(Boolean).join("\n"); return { config: `${configHead.trim()}${configHead.trim() ? "\n\n" : ""}[providers.9router]\ntype = "openai-compatible"\nbase_url = ${JSON.stringify(baseUrl)}\nauth = "bearer"\napi_key_env = "JCODE_9ROUTER_API_KEY"\nenv_file = "provider-9router.env"\ndefault_model = ${JSON.stringify(model)}\nrequires_api_key = true\n`, env: `${envHead.trim()}${envHead.trim() ? "\n" : ""}JCODE_9ROUTER_API_KEY=${JSON.stringify(apiKey)}\n` }; }
  private reset(config: string, env: string) { const configOwned = /^# aigate: jcode-owned$/m.test(config), envOwned = /^# aigate: jcode-owned$/m.test(env), previous = this.marker(config, "provider"), key = this.marker(env, "key"), cleanConfig = this.removeTable(config, "providers.9router").replace(/^# aigate: jcode-(?:owned|provider).*\r?\n/gm, "").trim(), cleanEnv = this.removeEnv(env).replace(/^# aigate: jcode-(?:owned|key).*\r?\n/gm, "").trim(); return { config: configOwned ? `${[cleanConfig, previous].filter(Boolean).join("\n\n")}\n` : config, env: envOwned ? `${[cleanEnv, key].filter(Boolean).join("\n")}\n` : env }; }
  private table(source: string, table: string) { const lines = source.split(/\r?\n/), start = lines.findIndex((line) => new RegExp(`^\\s*\\[${table}\\]\\s*(?:#.*)?$`).test(line)); if (start < 0) return ""; const end = this.tableEnd(lines, start, table); return lines.slice(start, end < 0 ? lines.length : end).join("\n").trim(); }
  private removeTable(source: string, table: string) { const lines = source.split(/\r?\n/), start = lines.findIndex((line) => new RegExp(`^\\s*\\[${table}\\]\\s*(?:#.*)?$`).test(line)); if (start < 0) return source; const end = this.tableEnd(lines, start, table); lines.splice(start, (end < 0 ? lines.length : end) - start); return lines.join("\n"); }
  private tableEnd(lines: string[], start: number, table: string) { const nested = new RegExp(`^\\s*\\[${table.replaceAll(".", "\\\\.")}(?:\\.|\\])`); return lines.findIndex((line, index) => index > start && /^\s*\[/.test(line) && !nested.test(line)); }
  private envLine(source: string) { return source.match(/^JCODE_9ROUTER_API_KEY=.*$/m)?.[0] ?? ""; } private removeEnv(source: string) { return source.replace(/^JCODE_9ROUTER_API_KEY=.*\r?\n?/gm, ""); } private marker(source: string, key: string) { const value = source.match(new RegExp(`^# aigate: jcode-${key}\\s+(.+)$`, "m"))?.[1]; return value ? Buffer.from(value, "base64").toString("utf8") : ""; }
  private object(value: unknown): Record<string, unknown> | null { return typeof value === "object" && value !== null && !Array.isArray(value) ? Object.fromEntries(Object.entries(value)) : null; } private model(body: Record<string, unknown>) { const value = typeof body["model"] === "string" ? body.model.trim() : ""; if (!value || value.length > 256) throw new BadRequestException({ code: "INVALID_REQUEST", message: "model is invalid" }); return value; } private key(body: Record<string, unknown>) { const value = typeof body["apiKey"] === "string" ? body.apiKey : ""; if (value.length < 8 || value.length > 4096 || /[\r\n]/.test(value)) throw new BadRequestException({ code: "INVALID_REQUEST", message: "apiKey is invalid" }); return value; } private url(body: Record<string, unknown>) { const raw = typeof body["baseUrl"] === "string" ? body.baseUrl.trim() : ""; let url: URL; try { url = new URL(raw); } catch { throw new BadRequestException({ code: "INVALID_REQUEST", message: "baseUrl must be an absolute HTTP or HTTPS URL" }); } if (!(url.protocol === "http:" || url.protocol === "https:") || url.username || url.password || url.search || url.hash) throw new BadRequestException({ code: "INVALID_REQUEST", message: "baseUrl is invalid" }); const path = url.pathname.replace(/\/+$/, ""); url.pathname = path.endsWith("/v1") ? path : `${path}/v1`; return url.toString().replace(/\/$/, ""); }
  private diff(a: string, b: string, c: string, d: string) { const make = (before: string, after: string, name: string) => { const old = before.split(/\r?\n/).filter(Boolean), next = after.split(/\r?\n/).filter(Boolean), x = new Set(old), y = new Set(next), redact = (line: string) => line.replace(/((?:api[_-]?key|token|secret)\s*(?::|=)\s*)[^\s]+/i, '$1[redacted]'); return [`  ${name}`, ...old.filter((line) => !y.has(line)).map((line) => `- ${redact(line)}`), ...next.filter((line) => !x.has(line)).map((line) => `+ ${redact(line)}`)]; }; return [...make(a, b, CONFIG), ...make(c, d, ENV)].slice(0, 200); }
  private async read(path: string): Promise<string | null> { try { const info = await lstat(path); if (!info.isFile() || info.isSymbolicLink() || info.size > 1_048_576) throw new Error("JCode config must be a regular file within the 1 MiB limit"); return await readFile(path, "utf8"); } catch (error) { if (typeof error === "object" && error !== null && "code" in error && error.code === "ENOENT") return null; throw error; } } private async write(path: string, content: string) { const temp = `${path}.${randomUUID()}.tmp`; let file; try { file = await open(temp, "wx", 0o600); await file.writeFile(content); await file.sync(); await file.close(); file = undefined; await rename(temp, path); } finally { await file?.close().catch(() => undefined); await rm(temp, { force: true }).catch(() => undefined); } } private commandExists() { const names = process.platform === "win32" ? ["jcode.exe", "jcode.cmd", "jcode.bat"] : ["jcode"]; return (process.env.PATH ?? "").split(process.platform === "win32" ? ";" : ":").some((directory) => names.some((name) => existsSync(join(directory, name)))); } private prune() { for (const [id, draft] of this.previews) if (draft.expires < Date.now()) this.previews.delete(id); }
}
