import { createHash, randomUUID } from "node:crypto";
import { lstat, mkdir, open, readFile, rename, rm } from "node:fs/promises";
import { homedir } from "node:os";
import { dirname, join } from "node:path";
import { BadRequestException, ConflictException, Injectable, NotFoundException } from "@nestjs/common";
const AUTH = join(homedir(), ".local", "share", "kilo", "auth.json"), VSCODE = join(process.platform === "win32" ? process.env["APPDATA"] ?? homedir() : homedir(), process.platform === "win32" ? "Code/User/settings.json" : ".config/Code/User/settings.json"), hash = (v: string | null) => v === null ? null : createHash("sha256").update(v).digest("hex"), object = (v: unknown): Record<string, unknown> | null => typeof v === "object" && v !== null && !Array.isArray(v) ? Object.fromEntries(Object.entries(v)) : null;
type Draft = { beforeAuth: string | null; beforeVscode: string | null; auth: string; vscode: string; action: "configure" | "reset"; expires: number };
@Injectable() export class KiloSettingsService {
  private previews = new Map<string, Draft>(); private tail: Promise<void> = Promise.resolve();
  async status() { const source = await this.read(AUTH); const auth = source ? this.parse(source, "auth.json") : {}; const entry = object(auth["openai-compatible"]); return { installed: source !== null || await this.commandExists(), configured: typeof entry?.baseUrl === "string", authPath: AUTH, vscodePath: VSCODE, model: typeof entry?.model === "string" ? entry.model : null }; }
  async preview(input: unknown) { this.prune(); if (this.previews.size >= 20) throw new ConflictException({ code: "PREVIEW_LIMIT", message: "Close or apply an earlier configuration preview, then retry." }); const action = object(input)?.action; if (action !== "configure" && action !== "reset") throw new BadRequestException({ code: "INVALID_REQUEST", message: "action must be configure or reset" }); const beforeAuth = await this.read(AUTH), beforeVscode = await this.read(VSCODE), next = action === "configure" ? this.configure(beforeAuth, beforeVscode, input) : this.reset(beforeAuth, beforeVscode); const previewId = randomUUID(), expires = Date.now() + 300_000; this.previews.set(previewId, { beforeAuth, beforeVscode, ...next, action, expires }); return { previewId, action, authPath: AUTH, vscodePath: VSCODE, diff: this.diff(beforeAuth ?? "", next.auth, beforeVscode ?? "", next.vscode), expiresAt: new Date(expires).toISOString() }; }
  async apply(id: string) { const draft = this.previews.get(id); if (!draft || draft.expires < Date.now()) { this.previews.delete(id); throw new NotFoundException({ code: "PREVIEW_EXPIRED", message: "This preview expired. Review a new diff before applying." }); } let release!: () => void; const prior = this.tail; this.tail = new Promise<void>((resolve) => { release = resolve; }); await prior; try { if (hash(await this.read(AUTH)) !== hash(draft.beforeAuth) || hash(await this.read(VSCODE)) !== hash(draft.beforeVscode)) throw new ConflictException({ code: "CONFIG_CHANGED", message: "Kilo settings changed after the preview. Review a fresh diff before applying." }); await mkdir(dirname(AUTH), { recursive: true, mode: 0o700 }); if (draft.beforeAuth !== null) await this.write(`${AUTH}.aigate.bak`, draft.beforeAuth); if (draft.beforeVscode !== null) await this.write(`${VSCODE}.aigate.bak`, draft.beforeVscode); await this.write(AUTH, draft.auth); try { await mkdir(dirname(VSCODE), { recursive: true, mode: 0o700 }); await this.write(VSCODE, draft.vscode); } catch (error) { if (draft.beforeAuth !== null) await this.write(AUTH, draft.beforeAuth).catch(() => undefined); else await rm(AUTH, { force: true }).catch(() => undefined); throw error; } this.previews.delete(id); return { success: true, action: draft.action, authPath: AUTH, vscodePath: VSCODE }; } finally { release(); } }
  private configure(a: string | null, v: string | null, input: unknown) { const body = object(input) ?? {}, base = typeof body.baseUrl === "string" ? body.baseUrl.trim() : "", apiKey = typeof body.apiKey === "string" ? body.apiKey : "", model = typeof body.model === "string" ? body.model.trim() : ""; let url: URL; try { url = new URL(base); } catch { throw new BadRequestException({ code: "INVALID_REQUEST", message: "baseUrl must be an absolute HTTP or HTTPS URL" }); } if (!(url.protocol === "http:" || url.protocol === "https:") || url.username || url.password || url.search || url.hash || apiKey.length < 8 || apiKey.length > 4096 || /[\r\n]/.test(apiKey) || !model || model.length > 256) throw new BadRequestException({ code: "INVALID_REQUEST", message: "baseUrl, apiKey, or model is invalid" }); const path = url.pathname.replace(/\/+$/, ""); url.pathname = path.endsWith("/v1") ? path : `${path}/v1`; const baseUrl = url.toString().replace(/\/$/, ""), auth = a ? this.parse(a, "auth.json") : {}, vscode = v ? this.parse(v, "settings.json") : {}; return { auth: JSON.stringify({ ...auth, "openai-compatible": { type: "api-key", apiKey, baseUrl, model } }, null, 2) + "\n", vscode: JSON.stringify({ ...vscode, "kilocode.customProvider": { name: "9Router", baseURL: baseUrl, apiKey }, "kilocode.defaultModel": model }, null, 2) + "\n" }; }
  private reset(a: string | null, v: string | null) { const auth = a ? this.parse(a, "auth.json") : {}, vscode = v ? this.parse(v, "settings.json") : {}; delete auth["openai-compatible"]; delete auth["9router"]; delete vscode["kilocode.customProvider"]; delete vscode["kilocode.defaultModel"]; return { auth: JSON.stringify(auth, null, 2) + "\n", vscode: JSON.stringify(vscode, null, 2) + "\n" }; }
  private parse(v: string, name: string) { try { const result = object(JSON.parse(v)); if (!result) throw new Error(); return result; } catch { throw new BadRequestException({ code: "INVALID_REQUEST", message: `Kilo ${name} must contain a JSON object before AIGate can safely edit it.` }); } } private diff(a: string, b: string, c: string, d: string) { const make = (x: string, y: string, n: string) => { const old = x.split(/\r?\n/).filter(Boolean), next = y.split(/\r?\n/).filter(Boolean), p = new Set(old), q = new Set(next), redact = (l: string) => l.replace(/("(?:apiKey|api[_-]?key|token|secret)"\s*:\s*)"[^"]*"/gi, '$1"[redacted]"'); return [n, ...old.filter((l) => !q.has(l)).map((l) => `- ${redact(l)}`), ...next.filter((l) => !p.has(l)).map((l) => `+ ${redact(l)}`)]; }; return [...make(a, b, "auth.json"), ...make(c, d, "settings.json")].slice(0, 200); }
  private async read(path: string): Promise<string | null> { try { const s = await lstat(path); if (!s.isFile() || s.isSymbolicLink() || s.size > 1_048_576) throw new Error("Kilo config must be a regular file within the 1 MiB limit"); return await readFile(path, "utf8"); } catch (e) { if (typeof e === "object" && e !== null && "code" in e && e.code === "ENOENT") return null; throw e; } } private async write(path: string, value: string) { const temp = `${path}.${randomUUID()}.tmp`; let file; try { file = await open(temp, "wx", 0o600); await file.writeFile(value); await file.sync(); await file.close(); file = undefined; await rename(temp, path); } finally { await file?.close().catch(() => undefined); await rm(temp, { force: true }).catch(() => undefined); } } private async commandExists() { const { statSync } = await import("node:fs"); const ext = process.platform === "win32" ? (process.env.PATHEXT ?? ".EXE;.CMD;.BAT").split(";") : [""]; for (const d of (process.env.PATH ?? "").split(process.platform === "win32" ? ";" : ":")) for (const e of ext) try { if (statSync(join(d, `kilo${e}`)).isFile()) return true; } catch { /* next */ } return false; } private prune() { for (const [id, draft] of this.previews) if (draft.expires < Date.now()) this.previews.delete(id); }
}
