import { createHash, randomUUID } from "node:crypto";
import { existsSync } from "node:fs";
import { lstat, mkdir, open, readFile, rename, rm } from "node:fs/promises";
import { homedir } from "node:os";
import { dirname, join } from "node:path";
import { BadRequestException, ConflictException, Injectable, NotFoundException } from "@nestjs/common";

export type ManagedTomlTool = "codewhale" | "forge" | "deepseek-tui";
type Draft = { path: string; before: string | null; next: string; action: "configure" | "reset"; expires: number };
const hash = (v: string | null) => v === null ? null : createHash("sha256").update(v).digest("hex");

@Injectable()
export class ManagedTomlSettingsService {
  private previews = new Map<string, Draft>(); private tail: Promise<void> = Promise.resolve();
  async status(value: string) { const tool = this.tool(value), path = this.path(tool), source = await this.read(path); return { installed: source !== null || this.commandExists(tool), configured: source !== null && (tool === "deepseek-tui" ? /^# aigate: deepseek-tui-owned$/m.test(source) : /^\s*\[openai\]/m.test(source)), configPath: path }; }
  async preview(value: string, input: unknown) { const tool = this.tool(value); this.prune(); if (this.previews.size >= 20) throw new ConflictException({ code: "PREVIEW_LIMIT", message: "Close or apply an earlier configuration preview, then retry." }); const action = this.object(input)?.["action"]; if (action !== "configure" && action !== "reset") throw new BadRequestException({ code: "INVALID_REQUEST", message: "action must be configure or reset" }); const path = this.path(tool), before = await this.read(path), next = action === "configure" ? this.configure(before, input, tool) : this.reset(before, tool); const previewId = randomUUID(), expires = Date.now() + 300_000; this.previews.set(previewId, { path, before, next, action, expires }); return { previewId, action, configPath: path, backupPath: `${path}.aigate.bak`, diff: this.diff(before ?? "", next), expiresAt: new Date(expires).toISOString() }; }
  async apply(id: string) { const draft = this.previews.get(id); if (!draft || draft.expires < Date.now()) { this.previews.delete(id); throw new NotFoundException({ code: "PREVIEW_EXPIRED", message: "This preview expired. Review a new diff before applying." }); } let release!: () => void; const prior = this.tail; this.tail = new Promise<void>((resolve) => { release = resolve; }); await prior; try { if (hash(await this.read(draft.path)) !== hash(draft.before)) throw new ConflictException({ code: "CONFIG_CHANGED", message: "Settings changed after the preview. Review a fresh diff before applying." }); await mkdir(dirname(draft.path), { recursive: true, mode: 0o700 }); if (draft.before !== null) await this.write(`${draft.path}.aigate.bak`, draft.before); await this.write(draft.path, draft.next); this.previews.delete(id); return { success: true, action: draft.action, configPath: draft.path }; } finally { release(); } }
  private configure(source: string | null, input: unknown, tool: ManagedTomlTool) { const body = this.object(input) ?? {}, baseUrl = typeof body["baseUrl"] === "string" ? body.baseUrl.trim() : "", apiKey = typeof body["apiKey"] === "string" ? body.apiKey : "", model = typeof body["model"] === "string" ? body.model.trim() : ""; let url: URL; try { url = new URL(baseUrl); } catch { throw new BadRequestException({ code: "INVALID_REQUEST", message: "baseUrl must be an absolute HTTP or HTTPS URL" }); } if (!(url.protocol === "http:" || url.protocol === "https:") || url.username || url.password || url.search || url.hash || apiKey.length < 8 || apiKey.length > 4096 || /[\r\n]/.test(apiKey) || !model || model.length > 256) throw new BadRequestException({ code: "INVALID_REQUEST", message: "baseUrl, apiKey, or model is invalid" }); const pathname = url.pathname.replace(/\/+$/, ""); url.pathname = pathname.endsWith("/v1") ? pathname : `${pathname}/v1`; const normalized = url.toString().replace(/\/$/, ""); return tool === "deepseek-tui" ? this.deepseekConfigure(source ?? "", normalized, apiKey, model) : `${this.removeTable(source ?? "", "openai").trimEnd()}${source?.trim() ? "\n\n" : ""}[openai]\nbase_url = ${JSON.stringify(normalized)}\napi_key = ${JSON.stringify(apiKey)}\nmodel = ${JSON.stringify(model)}\n`; }
  private reset(source: string | null, tool: ManagedTomlTool) { return tool === "deepseek-tui" ? this.deepseekReset(source ?? "") : this.removeTable(source ?? "", "openai").trimEnd() + (this.removeTable(source ?? "", "openai").trim() ? "\n" : ""); }
  private tool(value: string): ManagedTomlTool { if (value === "codewhale" || value === "forge" || value === "deepseek-tui") return value; throw new BadRequestException({ code: "INVALID_TOOL", message: "Unsupported CLI tool" }); }
  private path(tool: ManagedTomlTool) { return join(homedir(), tool === "codewhale" ? ".codewhale" : tool === "forge" ? ".forge" : ".deepseek", "config.toml"); }
  private deepseekConfigure(source: string, baseUrl: string, apiKey: string, model: string) { const owned = /^# aigate: deepseek-tui-owned$/m.test(source), previousProvider = this.line(source, "provider") ?? "", previousOpenai = this.table(source, "providers.openai"); let next = this.removeTable(this.removeLine(source, "provider"), "providers.openai").trim(); if (!owned) next = [`# aigate: deepseek-tui-owned`, `# aigate: deepseek-tui-provider ${Buffer.from(previousProvider).toString("base64")}`, `# aigate: deepseek-tui-openai ${Buffer.from(previousOpenai).toString("base64")}`, next].filter(Boolean).join("\n"); return `${next.trim()}${next.trim() ? "\n\n" : ""}provider = "openai"\n\n[providers.openai]\nbase_url = ${JSON.stringify(baseUrl)}\napi_key = ${JSON.stringify(apiKey)}\nmodel = ${JSON.stringify(model)}\n`; }
  private deepseekReset(source: string) { if (!/^# aigate: deepseek-tui-owned$/m.test(source)) return source; const provider = this.marker(source, "provider"), openai = this.marker(source, "openai"); let next = this.removeTable(this.removeLine(source, "provider"), "providers.openai").replace(/^# aigate: deepseek-tui-(?:owned|provider|openai).*\r?\n/gm, "").trim(); next = [next, provider || "provider = \"deepseek\"", openai].filter(Boolean).join("\n\n"); return `${next}\n`; }
  private line(source: string, key: string) { return source.match(new RegExp(`^${key}\\s*=.*$`, "m"))?.[0] ?? null; }
  private removeLine(source: string, key: string) { return source.replace(new RegExp(`^${key}\\s*=.*\\r?\\n?`, "gm"), ""); }
  private marker(source: string, key: string) { const value = source.match(new RegExp(`^# aigate: deepseek-tui-${key}\\s+(.+)$`, "m"))?.[1]; return value ? Buffer.from(value, "base64").toString("utf8") : ""; }
  private table(source: string, table: string) { const lines = source.split(/\r?\n/), start = lines.findIndex((line) => new RegExp(`^\\s*\\[${table}\\]\\s*(?:#.*)?$`).test(line)); if (start < 0) return ""; const end = this.tableEnd(lines, start, table); return lines.slice(start, end < 0 ? lines.length : end).join("\n").trim(); }
  private removeTable(source: string, table: string) { const lines = source.split(/\r?\n/); const start = lines.findIndex((line) => new RegExp(`^\\s*\\[${table}\\]\\s*(?:#.*)?$`).test(line)); if (start < 0) return source; const end = this.tableEnd(lines, start, table); lines.splice(start, (end < 0 ? lines.length : end) - start); return lines.join("\n"); }
  private tableEnd(lines: string[], start: number, table: string) { const nested = new RegExp(`^\\s*\\[${table.replaceAll(".", "\\\\.")}(?:\\.|\\])`); return lines.findIndex((line, index) => index > start && /^\s*\[/.test(line) && !nested.test(line)); }
  private object(value: unknown): Record<string, unknown> | null { return typeof value === "object" && value !== null && !Array.isArray(value) ? Object.fromEntries(Object.entries(value)) : null; }
  private diff(a: string, b: string) { const old = a.split(/\r?\n/).filter(Boolean), next = b.split(/\r?\n/).filter(Boolean), x = new Set(old), y = new Set(next); const redact = (line: string) => line.replace(/((?:api[_-]?key|token|secret)\s*=\s*)"[^"]*"/i, '$1"[redacted]"'); return [...old.filter((line) => !y.has(line)).map((line) => `- ${redact(line)}`), ...next.filter((line) => !x.has(line)).map((line) => `+ ${redact(line)}`)].slice(0, 200); }
  private async read(path: string): Promise<string | null> { try { const info = await lstat(path); if (!info.isFile() || info.isSymbolicLink() || info.size > 1_048_576) throw new Error("CLI config must be a regular file within the 1 MiB limit"); return await readFile(path, "utf8"); } catch (e) { if (typeof e === "object" && e !== null && "code" in e && e.code === "ENOENT") return null; throw e; } }
  private async write(path: string, content: string) { const temp = `${path}.${randomUUID()}.tmp`; let file; try { file = await open(temp, "wx", 0o600); await file.writeFile(content, "utf8"); await file.sync(); await file.close(); file = undefined; await rename(temp, path); } finally { await file?.close().catch(() => undefined); await rm(temp, { force: true }).catch(() => undefined); } }
  private commandExists(tool: ManagedTomlTool) { const names = process.platform === "win32" ? [`${tool}.exe`, `${tool}.cmd`, `${tool}.bat`] : [tool]; return (process.env.PATH ?? "").split(process.platform === "win32" ? ";" : ":").some((directory) => names.some((name) => existsSync(join(directory, name)))); }
  private prune() { for (const [id, draft] of this.previews) if (draft.expires < Date.now()) this.previews.delete(id); }
}
