import { randomUUID } from "node:crypto";
import { readBoundedText, type HttpTransportPort } from "@aigate/engine";
import { Inject, Injectable, ServiceUnavailableException } from "@nestjs/common";
import { HTTP_TRANSPORT } from "../transport/transport.token.js";

type MarketServer = { name: string; title: string; description: string; url: string; transport: "http" | "sse"; requiresAuth: boolean };
const REGISTRY = "https://api.anthropic.com/mcp-registry/v0/servers?limit=100&visibility=commercial,gsuite,gsuite-google", MAX_BYTES = 1_048_576, TTL = 3_600_000;
@Injectable() export class McpMarketplaceService {
  private cached: { at: number; servers: MarketServer[] } | null = null;
  constructor(@Inject(HTTP_TRANSPORT) private readonly transport: HttpTransportPort) {}
  async list(refresh = false) { if (!refresh && this.cached && Date.now() - this.cached.at < TTL) return { cached: true, servers: this.cached.servers }; let response; try { response = await this.transport.send({ method: "GET", url: REGISTRY, headers: { accept: "application/json" }, timeoutMs: 8_000 }, { signal: AbortSignal.timeout(8_000), requestId: randomUUID() }); } catch { throw new ServiceUnavailableException({ code: "MCP_MARKETPLACE_UNAVAILABLE", message: "The MCP marketplace did not respond." }); } if (response.status < 200 || response.status >= 300) throw new ServiceUnavailableException({ code: "MCP_MARKETPLACE_UNAVAILABLE", message: `The MCP marketplace answered HTTP ${response.status}.` }); let body: string; try { body = await readBoundedText(response.body, MAX_BYTES); } catch { throw new ServiceUnavailableException({ code: "MCP_MARKETPLACE_UNAVAILABLE", message: "The MCP marketplace response was too large." }); } let payload: Record<string, unknown> | null; try { payload = this.object(JSON.parse(body)); } catch { payload = null; } if (!payload) throw new ServiceUnavailableException({ code: "MCP_MARKETPLACE_UNAVAILABLE", message: "The MCP marketplace returned invalid JSON." }); const rows = Array.isArray(payload["servers"]) ? payload["servers"] : [], seen = new Set<string>(), servers: MarketServer[] = []; for (const row of rows) { const item = this.object(row), server = this.object(item?.["server"]), meta = this.object(this.object(item?.["_meta"])?.["com.anthropic.api/mcp-registry"]), remote = Array.isArray(server?.["remotes"]) ? this.object(server.remotes[0]) : null, rawUrl = typeof remote?.["url"] === "string" ? remote.url : ""; let url: URL; try { url = new URL(rawUrl); } catch { continue; } if (url.protocol !== "https:" || url.username || url.password || url.search || url.hash || /(?:^|\.)mcp\.claude\.com$/i.test(url.hostname) || seen.has(url.toString())) continue; seen.add(url.toString()); const name = typeof server?.["name"] === "string" ? server.name.trim() : "", title = typeof server?.["title"] === "string" ? server.title.trim() : name, description = typeof server?.["description"] === "string" ? server.description.trim() : ""; if (!name || name.length > 64) continue; servers.push({ name, title, description: description.slice(0, 500), url: url.toString(), transport: remote?.["type"] === "sse" ? "sse" : "http", requiresAuth: meta?.["isAuthless"] !== true }); } this.cached = { at: Date.now(), servers }; return { cached: false, servers }; }
  private object(value: unknown): Record<string, unknown> | null { return typeof value === "object" && value !== null && !Array.isArray(value) ? Object.fromEntries(Object.entries(value)) : null; }
}
