import { randomUUID } from "node:crypto";
import { existsSync } from "node:fs";
import { lstat, mkdir, readFile, rename, rm, writeFile } from "node:fs/promises";
import { join } from "node:path";
import { execFile } from "node:child_process";
import { promisify } from "node:util";
import { request as requestHttp } from "node:http";
import { createServer as createHttpsServer } from "node:https";
import type { Server } from "node:https";
import { BadRequestException, ConflictException, Injectable, NotFoundException, ServiceUnavailableException, type OnModuleDestroy } from "@nestjs/common";
import { TOOLING_DATA_DIR } from "./mcp-server.store.js";
import { Inject } from "@nestjs/common";

const run = promisify(execFile), TTL = 300_000, MAX_OUTPUT = 64 * 1024, HOSTS = ["api.anthropic.com", "api.openai.com", "generativelanguage.googleapis.com"] as const;
type Action = "generate" | "install" | "remove" | "start" | "stop"; type Draft = { action: Action; expires: number };
@Injectable() export class MitmService implements OnModuleDestroy {
  private previews = new Map<string, Draft>();
  private readonly dir: string; private readonly cert: string; private readonly key: string; private readonly caPfx: string; private readonly leaf: string; private readonly leafKey: string; private readonly leafPfx: string; private server: Server | null = null;
  constructor(@Inject(TOOLING_DATA_DIR) dataDir: string) { this.dir = join(dataDir, "mitm"); this.cert = join(this.dir, "aigate-local-ca.pem"); this.key = join(this.dir, "aigate-local-ca.key"); this.caPfx = join(this.dir, "aigate-local-ca.pfx"); this.leaf = join(this.dir, "aigate-mitm-leaf.pem"); this.leafKey = join(this.dir, "aigate-mitm-leaf.key"); this.leafPfx = join(this.dir, "aigate-mitm-leaf.pfx"); }
  async status() { const certificate = await this.file(this.cert), key = await this.file(this.key) || await this.file(this.caPfx), running = this.server?.listening === true; return { listener: { configuredPort: 443, available: await this.file(this.leaf) && (await this.file(this.leafKey) || await this.file(this.leafPfx)), running }, certificate: { path: this.cert, present: certificate, keyPresent: key }, targets: HOSTS.map((host) => ({ host, enabled: running, blockedReason: running ? null : "Start the local TLS listener before enabling interception." })) }; }
  async preview(input: unknown) { const action = this.action(input); if (this.previews.size >= 20) throw new ConflictException({ code: "PREVIEW_LIMIT", message: "Close or apply an earlier MITM preview, then retry." }); const state = await this.status(); if (action === "generate" && state.certificate.present) throw new ConflictException({ code: "MITM_CA_EXISTS", message: "AIGate already has a local CA. Remove it before generating a new one." }); if ((action === "install" || action === "start") && !state.certificate.present) throw new BadRequestException({ code: "MITM_CA_MISSING", message: "Generate the local CA before this action." }); if (action === "start" && state.listener.running) throw new ConflictException({ code: "MITM_RUNNING", message: "The local TLS listener is already running." }); const previewId = randomUUID(), expires = Date.now() + TTL; this.previews.set(previewId, { action, expires }); const changes = action === "generate" ? ["Create a local CA key and certificate under AIGATE_DATA_DIR/mitm."] : action === "install" ? ["Install the AIGate local CA in this machine's trusted root store."] : action === "start" ? ["Generate a leaf certificate for supported IDE hosts.", "Bind a TLS proxy to 127.0.0.1:443.", `Add ${HOSTS.length} marked hosts-file entries that map those hosts to 127.0.0.1.`] : action === "stop" ? ["Remove AIGate's marked hosts-file entries.", "Stop the local TLS proxy."] : ["Remove the AIGate local CA from the trusted root store and AIGATE_DATA_DIR."]; return { previewId, action, certificatePath: this.cert, keyPath: this.key, changes, expiresAt: new Date(expires).toISOString() }; }
  async apply(id: string) { const draft = this.previews.get(id); if (!draft || draft.expires < Date.now()) { this.previews.delete(id); throw new NotFoundException({ code: "PREVIEW_EXPIRED", message: "This preview expired. Review a new MITM change." }); } if (draft.action === "generate") await this.generate(); else if (draft.action === "install") await this.install(); else if (draft.action === "start") await this.start(); else if (draft.action === "stop") await this.stop(); else await this.remove(); this.previews.delete(id); return this.status(); }
  private async generate() { await mkdir(this.dir, { recursive: true, mode: 0o700 }); if (this.openssl()) await this.exec("openssl", ["req", "-x509", "-newkey", "rsa:2048", "-nodes", "-keyout", this.key, "-out", this.cert, "-days", "365", "-subj", "/CN=AIGate Local MITM CA"]); else await this.windowsRoot(); }
  private async install() { if (process.platform !== "win32") throw new ServiceUnavailableException({ code: "MITM_PLATFORM_UNSUPPORTED", message: "Automatic CA installation is currently implemented for Windows only." }); await this.exec("certutil", ["-user", "-addstore", "-f", "Root", this.cert]); }
  private async start() {
    if (this.server?.listening) return;
    await this.generateLeaf();
    const cert = await readFile(this.leaf), key = await this.file(this.leafKey) ? await readFile(this.leafKey) : undefined, pfx = key ? undefined : await readFile(this.leafPfx);
    const port = this.gatewayPort();
    const server = createHttpsServer(key ? { key, cert } : { pfx, passphrase: "" }, (request, response) => {
      const upstream = requestHttp({ host: "127.0.0.1", port, method: request.method, path: request.url, headers: { ...request.headers, host: `127.0.0.1:${port}`, "x-forwarded-host": String(request.headers.host ?? "") } }, (result) => {
        response.writeHead(result.statusCode ?? 502, result.headers); result.pipe(response);
      });
      upstream.on("error", () => { if (!response.headersSent) response.writeHead(502); response.end("AIGate is unavailable."); }); request.pipe(upstream);
    });
    await new Promise<void>((resolve, reject) => { server.once("error", reject); server.listen(443, "127.0.0.1", () => { server.off("error", reject); resolve(); }); });
    this.server = server;
    try { await this.addHosts(); } catch (error) { await this.close(); if (typeof error === "object" && error !== null && "code" in error && (error.code === "EACCES" || error.code === "EPERM")) throw new ServiceUnavailableException({ code: "MITM_HOSTS_PERMISSION_DENIED", message: "Run AIGate from an elevated Windows session to update the hosts file." }); throw error; }
  }
  private async stop() { await this.close(); await this.removeHosts(); }
  private async remove() { await this.stop(); if (process.platform === "win32" && await this.file(this.cert)) { const hash = (await this.exec("certutil", ["-hashfile", this.cert, "SHA1"])).match(/[A-F0-9]{40}/i)?.[0]; if (hash) await this.exec("certutil", ["-user", "-delstore", "Root", hash]); } await rm(this.dir, { recursive: true, force: true }); }
  async onModuleDestroy() { await this.stop().catch(() => undefined); }
  private async generateLeaf() {
    if (await this.file(this.leaf) && (await this.file(this.leafKey) || await this.file(this.leafPfx))) return;
    if (!this.openssl()) { await this.windowsLeaf(); return; }
    const request = join(this.dir, "leaf.csr"), extensions = join(this.dir, "leaf.ext");
    await writeFile(extensions, `subjectAltName=${HOSTS.map((host) => `DNS:${host}`).join(",")}\nextendedKeyUsage=serverAuth\n`, { mode: 0o600 });
    try { await this.exec("openssl", ["req", "-new", "-newkey", "rsa:2048", "-nodes", "-keyout", this.leafKey, "-out", request, "-subj", "/CN=api.openai.com"]); await this.exec("openssl", ["x509", "-req", "-in", request, "-CA", this.cert, "-CAkey", this.key, "-CAcreateserial", "-out", this.leaf, "-days", "365", "-sha256", "-extfile", extensions]); } finally { await Promise.all([rm(request, { force: true }), rm(extensions, { force: true })]); }
  }
  private async close() { const server = this.server; this.server = null; if (server?.listening) await new Promise<void>((resolve, reject) => server.close((error) => error ? reject(error) : resolve())); }
  private async addHosts() { const path = this.hostsPath(), source = await readFile(path, "utf8"); await this.replaceHosts(path, `${this.stripHosts(source).trimEnd()}\n\n# AIGate MITM begin\n${HOSTS.map((host) => `127.0.0.1 ${host}`).join("\n")}\n# AIGate MITM end\n`); }
  private async removeHosts() { const path = this.hostsPath(); try { const source = await readFile(path, "utf8"), stripped = this.stripHosts(source); if (stripped !== source) await this.replaceHosts(path, stripped); } catch (error) { if (!(error instanceof Error) || !("code" in error) || error.code !== "ENOENT") throw error; } }
  private async replaceHosts(path: string, value: string) { const backup = join(this.dir, "hosts.aigate.bak"), temporary = `${path}.aigate-${randomUUID()}.tmp`; await mkdir(this.dir, { recursive: true, mode: 0o700 }); await writeFile(backup, await readFile(path), { mode: 0o600 }); await writeFile(temporary, value); await rename(temporary, path); }
  private stripHosts(source: string) { return source.replace(/\r?\n?# AIGate MITM begin\r?\n[\s\S]*?# AIGate MITM end\r?\n?/g, "\n"); }
  private hostsPath() { return process.platform === "win32" ? join(process.env.SystemRoot ?? "C:\\Windows", "System32", "drivers", "etc", "hosts") : "/etc/hosts"; }
  private gatewayPort() { const value = Number(process.env.PORT ?? 20200); return Number.isInteger(value) && value > 0 && value < 65536 ? value : 20200; }
  private async windowsRoot() { if (process.platform !== "win32") throw new ServiceUnavailableException({ code: "MITM_OPENSSL_MISSING", message: "Install OpenSSL on the AIGate host to generate a local CA." }); await this.powershell("$key=[Security.Cryptography.RSA]::Create(2048);$request=[Security.Cryptography.X509Certificates.CertificateRequest]::new('CN=AIGate Local MITM CA',$key,[Security.Cryptography.HashAlgorithmName]::SHA256,[Security.Cryptography.RSASignaturePadding]::Pkcs1);$request.CertificateExtensions.Add([Security.Cryptography.X509Certificates.X509BasicConstraintsExtension]::new($true,$false,0,$true));$cert=$request.CreateSelfSigned([DateTimeOffset]::UtcNow.AddMinutes(-5),[DateTimeOffset]::UtcNow.AddYears(1));$bytes=$cert.Export([Security.Cryptography.X509Certificates.X509ContentType]::Cert);$pem=\"-----BEGIN CERTIFICATE-----\"+[Environment]::NewLine+([Convert]::ToBase64String($bytes,'InsertLineBreaks'))+[Environment]::NewLine+\"-----END CERTIFICATE-----\"+[Environment]::NewLine;[IO.File]::WriteAllText($args[0],$pem);[IO.File]::WriteAllBytes($args[1],$cert.Export([Security.Cryptography.X509Certificates.X509ContentType]::Pfx,''));", [this.cert, this.caPfx]); }
  private async windowsLeaf() { if (process.platform !== "win32") throw new ServiceUnavailableException({ code: "MITM_OPENSSL_MISSING", message: "Install OpenSSL on the AIGate host to generate a local CA." }); const hosts = HOSTS.join(","); await this.powershell("$ca=[Security.Cryptography.X509Certificates.X509Certificate2]::new($args[0],'',[Security.Cryptography.X509Certificates.X509KeyStorageFlags]::Exportable);$key=[Security.Cryptography.RSA]::Create(2048);$request=[Security.Cryptography.X509Certificates.CertificateRequest]::new('CN=api.openai.com',$key,[Security.Cryptography.HashAlgorithmName]::SHA256,[Security.Cryptography.RSASignaturePadding]::Pkcs1);$san=[Security.Cryptography.X509Certificates.SubjectAlternativeNameBuilder]::new();$args[3].Split(',')|%{$san.AddDnsName($_)};$request.CertificateExtensions.Add($san.Build());$serial=New-Object byte[] 16;[Security.Cryptography.RNGCryptoServiceProvider]::Create().GetBytes($serial);$until=[DateTimeOffset]::new($ca.NotAfter.ToUniversalTime()).AddDays(-1);$issued=$request.Create($ca,[DateTimeOffset]::UtcNow.AddMinutes(-5),$until,$serial);$leaf=[Security.Cryptography.X509Certificates.RSACertificateExtensions]::CopyWithPrivateKey($issued,$key);$bytes=$leaf.Export([Security.Cryptography.X509Certificates.X509ContentType]::Cert);$pem=\"-----BEGIN CERTIFICATE-----\"+[Environment]::NewLine+([Convert]::ToBase64String($bytes,'InsertLineBreaks'))+[Environment]::NewLine+\"-----END CERTIFICATE-----\"+[Environment]::NewLine;[IO.File]::WriteAllText($args[1],$pem);[IO.File]::WriteAllBytes($args[2],$leaf.Export([Security.Cryptography.X509Certificates.X509ContentType]::Pfx,''));", [this.caPfx, this.leaf, this.leafPfx, hosts]); }
  private async powershell(script: string, args: string[]) { const file = join(this.dir, `.aigate-cert-${randomUUID()}.ps1`); await writeFile(file, "$ErrorActionPreference='Stop';" + script, { mode: 0o600 }); try { await this.exec("powershell.exe", ["-NoLogo", "-NoProfile", "-NonInteractive", "-File", file, ...args]); } finally { await rm(file, { force: true }); } }
  private action(input: unknown): Action { const action = typeof input === "object" && input !== null && "action" in input && typeof input.action === "string" ? input.action : ""; if (action === "generate" || action === "install" || action === "remove" || action === "start" || action === "stop") return action; throw new BadRequestException({ code: "INVALID_REQUEST", message: "action must be generate, install, remove, start, or stop" }); }
  private async file(path: string) { try { const item = await lstat(path); return item.isFile() && !item.isSymbolicLink(); } catch { return false; } }
  private openssl() { const exts = process.platform === "win32" ? [".exe", ".cmd", ".bat"] : [""]; return (process.env.PATH ?? "").split(process.platform === "win32" ? ";" : ":").some((dir) => exts.some((ext) => existsSync(join(dir, `openssl${ext}`)))); }
  private async exec(command: string, args: string[]) { try { const result = await run(command, args, { timeout: 30_000, windowsHide: true, maxBuffer: MAX_OUTPUT }); return `${result.stdout}\n${result.stderr}`.slice(0, MAX_OUTPUT); } catch (error) { const value = typeof error === "object" && error !== null ? Object.fromEntries(Object.entries(error)) : {}; throw new ServiceUnavailableException({ code: "MITM_COMMAND_FAILED", message: `${command} failed: ${String(value.stderr ?? value.message ?? "unknown error")}`.slice(0, 512) }); } }
}
