import { createHash, randomUUID } from "node:crypto";
import { existsSync } from "node:fs";
import { lstat, mkdir, open, readFile, rename, rm } from "node:fs/promises";
import { homedir } from "node:os";
import { dirname, join } from "node:path";
import { BadRequestException, ConflictException, Injectable, NotFoundException } from "@nestjs/common";

const FILE = join(homedir(), ".omp", "agent", "models.yml"), hash = (value: string | null) => value === null ? null : createHash("sha256").update(value).digest("hex");
type Draft = { before: string | null; next: string; action: "configure" | "reset"; expires: number };
@Injectable() export class OmpSettingsService {
  private previews = new Map<string, Draft>(); private tail: Promise<void> = Promise.resolve();
  async status() { const source = await this.read(FILE); return { installed: source !== null || this.commandExists(), configured: source !== null && /^  # aigate: omp-owned$/m.test(source), configPath: FILE }; }
  async preview(input: unknown) { this.prune(); if (this.previews.size >= 20) throw new ConflictException({ code: "PREVIEW_LIMIT", message: "Close or apply an earlier configuration preview, then retry." }); const action = this.object(input)?.["action"]; if (action !== "configure" && action !== "reset") throw new BadRequestException({ code: "INVALID_REQUEST", message: "action must be configure or reset" }); const before = await this.read(FILE), next = action === "configure" ? this.configure(before ?? "", input) : this.reset(before ?? ""); const previewId = randomUUID(), expires = Date.now() + 300_000; this.previews.set(previewId, { before, next, action, expires }); return { previewId, action, configPath: FILE, diff: this.diff(before ?? "", next), expiresAt: new Date(expires).toISOString() }; }
  async apply(id: string) { const draft = this.previews.get(id); if (!draft || draft.expires < Date.now()) { this.previews.delete(id); throw new NotFoundException({ code: "PREVIEW_EXPIRED", message: "This preview expired. Review a fresh diff before applying." }); } let release!: () => void; const prior = this.tail; this.tail = new Promise<void>((resolve) => { release = resolve; }); await prior; try { if (hash(await this.read(FILE)) !== hash(draft.before)) throw new ConflictException({ code: "CONFIG_CHANGED", message: "OMP settings changed after the preview. Review a fresh diff before applying." }); await mkdir(dirname(FILE), { recursive: true, mode: 0o700 }); if (draft.before !== null) await this.write(`${FILE}.aigate.bak`, draft.before); await this.write(FILE, draft.next); this.previews.delete(id); return { success: true, action: draft.action, configPath: FILE }; } finally { release(); } }
  private configure(source: string, input: unknown) { const body = this.object(input) ?? {}, baseUrl = this.url(body), apiKey = this.key(body), owned = /^  # aigate: omp-owned$/m.test(source), previous = this.block(source), clean = this.removeBlock(source), block = `  # aigate: omp-owned\n${owned ? "" : `  # aigate: omp-previous ${Buffer.from(previous).toString("base64")}\n`}  9router:\n    baseUrl: ${JSON.stringify(baseUrl)}\n    apiKey: ${JSON.stringify(apiKey)}\n    api: openai-completions\n    authHeader: true\n    disableStrictTools: true\n    discovery:\n      type: proxy`; return this.insert(clean, block) + "\n"; }
  private reset(source: string) { if (!/^  # aigate: omp-owned$/m.test(source)) return source; const previous = this.marker(source), clean = this.removeBlock(source); return previous ? this.insert(clean, previous) + "\n" : clean.trimEnd() + (clean.trim() ? "\n" : ""); }
  private block(source: string) { return source.match(/^  9router:\r?\n(?:    .*\r?\n?)*/m)?.[0].trimEnd() ?? ""; }
  private removeBlock(source: string) { return source.replace(/^  # aigate: omp-owned\r?\n(?:  # aigate: omp-previous .*\r?\n)?  9router:\r?\n(?:    .*\r?\n?)*/m, "").replace(/^  9router:\r?\n(?:    .*\r?\n?)*/m, ""); }
  private marker(source: string) { const value = source.match(/^  # aigate: omp-previous\s+(.+)$/m)?.[1]; return value ? Buffer.from(value, "base64").toString("utf8") : ""; }
  private insert(source: string, block: string) { const header = /^providers:\s*$/m; if (header.test(source)) return source.replace(header, `providers:\n${block}`); return `${source.trimEnd()}${source.trim() ? "\n\n" : ""}providers:\n${block}`; }
  private object(value: unknown): Record<string, unknown> | null { return typeof value === "object" && value !== null && !Array.isArray(value) ? Object.fromEntries(Object.entries(value)) : null; } private key(body: Record<string, unknown>) { const value = typeof body["apiKey"] === "string" ? body.apiKey : ""; if (value.length < 8 || value.length > 4096 || /[\r\n]/.test(value)) throw new BadRequestException({ code: "INVALID_REQUEST", message: "apiKey is invalid" }); return value; } private url(body: Record<string, unknown>) { const raw = typeof body["baseUrl"] === "string" ? body.baseUrl.trim() : ""; let url: URL; try { url = new URL(raw); } catch { throw new BadRequestException({ code: "INVALID_REQUEST", message: "baseUrl must be an absolute HTTP or HTTPS URL" }); } if (!(url.protocol === "http:" || url.protocol === "https:") || url.username || url.password || url.search || url.hash) throw new BadRequestException({ code: "INVALID_REQUEST", message: "baseUrl is invalid" }); const path = url.pathname.replace(/\/+$/, ""); url.pathname = path.endsWith("/v1") ? path : `${path}/v1`; return url.toString().replace(/\/$/, ""); }
  private diff(before: string, after: string) { const old = before.split(/\r?\n/).filter(Boolean), next = after.split(/\r?\n/).filter(Boolean), x = new Set(old), y = new Set(next), redact = (line: string) => line.replace(/(apiKey:\s*)[^\s]+/i, '$1[redacted]'); return [...old.filter((line) => !y.has(line)).map((line) => `- ${redact(line)}`), ...next.filter((line) => !x.has(line)).map((line) => `+ ${redact(line)}`)].slice(0, 200); } private async read(path: string): Promise<string | null> { try { const info = await lstat(path); if (!info.isFile() || info.isSymbolicLink() || info.size > 1_048_576) throw new Error("OMP config must be a regular file within the 1 MiB limit"); return await readFile(path, "utf8"); } catch (error) { if (typeof error === "object" && error !== null && "code" in error && error.code === "ENOENT") return null; throw error; } } private async write(path: string, content: string) { const temp = `${path}.${randomUUID()}.tmp`; let file; try { file = await open(temp, "wx", 0o600); await file.writeFile(content); await file.sync(); await file.close(); file = undefined; await rename(temp, path); } finally { await file?.close().catch(() => undefined); await rm(temp, { force: true }).catch(() => undefined); } } private commandExists() { const names = process.platform === "win32" ? ["omp.exe", "omp.cmd", "omp.bat"] : ["omp"]; return (process.env.PATH ?? "").split(process.platform === "win32" ? ";" : ":").some((directory) => names.some((name) => existsSync(join(directory, name)))); } private prune() { for (const [id, draft] of this.previews) if (draft.expires < Date.now()) this.previews.delete(id); }
}
